create table if not exists public.attack_events (
  id bigint generated by default as identity primary key,
  external_id bigint null,
  occurred_at timestamptz not null,
  source_ip text not null,
  source_country text not null,
  target_port integer not null,
  attack_type text not null,
  severity text not null check (severity in ('critical', 'high', 'low')),
  created_at timestamptz not null default now()
);

create index if not exists attack_events_occurred_at_idx on public.attack_events (occurred_at desc);
create index if not exists attack_events_source_ip_idx on public.attack_events (source_ip);
create index if not exists attack_events_country_idx on public.attack_events (source_country);

alter table public.attack_events enable row level security;

-- Keep RLS strict. Service role bypasses RLS in server-side routes.
drop policy if exists "attack_events_read_auth" on public.attack_events;
create policy "attack_events_read_auth"
  on public.attack_events
  for select
  to authenticated
  using (true);
