import type { Module } from '@/lib/lab/types'

// ─── Learning Path ────────────────────────────────────────────────────────────

export const MODULES: Module[] = [
  {
    id: 'linux-fundamentals',
    title: 'Linux Temelleri',
    subtitle: 'Komut satırına hâkimiyet',
    difficulty: 'beginner',
    color: '#00ff41',
    icon: '🐧',
    toolIds: ['netcat', 'linpeas'],
    topics: [
      'Dosya sistemi hiyerarşisi (FHS)',
      'Temel komutlar: ls, cd, cat, grep, find',
      'Dosya izinleri ve chmod/chown',
      'Stdin/stdout/stderr ve yönlendirme',
      'Pipe zinciri ve metin işleme',
      'Kullanıcı yönetimi ve sudo',
      'Ortam değişkenleri ve PATH',
      'Bash scripting temelleri',
    ],
    resources: [
      { label: 'OverTheWire: Bandit', url: 'https://overthewire.org/wargames/bandit/' },
      { label: 'Linux Journey', url: 'https://linuxjourney.com/' },
      { label: 'The Linux Command Line', url: 'https://linuxcommand.org/tlcl.php' },
    ],
  },
  {
    id: 'network-fundamentals',
    title: 'Ağ Temelleri',
    subtitle: 'TCP/IP, protokoller ve paket analizi',
    difficulty: 'beginner',
    color: '#00d4ff',
    icon: '🌐',
    toolIds: ['nmap', 'wireshark', 'netcat'],
    topics: [
      'OSI ve TCP/IP modeli',
      'IP adresleme ve subnetting',
      'TCP/UDP farkları ve handshake',
      'HTTP/HTTPS, DNS, DHCP, ARP',
      'Wireshark ile paket yakalama',
      'Nmap ile port tarama',
      'Netcat: ağın İsviçre çakısı',
      'Firewall ve IDS/IPS temelleri',
    ],
    resources: [
      { label: 'TryHackMe: Pre-Security', url: 'https://tryhackme.com/path/outline/presecurity' },
      { label: 'Wireshark Docs', url: 'https://www.wireshark.org/docs/' },
      { label: 'Nmap Book', url: 'https://nmap.org/book/' },
    ],
  },
  {
    id: 'web-security',
    title: 'Web Güvenliği',
    subtitle: 'OWASP Top 10 ve pratik saldırılar',
    difficulty: 'intermediate',
    color: '#f59e0b',
    icon: '🕸️',
    toolIds: ['burpsuite', 'sqlmap', 'gobuster', 'ffuf', 'nikto', 'wpscan', 'wfuzz', 'nuclei'],
    topics: [
      'HTTP protokolü derinlemesine',
      'OWASP Top 10 (2021)',
      'SQL Injection (SQLi)',
      'Cross-Site Scripting (XSS)',
      'CSRF, SSRF, XXE',
      'Burp Suite ile intercepting',
      'Directory traversal & LFI/RFI',
      'Authentication bypass teknikleri',
      'JWT ve session yönetimi açıkları',
      'API güvenliği',
    ],
    resources: [
      { label: 'PortSwigger Web Academy', url: 'https://portswigger.net/web-security' },
      { label: 'OWASP Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/' },
      { label: 'HackTheBox Web Challenges', url: 'https://app.hackthebox.com/challenges' },
    ],
  },
  {
    id: 'penetration-testing',
    title: 'Sızma Testi',
    subtitle: 'Metodoloji ve araç kullanımı',
    difficulty: 'intermediate',
    color: '#8b5cf6',
    icon: '🔓',
    toolIds: ['nmap', 'metasploit', 'msfvenom', 'linpeas', 'impacket', 'enum4linux'],
    topics: [
      'Pentest metodolojisi (PTES, OSSTMM)',
      'Kali Linux ortamı',
      'Keşif: Passive & Active Recon',
      'Zafiyet tarama: Nessus, OpenVAS',
      'Metasploit Framework',
      'Post-exploitation teknikleri',
      'Privilege escalation (Linux & Windows)',
      'Pivoting ve lateral movement',
      'Rapor yazımı ve bulgular',
    ],
    resources: [
      { label: 'PTES Standard', url: 'http://www.pentest-standard.org/' },
      { label: 'HackTheBox', url: 'https://www.hackthebox.com/' },
      { label: 'TryHackMe: Jr Pentester', url: 'https://tryhackme.com/path/outline/jrpenetrationtester' },
    ],
  },
  {
    id: 'exploit-development',
    title: 'Exploit Geliştirme',
    subtitle: 'Buffer overflow ve ileri teknikler',
    difficulty: 'advanced',
    color: '#ef4444',
    icon: '💥',
    toolIds: ['gdb', 'metasploit', 'msfvenom', 'radare2'],
    topics: [
      'x86/x64 Assembly temelleri',
      'Stack ve heap yönetimi',
      'Buffer overflow (Stack-based)',
      'Return-Oriented Programming (ROP)',
      'Format string zafiyetleri',
      'ASLR, NX/DEP, Stack Canary bypass',
      'Heap exploitation (Use-after-free)',
      'Kernel exploit geliştirme',
      'CVE analizi ve PoC yazımı',
    ],
    resources: [
      { label: 'PWN.college', url: 'https://pwn.college/' },
      { label: 'exploit.education', url: 'https://exploit.education/' },
      { label: 'LiveOverflow YouTube', url: 'https://www.youtube.com/@LiveOverflow' },
    ],
  },
  {
    id: 'reverse-engineering',
    title: 'Tersine Mühendislik',
    subtitle: 'Binary analiz ve malware inceleme',
    difficulty: 'advanced',
    color: '#f97316',
    icon: '🔬',
    toolIds: ['ghidra', 'gdb', 'radare2', 'binwalk'],
    topics: [
      'ELF ve PE binary formatları',
      'Static analiz: strings, file, objdump',
      'GDB ile dynamic analiz',
      'Radare2 ve Ghidra kullanımı',
      'Crackme çözümleri',
      'Anti-debugging teknikleri',
      'Obfuscation ve packing',
      'Firmware analizi (binwalk)',
    ],
    resources: [
      { label: 'Ghidra (NSA)', url: 'https://ghidra-sre.org/' },
      { label: 'Malware Unicorn Workshops', url: 'https://malwareunicorn.org/' },
      { label: 'Crackmes.one', url: 'https://crackmes.one/' },
    ],
  },
  {
    id: 'malware-analysis',
    title: 'Malware Analizi',
    subtitle: 'Kötü amaçlı yazılım inceleme',
    difficulty: 'advanced',
    color: '#dc2626',
    icon: '🦠',
    toolIds: ['volatility', 'binwalk', 'ghidra', 'wireshark'],
    topics: [
      'Malware türleri: RAT, Ransomware, Rootkit',
      'Güvenli analiz ortamı kurma',
      'Static analiz: PE yapısı, imports',
      'Dynamic analiz: Process Monitor, RegShot',
      'YARA kural yazımı',
      'Network traffic analizi',
      'Memory forensics (Volatility)',
      'Sandbox analizi (Any.run, Cuckoo)',
    ],
    resources: [
      { label: 'ANY.RUN Sandbox', url: 'https://any.run/' },
      { label: 'MalwareBazaar', url: 'https://bazaar.abuse.ch/' },
      { label: 'Practical Malware Analysis (kitap)', url: 'https://www.amazon.com/Practical-Malware-Analysis/dp/1593272901' },
    ],
  },
  {
    id: 'red-team',
    title: 'Red Team Operasyonları',
    subtitle: 'Gelişmiş kalıcı tehdit simülasyonu',
    difficulty: 'expert',
    color: '#7c3aed',
    icon: '🎯',
    toolIds: ['metasploit', 'mimikatz', 'impacket', 'responder', 'msfvenom'],
    topics: [
      'Red Team vs Pentest farkı',
      'MITRE ATT&CK framework',
      'C2 (Command & Control) altyapısı',
      'Cobalt Strike & Sliver',
      'Phishing kampanyaları',
      'Active Directory saldırıları',
      'Kerberoasting, Pass-the-Hash',
      'Evasion ve AV bypass',
      'OPSEC ve iz silme',
    ],
    resources: [
      { label: 'MITRE ATT&CK', url: 'https://attack.mitre.org/' },
      { label: 'Red Team Notes', url: 'https://www.ired.team/' },
      { label: 'VulnLab', url: 'https://www.vulnlab.com/' },
    ],
  },

  // ── 4 Yeni Modül ─────────────────────────────────────────────────────────────

  {
    id: 'cloud-security',
    title: 'Cloud Güvenliği',
    subtitle: 'AWS, GCP ve Azure saldırı yüzeyi',
    difficulty: 'intermediate',
    color: '#06b6d4',
    icon: '☁️',
    toolIds: ['nuclei', 'amass', 'shodan'],
    topics: [
      'Cloud paylaşım modeli (IaaS/PaaS/SaaS)',
      'AWS IAM yanlış yapılandırmaları',
      'S3 bucket açık erişim tespiti',
      'Metadata API saldırıları (SSRF→cloud)',
      'Azure AD ve Entra ID keşfi',
      'GCP service account ayrıcalıkları',
      'Container ve Kubernetes güvenliği',
      'Serverless fonksiyon güvenliği',
      'Cloud forensics ve log analizi',
    ],
    resources: [
      { label: 'HackTricks Cloud', url: 'https://cloud.hacktricks.xyz/' },
      { label: 'CloudGoat (Vulnerable AWS)', url: 'https://github.com/RhinoSecurityLabs/cloudgoat' },
      { label: 'flaws.cloud (AWS Lab)', url: 'http://flaws.cloud/' },
    ],
  },
  {
    id: 'digital-forensics',
    title: 'Dijital Adli Bilişim',
    subtitle: 'Olay müdahale ve delil analizi',
    difficulty: 'advanced',
    color: '#a78bfa',
    icon: '🔍',
    toolIds: ['volatility', 'binwalk', 'wireshark'],
    topics: [
      'DFIR metodolojisi ve zincir muhafaza',
      'Disk imajı alma (dd, FTK Imager)',
      'Dosya sistemi analizi (The Sleuth Kit)',
      'Windows artefaktları (Registry, Prefetch, LNK)',
      'Memory forensics temelleri',
      'Log analizi (Windows Event Log, Syslog)',
      'Timeline analizi ve korelasyon',
      'Ağ trafiği inceleme ve protokol analizi',
      'Olay müdahale raporu yazımı',
    ],
    resources: [
      { label: 'SANS FOR508', url: 'https://www.sans.org/cyber-security-courses/advanced-incident-response-threat-hunting-training/' },
      { label: 'CyberDefenders', url: 'https://cyberdefenders.org/' },
      { label: 'Blue Team Labs Online', url: 'https://blueteamlabs.online/' },
    ],
  },
  {
    id: 'bug-bounty',
    title: 'Bug Bounty',
    subtitle: 'Recon, scope ve responsible disclosure',
    difficulty: 'intermediate',
    color: '#fb923c',
    icon: '🐛',
    toolIds: ['amass', 'sublist3r', 'ffuf', 'gobuster', 'nuclei', 'burpsuite'],
    topics: [
      'Bug bounty platformları (HackerOne, Bugcrowd, Intigriti)',
      'Scope analizi ve program seçimi',
      'Passive recon: Amass, Subfinder, Shodan',
      'Active recon: port tarama, dizin keşfi',
      'OWASP bulgu kategorileri',
      'Zafiyet doğrulama ve PoC hazırlama',
      'Etkili rapor yazımı (CVSS, reproduction steps)',
      'Duplicate önleme taktikleri',
      'Ödül optimizasyonu ve triage süreci',
    ],
    resources: [
      { label: 'HackerOne Hacktivity', url: 'https://hackerone.com/hacktivity' },
      { label: 'Bugcrowd University', url: 'https://www.bugcrowd.com/hackers/bugcrowd-university/' },
      { label: 'NahamCon Talks', url: 'https://www.youtube.com/@NahamSec' },
    ],
  },
  {
    id: 'social-engineering',
    title: 'Sosyal Mühendislik',
    subtitle: 'İnsan faktörü ve manipülasyon teknikleri',
    difficulty: 'beginner',
    color: '#f43f5e',
    icon: '🎭',
    toolIds: ['theharvester', 'maltego', 'spiderfoot'],
    topics: [
      'Sosyal mühendislik psikolojisi',
      'Pretexting ve kimlik taklit',
      'Phishing: hedefli (spear) ve genel',
      'Vishing (telefon tabanlı saldırılar)',
      'Smishing ve QR code saldırıları',
      'OSINT ile hedef profili oluşturma',
      'LinkedIn ve sosyal medya istihbaratı',
      'E-posta sahteciliği (SPF/DKIM/DMARC bypass)',
      'Farkındalık eğitimi ve karşı önlemler',
    ],
    resources: [
      { label: 'Social Engineer Toolkit (SET)', url: 'https://github.com/trustedsec/social-engineer-toolkit' },
      { label: 'Phishme / Cofense', url: 'https://cofense.com/' },
      { label: 'SE-Radio Podcast', url: 'https://www.se-radio.net/' },
    ],
  },
]
