import type { TrainingSet } from '@/lib/lab/types'

// Training Sets

export const TRAINING_SETS: TrainingSet[] = [
  {
    id: 'set-01-foundations',
    title: 'Foundations',
    subtitle: 'Linux terminal mastery, filesystem, and basic analysis routines',
    icon: 'OPS',
    color: '#00ff41',
    overview: {
      heading: 'Operations track',
      summary: 'This set is designed to make you manage the terminal, not just watch it. The goal is not to consume canned commands but to build operator-grade muscle for interpreting the filesystem, permissions, logs, and basic network indicators on your own.',
      pillars: ['Mission-first', 'Manual command discipline', 'Evidence-based validation', 'Operational reflection'],
      assessment: 'Each lesson runs as a mission briefing. You type the command; the system completes the lesson only when it captures the right evidence. Pre-canned terminal injection is disabled for this set.',
    },
    lessons: [
      {
        id: 's01-k01',
        title: 'Operatör çalışma alanını haritalama',
        description: 'Çalışma dizinini, operatör home alanını ve brifing dosyalarını kendi komutlarınla doğrula.',
        difficulty: 'kolay',
        duration: 18,
        mission: {
          objective: 'Operatör home dizininde yön bulmak ve brifing dokümanlarını tespit etmek.',
          operatorBrief: 'Bir operatör oturumu başladığında önce zemin okunur. Hangi klasördesin, hangi brifing dosyaları seni bekliyor ve çalışma alanın nerede; bunları tahmin ederek değil kanıtlayarak öğrenmelisin.',
          task: 'Operatör home dizinine kontrollü geçiş yap, sonra içeriği listeleyip brifing dosyasının göründüğünü kanıtla.',
          evidence: ['Geçiş için açık hedefli bir cd /home/operator komutu kullanılmalı.', 'Listeleme çıktılarında README.txt görünmeli.'],
          hints: ['Yalnızca path yazmak komut değildir; önce geçiş komutu ver.', 'Dizine girdikten sonra listeleme ile brifing dosyasını gör.', '`cd /home/operator` ve ardından `ls -la` ya da `ls -la /home/operator` beklenen kanıtı üretir.'],
          reflection: 'Bu görev, operatörün terminal oturumuna kaotik değil kontrollü girmesini öğretir. Doğru dizini kanıtlamak ve briefing dosyasını bulmak, sonraki her görev için temel bağlam oluşturur.',
          validation: [
            { id: 'command-home', label: 'Geçiş için açık hedefli cd /home/operator komutu kullanıldı', type: 'commandIncludesAll', values: ['cd', '/home/operator'] },
            { id: 'readme-visible', label: 'Listelemede README.txt görüldü', type: 'outputIncludes', values: ['README.txt'] },
          ],
        },
      },
      {
        id: 's01-k02',
        title: 'İzin ve yetki izi tarama',
        description: 'SUID izleri ve operatör dizinindeki izin görünümünü kanıt toplayarak incele.',
        difficulty: 'kolay',
        duration: 22,
        mission: {
          objective: 'Yetki yüzeyini gözle değil, terminal kanıtı ile okumak.',
          operatorBrief: 'Temel operasyonlarda ilk risk taraması genellikle izinlerden başlar. SUID binary listesi ve mevcut dizin izin görünümü, sistemde nereden ilerlenebileceğine dair ilk sinyali verir.',
          task: 'SUID binary araması yap ve kritik bir binary göründüğünü doğrula.',
          evidence: ['Aramada `-4000` perm parametresi kullanılmalı.', '`/usr/bin/sudo` çıktısı içinde görünmeli.'],
          hints: ['`find` komutu izin tabanlı aramayı destekler.', 'SUID aramalarında `-perm -4000` beklenir.', '`find / -perm -4000 2>/dev/null` komutu gerekli kanıtı verir.'],
          reflection: 'SUID ve sudo yüzeyi, yetki yükseltme düşüncesinin giriş kapısıdır. Buradaki amaç istismar etmek değil; sistemin neleri yanlış optimize etmiş olabileceğini görmeyi öğrenmektir.',
          validation: [
            { id: 'find-suid', label: 'SUID taraması uygun perm filtresi ile yapıldı', type: 'commandIncludesAll', values: ['find', '-4000'] },
            { id: 'sudo-found', label: 'Tarama çıktısında `/usr/bin/sudo` bulundu', type: 'outputIncludes', values: ['/usr/bin/sudo'] },
          ],
        },
      },
      {
        id: 's01-k03',
        title: 'Log içinde sinyal ayıklama',
        description: 'auth.log üzerinde başarısız kimlik denemelerini kendi filtrelerinle bul.',
        difficulty: 'kolay',
        duration: 20,
        mission: {
          objective: 'Ham logu hedefli sinyale indirgemek.',
          operatorBrief: 'Gerçek operasyonlarda log okumak, bütün dosyayı izlemek değil; gürültü içinden anlamlı paterni çekip almaktır. Bu derste başarısız SSH denemelerini ayıklayacaksın.',
          task: '`auth.log` içindeki başarısız giriş denemelerini filtrele ve görünür hale getir.',
          evidence: ['Komut zincirinde `grep` kullanılmalı.', 'Çıktı içinde `Failed password` metni yakalanmalı.'],
          hints: ['Log dosyasını önce gör, sonra filtrele.', '`grep` bir pattern ile çalışır.', '`cat /var/log/auth.log | grep "Failed"` veya `grep "Failed" /var/log/auth.log` beklenen yaklaşımdır.'],
          reflection: 'Bu görev, gözle tarama yerine pattern tabanlı düşünmeyi pekiştirir. Analist refleksi, log kalabalığını küçük bir karar alanına indirebildiği anda olgunlaşır.',
          validation: [
            { id: 'grep-used', label: 'Filtreleme için `grep` kullanıldı', type: 'commandIncludesAny', values: ['grep', 'grep -n'] },
            { id: 'failed-password', label: 'Başarısız parola girişleri ekrana getirildi', type: 'outputIncludes', values: ['Failed password'] },
          ],
        },
      },
      {
        id: 's01-k04',
        title: 'Ağ görünürlüğü okuma',
        description: 'Arayüz bilgisi ve açık servisleri okuyarak temel ağ fotoğrafı çıkar.',
        difficulty: 'kolay',
        duration: 18,
        mission: {
          objective: 'Makinenin ağ üzerindeki görünürlüğünü komut kanıtı ile okumak.',
          operatorBrief: 'Bir host hakkında ilk karar, servisleri ve arayüz kimliğini okumadan verilmez. Bu görevde hem IP bilgisini hem de açık dinleyen servisleri tek operatör bakışına çevireceksin.',
          task: 'Yerel arayüzü ve dinleyen servisleri sorgula.',
          evidence: ['Ağ komutlarından biri kullanılmalı.', 'Çıktı içinde `10.0.2.15` adresi görünmeli.'],
          hints: ['`ifconfig` arayüzü, `netstat/ss` ise dinleyen servisleri gösterir.', 'İki ayrı komut kullanman normaldir.', '`ifconfig` ve `netstat -tulpn` ikilisi beklenen tabloyu verir.'],
          reflection: 'Bu aşama, bir hostu sadece IP değil servis kimliğiyle okumayı öğretir. Yüzey okuması zayıf olan operatör, sonraki modüllerde neyi taradığını da doğru seçemez.',
          validation: [
            { id: 'network-command', label: 'Ağ görünürlüğü için `ifconfig` veya `netstat/ss` çalıştırıldı?', type: 'commandIncludesAny', values: ['ifconfig', 'netstat', 'ss'] },
            { id: 'network-output', label: 'IP ya da LISTEN servisi çıktı olarak görüldü?', type: 'outputIncludes', values: ['10.0.2.15'] },
          ],
        },
      },
      {
        id: 's01-o01',
        title: 'Bash ile küçük otomasyon',
        description: 'Tekrarlayan port kontrolünü kısa bir bash döngüsüne çevir.',
        difficulty: 'orta',
        duration: 34,
        mission: {
          objective: 'Tek komut yerine operasyona uygun mini otomasyon kurmak.',
          operatorBrief: 'Aynı işi dört kere elle yapmak yerine bash ile kısa bir denetim ritmi kurabilmelisin. Burada amaç script yazmak değil, operatör refleksi olarak tekrar eden işi otomatikleştirmektir.',
          task: 'Bash üzerinden bir döngü kur ve birden fazla portu satır satır raporla.',
          evidence: ['Komut zincirinde `bash` kullanılmalı.', 'Çıktı içinde `Port 22` ve `Port 443` gibi satırlar görünmeli.'],
          hints: ['Tek satırlık `bash -c` yapısı yeterli.', '`for` döngüsü kullanmak beklenen yaklaşımdır.', '`bash -c \"for p in 22 80 443; do echo Port $p; done\"` mantığı hedefleniyor.'],
          reflection: 'Bu görev, operatörün terminali sadece tüketen değil kompozisyon kuran bir araca dönüştürmesini sağlar. Mikro otomasyonlar sonraki pentest ve keşif akışları için kritik kas hafızasıdır.',
          validation: [
            { id: 'bash-loop', label: 'Bash üzerinden otomasyon akışı kuruldu', type: 'commandIncludesAll', values: ['bash', 'for'] },
            { id: 'port-output', label: 'Port tabanlı satırlar ekrana basıldı', type: 'outputIncludes', values: ['Port 22'] },
          ],
        },
      },
      {
        id: 's01-o02',
        title: 'Servis parmak izi toplama',
        description: 'Nmap ile tek hedef üzerinde servis bilgisi ve varsayılan script çıktıları topla.',
        difficulty: 'orta',
        duration: 32,
        mission: {
          objective: 'Port görüntüsünü servis ve script istihbaratına çevirmek.',
          operatorBrief: 'Basit bir port listesi operasyon için yeterli değildir. Versiyon ve varsayılan script çıktıları, hedefin nasıl bir yüzeye sahip olduğunu anlamak için daha zengin bir brifing üretir.',
          task: 'Bir hedefe servis tespiti yapan nmap taraması uygula.',
          evidence: ['Komutta `nmap` ve `-sV` bulunmalı.', 'Çıktı içinde servis raporu veya `Nmap done` satırı görünmeli.'],
          hints: ['Servis tespiti için `-sV` gerekir.', 'Varsayılan scriptler için `-sC` eklenebilir.', '`nmap -sV -sC 10.10.10.1` beklenen standarda yakındır.'],
          reflection: 'Keşif aşamasında kaliteyi belirleyen şey taramanın hızından çok bilgi yoğunluğudur. Servis parmak izi, sonraki istismar kararlarının isabetini artırır.',
          validation: [
            { id: 'nmap-service', label: 'Nmap servis tespiti bayrağı ile kullanıldı', type: 'commandIncludesAll', values: ['nmap', '-sV'] },
            { id: 'nmap-output', label: 'Tarama raporu ekrana geldi', type: 'outputIncludes', values: ['Nmap done'] },
          ],
        },
      },
      {
        id: 's01-o03',
        title: 'Netcat ile oturum dinleme',
        description: 'Dinleyici port aç ve bağlantı geldiğini terminal kanıtı ile izle.',
        difficulty: 'orta',
        duration: 28,
        mission: {
          objective: 'Dinleme portu açmak ve bağlantı davranışını okumak.',
          operatorBrief: 'Netcat, operatörün minimal ama keskin aracıdır. Bir dinleyici açtığında sadece port açmazsın; bağlantı kabulünün nasıl göründüğünü ve oturumun nasıl aktığını da okumayı öğrenirsin.',
          task: 'Dinleyici modda bir netcat oturumu aç ve bağlantı kabulünü gör.',
          evidence: ['Komutta `nc` veya `netcat` dinleme modunda kullanılmalı.', 'Çıktı içinde `Listening` veya `Connection received` görünmeli.'],
          hints: ['Dinleme için `-l` kullanılır.', 'Port belirtmek gerekir.', '`nc -lvnp 4444` veya benzeri bir dinleyici yeterlidir.'],
          reflection: 'Bu görev, operatörün aktif servis oluşturma ve bağlantı akışına dair sezgisini keskinleştirir. Netcat bilgisi, payload, banner grab ve ters bağlantı senaryoları için temel bir dildir.',
          validation: [
            { id: 'nc-listener', label: 'Netcat dinleyici modunda çalıştırıldı?', type: 'commandIncludesAny', values: ['nc -l', 'nc -lvnp', 'netcat -l'] },
            { id: 'nc-output', label: 'Dinleme ya da bağlantı kabul çıktısı alındı?', type: 'outputIncludes', values: ['Listening on'] },
          ],
        },
      },
      {
        id: 's01-o04',
        title: 'Süreç ve cron davranışı inceleme',
        description: 'Çalışan süreçleri ve zamanlanmış görevleri birlikte okuyarak operasyon izi çıkar.',
        difficulty: 'orta',
        duration: 26,
        mission: {
          objective: 'Makinedeki canlı süreç akışı ile zamanlanmış davranışı beraber yorumlamak.',
          operatorBrief: 'Sistem davranışı sadece aktif süreçlerden ibaret değildir. Cron gibi zamanlanmış işler, persistence veya bakım isimli gizli yüzeyler doğurabilir. Bu derste canlı ve zamanlanmış akışı tek bakışta toplayacaksın.',
          task: 'Çalışan süreçleri gör ve cron kayıtlarına bak.',
          evidence: ['`ps` ya da `top` ile süreç sorgusu yapılmalı.', '`crontab -l` çıktısı görünmeli.'],
          hints: ['Süreçler için `ps aux` yeterlidir.', 'Zamanlanmış görevler için `crontab -l` kullan.', 'İki ayrı komutla ilerlemek beklenen çözümdür.'],
          reflection: 'Bir hostu anlamak, o an ne çalıştığını ve sonra ne çalışacağını birlikte okuyabilmektir. Bu bakış açısı persistence ve anomalileri erkenden ayırt etmene yardım eder.',
          validation: [
            { id: 'process-check', label: 'Süreç görünümü için `ps` ya da `top` kullanıldı?', type: 'commandIncludesAny', values: ['ps', 'top'] },
            { id: 'cron-output', label: 'Crontab kayıtları ekrana getirildi', type: 'outputIncludes', values: ['/usr/bin/backup.sh'] },
          ],
        },
      },
      {
        id: 's01-z01',
        title: 'Yetki yükseltme brifingi',
        description: 'Sudo ve SUID yüzeyinden yükselme ihtimalini brifing formatında kanıtla.',
        difficulty: 'zor',
        duration: 58,
        mission: {
          objective: 'Yüksek riskli yetki yüzeyini exploit etmeden önce okuyup haritalamak.',
          operatorBrief: 'Yetki yükseltme, tek bir sihirli komut değil zemin analizidir. Bu aşamada amaç root almak değil; hangi izin modelinin yükselme fırsatı doğurduğunu brifing formatında ayıklamaktır.',
          task: 'Sudo yetkilerini ve SUID yüzeyini tarayıp kritik bir ipucunu terminalde görünür hale getir.',
          evidence: ['Komutta `sudo -l` kullanılmalı.', 'Çıktı içinde `NOPASSWD` ya da `/usr/bin/vim` görünmeli.'],
          hints: ['İlk soru: kullanıcı sudo ile ne çalıştırabilir?', 'Sonra SUID yüzeyine bak.', '`sudo -l` ve `find / -perm -4000` kombinasyonu tam brifing verir.'],
          reflection: 'Privilege escalation refleksi, exploit seçmeden önce mekanik avantajları görmekle başlar. Bu görev sana teknik karar vermeden önce yüzeyi okuyup sınıflandırmayı öğretir.',
          validation: [
            { id: 'sudo-list', label: 'Sudo yetki listesi sorgulandı', type: 'commandIncludesAll', values: ['sudo', '-l'] },
            { id: 'sudo-vim', label: '`NOPASSWD` veya `vim` yüzeyi görüldü?', type: 'outputIncludes', values: ['NOPASSWD', '/usr/bin/vim'] },
          ],
        },
      },
      {
        id: 's01-z02',
        title: 'Tcpdump ile trafik okuması',
        description: 'Canlı trafik görüntüsünü yorumlayıp veri akışına dair ilk sinyali yakala.',
        difficulty: 'zor',
        duration: 46,
        mission: {
          objective: 'Paket görüntüsünü olay akışına çevirmek.',
          operatorBrief: 'Trafik analizi, paket saymak değil akış okumaktır. Tcpdump çıktıları sana kim kiminle ne zaman haberleşiyor sorusunun ilk cevabını verir. Bu derste görüntü yerine yorum yapmaya hazır bir olay akışına bakacaksın.',
          task: 'Tcpdump ile trafik yakalamayı başlat ve olası HTTPS akışına dair kanıt topla.',
          evidence: ['Komutta `tcpdump` bulunmalı.', 'Çıktı içinde `10.10.10.1.443` veya `Flags [P.]` benzeri trafik satırı görünmeli.'],
          hints: ['Arayüz belirtmek iyi pratiktir.', 'Port filtresi kullanman mantıklı olabilir.', '`tcpdump -i eth0 -n port 80 or port 443` simüle akışı gösterecektir.'],
          reflection: 'Ağ analistinin olgunluğu, tek satırlık paket kaydını davranışa çevirebilmesidir. Bu görev, görsel arayüze bağımlı kalmadan trafik okuma kasını çalıştırır.',
          validation: [
            { id: 'tcpdump-command', label: '`tcpdump` komutu çalıştırıldı?', type: 'commandIncludesAny', values: ['tcpdump', 'wireshark'] },
            { id: 'tcpdump-output', label: 'Canlı trafik akışından kanıt satırı görüldü?', type: 'outputIncludes', values: ['10.10.10.1.443'] },
          ],
        },
      },
      {
        id: 's01-z03',
        title: 'SSH tunneling zihniyeti',
        description: 'Port forwarding fikrini komut seviyesinde kur ve tünel topolojisini doğrula.',
        difficulty: 'zor',
        duration: 52,
        mission: {
          objective: 'SSH tünelleme komutunu mantıklı parametrelerle kurmak.',
          operatorBrief: 'Port forwarding, bir komut ezberi değil trafik topolojisi düşünmektir. Yerel port, uzak hedef ve erişim zinciri arasındaki ilişkiyi anlamadan tünel kurmak sadece kopyala-yapıştır olur.',
          task: 'Yerel port forward mantığını ifade eden bir ssh komutu kur.',
          evidence: ['Komutta `ssh` ve `-L` birlikte geçmeli.', 'Hedef formatında `user@target` benzeri bir tanım görünmeli.'],
          hints: ['Bu görev gerçek bağlantı değil, doğru komut anatomisini kurmakla ilgilidir.', 'Yerel forward için `-L` kullanılır.', '`ssh -L 8080:localhost:80 user@target` benzeri bir iskelet beklenir.'],
          reflection: 'Tunneling bilgisi, pentestte duvar arkası hizmetlere ulaşmanın temel yoludur. Buradaki kazanım tek komut değil; trafik rotasını zihninde kurabilmektir.',
          validation: [
            { id: 'ssh-forward', label: 'SSH local forwarding komutu kuruldu', type: 'commandIncludesAll', values: ['ssh', '-L'] },
            { id: 'ssh-target', label: 'Komutta hedef kullanıcı ve hedef sistemi tanımlandı', type: 'commandIncludesAny', values: ['user@target', 'user@target.com'] },
          ],
        },
      },
    ],
  },

  {
    id: 'set-02-web',
    title: 'Web Attacks',
    subtitle: 'OWASP Top 10, injection, and web application security',
    icon: 'WEB',
    color: '#f59e0b',
    lessons: [
      // ── KOLAY ──────────────────────────────────────────────────────────────
      {
        id: 's02-k01',
        title: 'HTTP Protokolü Derinlemesine',
        description: 'GET/POST/PUT/DELETE metodları, başlıklar, cookie\'ler, HTTP/HTTPS farkları.',
        difficulty: 'kolay',
        practiceCmd: 'curl -v http://10.10.10.1:80',
        duration: 20,
      },
      {
        id: 's02-k02',
        title: 'Dizin Keşfi — Gobuster',
        description: 'Web dizin ve dosya brute-force. /admin, /backup, /.env gibi hassas dizinleri bul.',
        difficulty: 'kolay',
        practiceCmd: 'gobuster dir http://10.10.10.1',
        duration: 25,
      },
      {
        id: 's02-k03',
        title: 'Temel SQL Injection',
        description: 'OR 1=1-- payloadı, boolean-based SQLi mantığı. Login bypass teknikleri.',
        difficulty: 'kolay',
        practiceCmd: 'sqlmap -u "http://target.com?id=1" --dbs',
        duration: 30,
      },
      {
        id: 's02-k04',
        title: 'Reflected XSS',
        description: '<script>alert(1)</script> temel XSS. Giriş sanitizasyonu eksikliğini tespit et.',
        difficulty: 'kolay',
        practiceCmd: 'curl "http://target.com/search?q=<script>alert(1)</script>"',
        duration: 20,
      },
      // ── ORTA ───────────────────────────────────────────────────────────────
      {
        id: 's02-o01',
        title: 'Burp Suite Intercept',
        description: 'Proxy kurulumu, request yakalama ve değiştirme, Repeater, Intruder modülleri.',
        difficulty: 'orta',
        practiceCmd: 'nikto -h http://10.10.10.1',
        duration: 45,
      },
      {
        id: 's02-o02',
        title: 'Gelişmiş SQLmap',
        description: '--dump, --os-shell, --forms bayrakları. Veritabanı dökümü ve tablo çıkarma.',
        difficulty: 'orta',
        practiceCmd: 'sqlmap -u "http://target.com?id=1" --dump --tables',
        duration: 40,
      },
      {
        id: 's02-o03',
        title: 'CSRF & SSRF Saldırıları',
        description: 'Cross-Site Request Forgery token bypass. Server-Side Request Forgery ile iç ağa erişim.',
        difficulty: 'orta',
        practiceCmd: 'curl -X POST http://target.com/api -d "url=http://169.254.169.254/latest/meta-data/"',
        duration: 40,
      },
      {
        id: 's02-o04',
        title: 'JWT Token Manipülasyonu',
        description: 'JWT yapısı, algorithm confusion (none alg), secret brute-force ve token forgery.',
        difficulty: 'orta',
        practiceCmd: 'curl http://target.com/api/profile -H "Authorization: Bearer eyJ..."',
        duration: 35,
      },
      // ── ZOR ────────────────────────────────────────────────────────────────
      {
        id: 's02-z01',
        title: 'Blind SQLi & Out-of-Band',
        description: 'Zaman tabanlı (time-based) ve boolean-based blind SQLi. DNS exfiltration teknikleri.',
        difficulty: 'zor',
        practiceCmd: "sqlmap -u 'http://target.com?id=1' --technique=T --time-sec=5",
        duration: 70,
      },
      {
        id: 's02-z02',
        title: 'Web Shell Upload & RCE',
        description: 'Dosya yükleme bypass teknikleri, MIME type manipülasyonu, PHP webshell ile RCE.',
        difficulty: 'zor',
        practiceCmd: 'wpscan --url http://target.com --enumerate p,u',
        duration: 60,
      },
      {
        id: 's02-z03',
        title: 'API Güvenliği — BOLA/IDOR',
        description: 'Broken Object Level Authorization. API endpoint fuzzing, parametre manipülasyonu.',
        difficulty: 'zor',
        practiceCmd: 'wfuzz -c -z range,1-100 http://api.target.com/users/FUZZ/profile',
        duration: 65,
      },
    ],
  },

  {
    id: 'set-03-pentest',
    title: 'Penetration Testing',
    subtitle: 'Metasploit, credential attacks, and lateral movement',
    icon: 'RED',
    color: '#ef4444',
    lessons: [
      // ── KOLAY ──────────────────────────────────────────────────────────────
      {
        id: 's03-k01',
        title: 'Metasploit Framework Temelleri',
        description: 'msfconsole, search, use, set RHOSTS, exploit komutları. Temel modül yapısı.',
        difficulty: 'kolay',
        practiceCmd: 'msfconsole',
        duration: 30,
      },
      {
        id: 's03-k02',
        title: 'Hydra ile Kimlik Brute-Force',
        description: 'SSH, FTP, HTTP-form-post servisleri için wordlist saldırısı. RockYou kullanımı.',
        difficulty: 'kolay',
        practiceCmd: 'hydra 10.10.10.1 ssh',
        duration: 25,
      },
      {
        id: 's03-k03',
        title: 'SMB Enumeration',
        description: 'enum4linux ile Windows paylaşımları, kullanıcılar ve grup bilgilerini çekme.',
        difficulty: 'kolay',
        practiceCmd: 'enum4linux 10.10.10.1',
        duration: 20,
      },
      {
        id: 's03-k04',
        title: 'Hash Kırma — Hashcat & John',
        description: 'MD5, NTLM, bcrypt hash türleri. Dictionary attack ve rule-based attack.',
        difficulty: 'kolay',
        practiceCmd: 'hashcat 5f4dcc3b5aa765d61d8327deb882cf99',
        duration: 30,
      },
      // ── ORTA ───────────────────────────────────────────────────────────────
      {
        id: 's03-o01',
        title: 'Meterpreter & Post-Exploitation',
        description: 'Shell upgrade, hashdump, getuid, getsystem. Kalıcılık (persistence) teknikleri.',
        difficulty: 'orta',
        practiceCmd: 'msfvenom',
        duration: 50,
      },
      {
        id: 's03-o02',
        title: 'LLMNR/NBT-NS Poisoning',
        description: 'Responder ile NTLM hash yakalama. Pass-the-Hash ve Relay saldırıları.',
        difficulty: 'orta',
        practiceCmd: 'responder eth0',
        duration: 45,
      },
      {
        id: 's03-o03',
        title: 'Active Directory Temelleri',
        description: 'Kerberoasting, AS-REP Roasting, BloodHound ile AD yol analizi.',
        difficulty: 'orta',
        practiceCmd: 'enum4linux -a 10.10.10.1',
        duration: 55,
      },
      {
        id: 's03-o04',
        title: 'Pivoting & Tünelleme',
        description: 'Ele geçirilen makine üzerinden iç ağa erişim. Chisel, SSH dynamic proxy.',
        difficulty: 'orta',
        practiceCmd: 'ssh -D 1080 user@pivot-host',
        duration: 50,
      },
      // ── ZOR ────────────────────────────────────────────────────────────────
      {
        id: 's03-z01',
        title: 'Buffer Overflow — x86',
        description: 'EIP kontrolü, bad char tespiti, shellcode enjeksiyonu. Vanilla stack overflow.',
        difficulty: 'zor',
        practiceCmd: 'python3 -c \'print("A"*100)\' | nc 10.10.10.1 9999',
        duration: 90,
      },
      {
        id: 's03-z02',
        title: 'Pass-the-Ticket & Golden Ticket',
        description: 'Kerberos bilet manipülasyonu. Impacket araçları ile domain compromise.',
        difficulty: 'zor',
        practiceCmd: 'netcat 10.10.10.1 445',
        duration: 75,
      },
      {
        id: 's03-z03',
        title: 'C2 Framework Operasyonu',
        description: 'Command & Control altyapısı. Beacon yönetimi, opsec güvenli komutlar.',
        difficulty: 'zor',
        practiceCmd: 'msfconsole',
        duration: 80,
      },
    ],
  },

  {
    id: 'set-04-advanced',
    title: 'Advanced Operations',
    subtitle: 'Reverse engineering, malware analysis, and red team',
    icon: 'ADV',
    color: '#7c3aed',
    lessons: [
      // ── KOLAY ──────────────────────────────────────────────────────────────
      {
        id: 's04-k01',
        title: 'Binary Analiz Temelleri',
        description: 'file, strings, xxd ile binary inceleme. ELF/PE format yapısı ve section\'lar.',
        difficulty: 'kolay',
        practiceCmd: 'file /bin/ls && strings /bin/ls | head -20',
        duration: 25,
      },
      {
        id: 's04-k02',
        title: 'OSINT Teknikleri',
        description: 'Shodan, theHarvester, Maltego ile hedef hakkında açık kaynak istihbaratı.',
        difficulty: 'kolay',
        practiceCmd: 'amass enum -d target.com',
        duration: 30,
      },
      {
        id: 's04-k03',
        title: 'Malware Sandbox Analizi',
        description: 'Statik ve dinamik analiz farkı. Any.run, VirusTotal, Cuckoo sandbox kullanımı.',
        difficulty: 'kolay',
        practiceCmd: 'strings malware.exe | grep -E "(http|cmd|powershell)" 2>/dev/null',
        duration: 30,
      },
      // ── ORTA ───────────────────────────────────────────────────────────────
      {
        id: 's04-o01',
        title: 'Ghidra ile Tersine Mühendislik',
        description: 'Decompiler kullanımı, fonksiyon analizi, string referansları, patch etme.',
        difficulty: 'orta',
        practiceCmd: 'ghidra',
        duration: 60,
      },
      {
        id: 's04-o02',
        title: 'GDB ile Dinamik Analiz',
        description: 'Breakpoint, watchpoint, register inceleme. PWNDBG/GEF eklentileri.',
        difficulty: 'orta',
        practiceCmd: 'r2 /bin/ls',
        duration: 55,
      },
      {
        id: 's04-o03',
        title: 'Ağ Tabanlı Malware Tespiti',
        description: 'C2 trafik örüntüleri, beaconing tespiti, DNS tünelleme ve exfiltration imzaları.',
        difficulty: 'orta',
        practiceCmd: 'tcpdump -i eth0 -nn -X port 53',
        duration: 50,
      },
      {
        id: 's04-o04',
        title: 'Cloud Güvenliği — AWS/Azure',
        description: 'S3 bucket misconfiguration, IAM privilege escalation, metadata service saldırıları.',
        difficulty: 'orta',
        practiceCmd: 'curl http://169.254.169.254/latest/meta-data/',
        duration: 50,
      },
      // ── ZOR ────────────────────────────────────────────────────────────────
      {
        id: 's04-z01',
        title: 'Özel Implant Geliştirme',
        description: 'Staged payload mimarisi, AV/EDR evasion teknikleri. OPSEC-safe C2 iletişimi.',
        difficulty: 'zor',
        practiceCmd: 'msfvenom',
        duration: 90,
      },
      {
        id: 's04-z02',
        title: 'Dijital Adli Bilişim — DFIR',
        description: 'Volatility ile memory forensics. Artifacts, timeline analizi, IOC çıkarma.',
        difficulty: 'zor',
        practiceCmd: 'strings /proc/1/mem 2>/dev/null | grep -i "password" | head -5',
        duration: 80,
      },
      {
        id: 's04-z03',
        title: 'Red Team Full-Chain Operasyon',
        description: 'Recon → Initial Access → Persistence → Lateral Movement → Exfil. Gerçekçi senaryo.',
        difficulty: 'zor',
        practiceCmd: 'nmap -sV -sC 10.10.10.1',
        duration: 120,
      },
    ],
  },
]
